package it.attendance100.mybicocca.data.mapper

import it.attendance100.mybicocca.data.local.entity.*
import it.attendance100.mybicocca.domain.model.*
import java.time.*
import java.time.format.*

// Helper extensions for manual mapping from LinkedTreeMap (Gson's default for Any)
@Suppress("UNCHECKED_CAST")
fun Any?.asMap(): Map<String, Any?>? = this as? Map<String, Any?>
fun Any?.asList(): List<Any?>? = this as? List<Any?>
fun Map<String, Any?>.getString(key: String): String? = this[key]?.toString()
fun Map<String, Any?>.getDouble(key: String): Double? = (this[key] as? Number)?.toDouble()
fun Map<String, Any?>.getInt(key: String): Int? = (this[key] as? Number)?.toInt()
fun Map<String, Any?>.getBoolean(key: String): Boolean? = this[key] as? Boolean

// --- Payments ---
fun List<Any>?.toPayments(): List<Payment> {
  return this?.mapNotNull { item ->
    val map = item.asMap() ?: return@mapNotNull null
    Payment(
      id = map.getString("invoiceId") ?: map.getString("fatt_id") ?: "",
      title = map.getString("description") ?: map.getString("descrizione") ?: "Payment",
      amount = map.getDouble("amount") ?: map.getDouble("importo") ?: 0.0,
      deadline = map.getString("deadline")?.parseDate() ?: LocalDate.MIN,
      status = parsePaymentStatus(map.getString("status")),
      invoiceUrl = map.getString("url")
    )
  } ?: emptyList()
}

private fun String?.parseDate(): LocalDate? {
  if (this == null) return null
  return try {
    // Try ISO
    LocalDate.parse(this, DateTimeFormatter.ISO_DATE)
  } catch (e: Exception) {
    // Try Italian format?
    try {
      LocalDate.parse(this, DateTimeFormatter.ofPattern("dd/MM/yyyy"))
    } catch (e2: Exception) {
      LocalDate.now() // Fallback
    }
  }
}

private fun parsePaymentStatus(status: String?): PaymentStatus {
  return when (status?.lowercase()) {
    "paid", "pagato" -> PaymentStatus.PAID
    "overdue", "scaduto" -> PaymentStatus.OVERDUE
    "cancelled", "annullato" -> PaymentStatus.CANCELLED
    else -> PaymentStatus.UNPAID
  }
}

// Registrations
fun List<Any>?.toRegistrations(): List<Registration> {
  return this?.mapNotNull { item ->
    val map = item.asMap() ?: return@mapNotNull null
    Registration(
      academicYear = map.getString("academicYear") ?: map.getString("aa_id") ?: "",
      date = map.getString("date")?.parseDate() ?: LocalDate.now(),
      type = map.getString("type") ?: map.getString("tipo") ?: "",
      status = map.getString("status") ?: map.getString("stato") ?: "",
      courseName = map.getString("course") ?: map.getString("corso") ?: ""
    )
  } ?: emptyList()
}

// Calendar Events
fun List<Any>?.toCourseEvents(): List<CourseEvent> {
  return this?.mapNotNull { item ->
    val map = item.asMap() ?: return@mapNotNull null

    val startStr = map.getString("start") ?: map.getString("data_inizio")
    val endStr = map.getString("end") ?: map.getString("data_fine")

    val start = try {
      LocalDateTime.parse(startStr, DateTimeFormatter.ISO_DATE_TIME)
    } catch (e: Exception) {
      LocalDateTime.now()
    }
    val end = try {
      LocalDateTime.parse(endStr, DateTimeFormatter.ISO_DATE_TIME)
    } catch (e: Exception) {
      start.plusHours(1)
    }

    CourseEvent(
      id = 0, // Generated by Room
      courseName = map.getString("title") ?: map.getString("nome") ?: "Event",
      courseCode = map.getString("code") ?: map.getString("codice"),
      professor = map.getString("professor") ?: map.getString("docente"),
      room = map.getString("room") ?: map.getString("aula"),
      building = map.getString("building") ?: map.getString("edificio"),
      startTime = start,
      endTime = end,
      eventType = EventType.LECTURE, // Defaulting
      notes = map.getString("description"),
      color = map.getString("color")
    )
  } ?: emptyList()
}

// Locations
fun List<Any>?.toLocations(): List<Location> {
  return this?.mapNotNull { item ->
    val map = item.asMap() ?: return@mapNotNull null
    Location(
      id = map.getString("id") ?: "",
      name = map.getString("name") ?: map.getString("nome") ?: "",
      description = map.getString("description"),
      category = map.getString("category") ?: "Unknown",
      latitude = map.getDouble("latitude") ?: map.getDouble("lat") ?: 0.0,
      longitude = map.getDouble("longitude") ?: map.getDouble("lng") ?: 0.0,
      address = map.getString("address")
    )
  } ?: emptyList()
}

// --- Exam Sessions (Appeals)
fun List<Any>?.toExamSessions(): List<ExamSession> {
  return this?.mapNotNull { item ->
    val map = item.asMap() ?: return@mapNotNull null
    ExamSession(
      id = map.getString("id") ?: "",
      name = map.getString("name") ?: "",
      code = map.getString("code") ?: "",
      description = map.getString("description") ?: "",
      date = map.getString("date")?.parseDate() ?: LocalDate.now(),
      registrationStartDate = map.getString("regStart")?.parseDate(),
      registrationEndDate = map.getString("regEnd")?.parseDate(),
      type = map.getString("type") ?: "Written",
      classroom = map.getString("room")
    )
  } ?: emptyList()
}
