/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param reportid Report ID
 * @param scheduleid Schedule ID
 */


data class ElearningCoreReportbuilderSchedulesDeleteRequest (

    /* Report ID */
    @SerializedName("reportid")
    val reportid: kotlin.Int,

    /* Schedule ID */
    @SerializedName("scheduleid")
    val scheduleid: kotlin.Int

) {


}

