/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningCoreCompetencyCreateCompetency200Response
import org.openapitools.client.models.ElearningToolLpDataForUserCompetencySummary200ResponseUsercompetency

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param competency 
 * @param usercompetency 
 */


data class ElearningToolLpDataForUserEvidenceListPage200ResponseEvidenceInnerUsercompetenciesInner (

    @SerializedName("competency")
    val competency: ElearningCoreCompetencyCreateCompetency200Response? = null,

    @SerializedName("usercompetency")
    val usercompetency: ElearningToolLpDataForUserCompetencySummary200ResponseUsercompetency? = null

) {


}

