/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param scormid scorm instance id
 * @param organization organization id
 */


data class ElearningModScormGetScormScoesRequest (

    /* scorm instance id */
    @SerializedName("scormid")
    val scormid: kotlin.Int,

    /* organization id */
    @SerializedName("organization")
    val organization: kotlin.String? = ""

) {


}

