/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningAuthEmailSignupUser200ResponseWarningsInner
import org.openapitools.client.models.ElearningModDataAddEntry200ResponseFieldnotificationsInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param fieldnotifications 
 * @param generalnotifications 
 * @param newentryid True new created entry id. 0 if the entry was not created.
 * @param warnings 
 */


data class ElearningModDataAddEntry200Response (

    @SerializedName("fieldnotifications")
    val fieldnotifications: kotlin.collections.List<ElearningModDataAddEntry200ResponseFieldnotificationsInner>,

    @SerializedName("generalnotifications")
    val generalnotifications: kotlin.collections.List<kotlin.Any>,

    /* True new created entry id. 0 if the entry was not created. */
    @SerializedName("newentryid")
    val newentryid: kotlin.Int,

    @SerializedName("warnings")
    val warnings: kotlin.collections.List<ElearningAuthEmailSignupUser200ResponseWarningsInner>? = null

) {


}

