/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningAuthEmailSignupUser200ResponseWarningsInner
import org.openapitools.client.models.ElearningModBigbluebuttonbnGetRecordingsToImport200ResponseTabledata

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param status Whether the fetch was successful
 * @param tabledata 
 * @param warnings 
 */


data class ElearningModBigbluebuttonbnGetRecordingsToImport200Response (

    /* Whether the fetch was successful */
    @SerializedName("status")
    val status: kotlin.Boolean,

    @SerializedName("tabledata")
    val tabledata: ElearningModBigbluebuttonbnGetRecordingsToImport200ResponseTabledata? = null,

    @SerializedName("warnings")
    val warnings: kotlin.collections.List<ElearningAuthEmailSignupUser200ResponseWarningsInner>? = null

) {


}

