/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningModWikiGetSubwikiPagesRequestOptions

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param wikiid Wiki instance ID.
 * @param groupid Subwiki's group ID, -1 means current group. It will be ignored if the wiki doesn't use groups.
 * @param options 
 * @param userid Subwiki's user ID, 0 means current user. It will be ignored in collaborative wikis.
 */


data class ElearningModWikiGetSubwikiPagesRequest (

    /* Wiki instance ID. */
    @SerializedName("wikiid")
    val wikiid: kotlin.Int,

    /* Subwiki's group ID, -1 means current group. It will be ignored if the wiki doesn't use groups. */
    @SerializedName("groupid")
    val groupid: kotlin.Int? = -1,

    @SerializedName("options")
    val options: ElearningModWikiGetSubwikiPagesRequestOptions? = null,

    /* Subwiki's user ID, 0 means current user. It will be ignored in collaborative wikis. */
    @SerializedName("userid")
    val userid: kotlin.Int? = 0

) {


}

