/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param filename File name.
 * @param filepath File path.
 */


data class ElearningModForumPrepareDraftAreaForPostRequestFilestokeepInner (

    /* File name. */
    @SerializedName("filename")
    val filename: kotlin.String? = null,

    /* File path. */
    @SerializedName("filepath")
    val filepath: kotlin.String? = null

) {


}

