/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param courseid The course to enrol the user role in
 * @param quantity Number of items purchased.
 * @param roleid Role to assign to the user
 * @param `suspend` set to 1 to suspend the enrolment
 * @param timeend Timestamp when the enrolment end
 * @param timestart Timestamp when the enrolment start
 * @param userid The user that is going to be enrolled
 */


data class ElearningBlockIomadCompanyAdminEnrolUsersRequestEnrolmentsInner (

    /* The course to enrol the user role in */
    @SerializedName("courseid")
    val courseid: kotlin.Int? = null,

    /* Number of items purchased. */
    @SerializedName("quantity")
    val quantity: kotlin.Int? = null,

    /* Role to assign to the user */
    @SerializedName("roleid")
    val roleid: kotlin.Int? = null,

    /* set to 1 to suspend the enrolment */
    @SerializedName("suspend")
    val `suspend`: kotlin.Int? = null,

    /* Timestamp when the enrolment end */
    @SerializedName("timeend")
    val timeend: kotlin.Int? = null,

    /* Timestamp when the enrolment start */
    @SerializedName("timestart")
    val timestart: kotlin.Int? = null,

    /* The user that is going to be enrolled */
    @SerializedName("userid")
    val userid: kotlin.Int? = null

) {


}

