/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param userid user id
 * @param returnusercount Include count of enrolled users for each course? This can add several seconds to the response time if a user is on several large courses, so set this to false if the value will not be used to improve performance.
 */


data class ElearningCoreEnrolGetUsersCoursesRequest (

    /* user id */
    @SerializedName("userid")
    val userid: kotlin.Int,

    /* Include count of enrolled users for each course? This can add several seconds to the response time if a user is on several large courses, so set this to false if the value will not be used to improve performance. */
    @SerializedName("returnusercount")
    val returnusercount: kotlin.Boolean? = true

) {


}

