/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param sortby The name of a sortable column
 * @param sortorder The direction that this column should be sorted by
 */


data class ElearningCoreTableGetDynamicTableContentRequestSortdataInner (

    /* The name of a sortable column */
    @SerializedName("sortby")
    val sortby: kotlin.String? = null,

    /* The direction that this column should be sorted by */
    @SerializedName("sortorder")
    val sortorder: kotlin.String? = null

) {


}

