/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param ctx Only retrieve tag instances in this context.
 * @param fromctx Context id where this tag cloud is displayed.
 * @param isstandard Whether to return only standard tags.
 * @param limit Maximum number of tags to retrieve.
 * @param rec Retrieve tag instances in the $ctx context and it's children.
 * @param search Search string.
 * @param sort Sort order for display                     (id, name, rawname, count, flag, isstandard, tagcollid).
 * @param tagcollid Tag collection id.
 */


data class ElearningCoreTagGetTagCloudRequest (

    /* Only retrieve tag instances in this context. */
    @SerializedName("ctx")
    val ctx: kotlin.Int? = 0,

    /* Context id where this tag cloud is displayed. */
    @SerializedName("fromctx")
    val fromctx: kotlin.Int? = 0,

    /* Whether to return only standard tags. */
    @SerializedName("isstandard")
    val isstandard: kotlin.Boolean? = false,

    /* Maximum number of tags to retrieve. */
    @SerializedName("limit")
    val limit: kotlin.Int? = 150,

    /* Retrieve tag instances in the $ctx context and it's children. */
    @SerializedName("rec")
    val rec: kotlin.Int? = 1,

    /* Search string. */
    @SerializedName("search")
    val search: kotlin.String? = "",

    /* Sort order for display                     (id, name, rawname, count, flag, isstandard, tagcollid). */
    @SerializedName("sort")
    val sort: kotlin.String? = "name",

    /* Tag collection id. */
    @SerializedName("tagcollid")
    val tagcollid: kotlin.Int? = 0

) {


}

