/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param direction The direction to move
 * @param plugin The name of the plugin
 */


data class ElearningCoreAdminSetPluginOrderRequest (

    /* The direction to move */
    @SerializedName("direction")
    val direction: kotlin.Int,

    /* The name of the plugin */
    @SerializedName("plugin")
    val plugin: kotlin.String

) {


}

