/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningAuthEmailSignupUser200ResponseWarningsInner
import org.openapitools.client.models.ElearningModFeedbackGetItems200ResponseItemsInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param items 
 * @param warnings 
 */


data class ElearningModFeedbackGetItems200Response (

    @SerializedName("items")
    val items: kotlin.collections.List<ElearningModFeedbackGetItems200ResponseItemsInner>,

    @SerializedName("warnings")
    val warnings: kotlin.collections.List<ElearningAuthEmailSignupUser200ResponseWarningsInner>? = null

) {


}

