/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningModForumGetDiscussionPost200ResponsePostAuthorGroupsInnerUrls

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id id
 * @param name name
 * @param urls 
 */


data class ElearningModForumGetDiscussionPost200ResponsePostAuthorGroupsInner (

    /* id */
    @SerializedName("id")
    val id: kotlin.Int? = null,

    /* name */
    @SerializedName("name")
    val name: kotlin.String? = null,

    @SerializedName("urls")
    val urls: ElearningModForumGetDiscussionPost200ResponsePostAuthorGroupsInnerUrls? = null

) {


}

