/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningAuthEmailSignupUser200ResponseWarningsInner
import org.openapitools.client.models.ElearningCoreBlockGetDashboardBlocks200ResponseBlocksInnerContentsFilesInner
import org.openapitools.client.models.ElearningModForumPrepareDraftAreaForPost200ResponseAreaoptionsInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param areaoptions 
 * @param draftitemid Draft item id for the file area.
 * @param messagetext Message text with URLs rewritten.
 * @param files 
 * @param warnings 
 */


data class ElearningModForumPrepareDraftAreaForPost200Response (

    @SerializedName("areaoptions")
    val areaoptions: kotlin.collections.List<ElearningModForumPrepareDraftAreaForPost200ResponseAreaoptionsInner>,

    /* Draft item id for the file area. */
    @SerializedName("draftitemid")
    val draftitemid: kotlin.Int,

    /* Message text with URLs rewritten. */
    @SerializedName("messagetext")
    val messagetext: kotlin.String,

    @SerializedName("files")
    val files: kotlin.collections.List<ElearningCoreBlockGetDashboardBlocks200ResponseBlocksInnerContentsFilesInner>? = null,

    @SerializedName("warnings")
    val warnings: kotlin.collections.List<ElearningAuthEmailSignupUser200ResponseWarningsInner>? = null

) {


}

