/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningAuthEmailSignupUser200ResponseWarningsInner
import org.openapitools.client.models.ElearningCoreCompletionGetActivitiesCompletionStatus200ResponseStatusesInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param statuses 
 * @param warnings 
 */


data class ElearningCoreCompletionGetActivitiesCompletionStatus200Response (

    @SerializedName("statuses")
    val statuses: kotlin.collections.List<ElearningCoreCompletionGetActivitiesCompletionStatus200ResponseStatusesInner>,

    @SerializedName("warnings")
    val warnings: kotlin.collections.List<ElearningAuthEmailSignupUser200ResponseWarningsInner>? = null

) {


}

