/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param component Component
 * @param itemid An identifier for payment area in the component
 * @param paymentarea Payment area in the component
 */


data class ElearningCorePaymentGetAvailableGatewaysRequest (

    /* Component */
    @SerializedName("component")
    val component: kotlin.String,

    /* An identifier for payment area in the component */
    @SerializedName("itemid")
    val itemid: kotlin.Int,

    /* Payment area in the component */
    @SerializedName("paymentarea")
    val paymentarea: kotlin.String

) {


}

