/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param html HTML code.
 * @param id ID of the template.
 */


data class ElearningToolMobileGetContent200ResponseTemplatesInner (

    /* HTML code. */
    @SerializedName("html")
    val html: kotlin.String? = null,

    /* ID of the template. */
    @SerializedName("id")
    val id: kotlin.String? = null

) {


}

