/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param lessonid lesson instance id
 * @param password optional password (the lesson may be protected)
 */


data class ElearningModLessonGetPagesRequest (

    /* lesson instance id */
    @SerializedName("lessonid")
    val lessonid: kotlin.Int,

    /* optional password (the lesson may be protected) */
    @SerializedName("password")
    val password: kotlin.String? = ""

) {


}

