/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningAuthEmailSignupUser200ResponseWarningsInner
import org.openapitools.client.models.ElearningModWorkshopGetSubmission200ResponseSubmission

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param submission 
 * @param warnings 
 */


data class ElearningModWorkshopGetSubmission200Response (

    @SerializedName("submission")
    val submission: ElearningModWorkshopGetSubmission200ResponseSubmission,

    @SerializedName("warnings")
    val warnings: kotlin.collections.List<ElearningAuthEmailSignupUser200ResponseWarningsInner>? = null

) {


}

