/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param timeremaining The number of seconds remaining in this session.
 * @param userid The current user id.
 */


data class ElearningCoreSessionTimeRemaining200Response (

    /* The number of seconds remaining in this session. */
    @SerializedName("timeremaining")
    val timeremaining: kotlin.Int,

    /* The current user id. */
    @SerializedName("userid")
    val userid: kotlin.Int

) {


}

