/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param text the text of the message
 * @param textformat text format (1 = HTML, 0 = MOODLE, 2 = PLAIN, or 4 = MARKDOWN)
 */


data class ElearningCoreMessageSendMessagesToConversationRequestMessagesInner (

    /* the text of the message */
    @SerializedName("text")
    val text: kotlin.String? = null,

    /* text format (1 = HTML, 0 = MOODLE, 2 = PLAIN, or 4 = MARKDOWN) */
    @SerializedName("textformat")
    val textformat: kotlin.Int? = 0

) {


}

