/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param courseid The course id
 * @param moduleid The module id
 */


data class ElearningToolLpDataForCourseCompetenciesPageRequest (

    /* The course id */
    @SerializedName("courseid")
    val courseid: kotlin.Int,

    /* The module id */
    @SerializedName("moduleid")
    val moduleid: kotlin.Int? = 0

) {


}

