/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param userid The id of the user who we are viewing self-conversations for
 * @param messagelimit Limit for number of messages
 * @param messageoffset Offset for messages list
 * @param newestmessagesfirst Order messages by newest first
 */


data class ElearningCoreMessageGetSelfConversationRequest (

    /* The id of the user who we are viewing self-conversations for */
    @SerializedName("userid")
    val userid: kotlin.Int,

    /* Limit for number of messages */
    @SerializedName("messagelimit")
    val messagelimit: kotlin.Int? = 100,

    /* Offset for messages list */
    @SerializedName("messageoffset")
    val messageoffset: kotlin.Int? = 0,

    /* Order messages by newest first */
    @SerializedName("newestmessagesfirst")
    val newestmessagesfirst: kotlin.Boolean? = true

) {


}

