/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningCoreCompetencyListCompetenciesRequestFiltersInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param filters 
 * @param limit Return this number of records at most.
 * @param order Sort direction. Should be either ASC or DESC
 * @param skip Skip this number of records before returning results
 * @param sort Column to sort by.
 */


data class ElearningCoreCompetencyListCompetenciesRequest (

    @SerializedName("filters")
    val filters: kotlin.collections.List<ElearningCoreCompetencyListCompetenciesRequestFiltersInner>,

    /* Return this number of records at most. */
    @SerializedName("limit")
    val limit: kotlin.Int? = 0,

    /* Sort direction. Should be either ASC or DESC */
    @SerializedName("order")
    val order: kotlin.String? = "",

    /* Skip this number of records before returning results */
    @SerializedName("skip")
    val skip: kotlin.Int? = 0,

    /* Column to sort by. */
    @SerializedName("sort")
    val sort: kotlin.String? = ""

) {


}

