/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningCoreCalendarGetCalendarDayView200ResponseNextperiod
import org.openapitools.client.models.ElearningCoreCalendarGetCalendarMonthlyView200ResponseWeeksInnerDaysInnerEventsInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param courseid courseid
 * @param date 
 * @param defaulteventcontext defaulteventcontext
 * @param events 
 * @param filterSelector filter_selector
 * @param isloggedin isloggedin
 * @param categoryid categoryid
 */


data class ElearningCoreCalendarGetCalendarUpcomingView200Response (

    /* courseid */
    @SerializedName("courseid")
    val courseid: kotlin.Int,

    @SerializedName("date")
    val date: ElearningCoreCalendarGetCalendarDayView200ResponseNextperiod,

    /* defaulteventcontext */
    @SerializedName("defaulteventcontext")
    val defaulteventcontext: kotlin.Int = 0,

    @SerializedName("events")
    val events: kotlin.collections.List<ElearningCoreCalendarGetCalendarMonthlyView200ResponseWeeksInnerDaysInnerEventsInner>,

    /* filter_selector */
    @SerializedName("filter_selector")
    val filterSelector: kotlin.String,

    /* isloggedin */
    @SerializedName("isloggedin")
    val isloggedin: kotlin.Boolean,

    /* categoryid */
    @SerializedName("categoryid")
    val categoryid: kotlin.Int? = 0

) {


}

