/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningAuthEmailSignupUser200ResponseWarningsInner
import org.openapitools.client.models.ElearningCoreCalendarGetCalendarEvents200ResponseEventsInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param events 
 * @param warnings 
 */


data class ElearningCoreCalendarGetCalendarEvents200Response (

    @SerializedName("events")
    val events: kotlin.collections.List<ElearningCoreCalendarGetCalendarEvents200ResponseEventsInner>,

    @SerializedName("warnings")
    val warnings: kotlin.collections.List<ElearningAuthEmailSignupUser200ResponseWarningsInner>? = null

) {


}

