/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningCoreRoleAssignRolesRequestAssignmentsInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param assignments 
 */


data class ElearningCoreRoleAssignRolesRequest (

    @SerializedName("assignments")
    val assignments: kotlin.collections.List<ElearningCoreRoleAssignRolesRequestAssignmentsInner>

) {


}

