/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param companyid ID of Iomad Company
 * @param pathid ID learning path
 */


data class ElearningLocalIomadLearningpathGetusersRequest (

    /* ID of Iomad Company */
    @SerializedName("companyid")
    val companyid: kotlin.Int,

    /* ID learning path */
    @SerializedName("pathid")
    val pathid: kotlin.Int

) {


}

