/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningAuthEmailSignupUser200ResponseWarningsInner
import org.openapitools.client.models.ElearningModFeedbackGetItems200ResponseItemsInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param hasnextpage Whether there are more pages.
 * @param hasprevpage Whether is a previous page.
 * @param items 
 * @param warnings 
 */


data class ElearningModFeedbackGetPageItems200Response (

    /* Whether there are more pages. */
    @SerializedName("hasnextpage")
    val hasnextpage: kotlin.Boolean,

    /* Whether is a previous page. */
    @SerializedName("hasprevpage")
    val hasprevpage: kotlin.Boolean,

    @SerializedName("items")
    val items: kotlin.collections.List<ElearningModFeedbackGetItems200ResponseItemsInner>,

    @SerializedName("warnings")
    val warnings: kotlin.collections.List<ElearningAuthEmailSignupUser200ResponseWarningsInner>? = null

) {


}

