/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param competencyid The competency id
 */


data class ElearningToolLpDataForRelatedCompetenciesSectionRequest (

    /* The competency id */
    @SerializedName("competencyid")
    val competencyid: kotlin.Int

) {


}

