/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningModForumGetDiscussionPosts200ResponseRatinginfoScalesInnerItemsInner

import com.google.gson.annotations.SerializedName

/**
 * Scale information
 *
 * @param courseid Course id.
 * @param id Scale id.
 * @param isnumeric Whether is a numeric scale.
 * @param items 
 * @param max Max value for the scale.
 * @param name Scale name (when a real scale is used).
 */


data class ElearningModForumGetDiscussionPosts200ResponseRatinginfoScalesInner (

    /* Course id. */
    @SerializedName("courseid")
    val courseid: kotlin.Int? = null,

    /* Scale id. */
    @SerializedName("id")
    val id: kotlin.Int? = null,

    /* Whether is a numeric scale. */
    @SerializedName("isnumeric")
    val isnumeric: kotlin.Boolean? = null,

    @SerializedName("items")
    val items: kotlin.collections.List<ElearningModForumGetDiscussionPosts200ResponseRatinginfoScalesInnerItemsInner>? = null,

    /* Max value for the scale. */
    @SerializedName("max")
    val max: kotlin.Int? = null,

    /* Scale name (when a real scale is used). */
    @SerializedName("name")
    val name: kotlin.String? = null

) {


}

