/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param drafttext The draft text
 */


data class ElearningTinyAutosaveResumeSession200Response (

    /* The draft text */
    @SerializedName("drafttext")
    val drafttext: kotlin.String

) {


}

