/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param competencyid competencyid
 * @param courseid courseid
 * @param grade grade
 * @param gradename gradename
 * @param id id
 * @param proficiency proficiency
 * @param proficiencyname proficiencyname
 * @param timecreated timecreated
 * @param timemodified timemodified
 * @param userid userid
 * @param usermodified usermodified
 */


data class ElearningToolLpDataForCourseCompetenciesPage200ResponseCompetenciesInnerUsercompetencycourse (

    /* competencyid */
    @SerializedName("competencyid")
    val competencyid: kotlin.Int,

    /* courseid */
    @SerializedName("courseid")
    val courseid: kotlin.Int,

    /* grade */
    @SerializedName("grade")
    val grade: kotlin.Int,

    /* gradename */
    @SerializedName("gradename")
    val gradename: kotlin.String,

    /* id */
    @SerializedName("id")
    val id: kotlin.Int = 0,

    /* proficiency */
    @SerializedName("proficiency")
    val proficiency: kotlin.Boolean,

    /* proficiencyname */
    @SerializedName("proficiencyname")
    val proficiencyname: kotlin.String,

    /* timecreated */
    @SerializedName("timecreated")
    val timecreated: kotlin.Int = 0,

    /* timemodified */
    @SerializedName("timemodified")
    val timemodified: kotlin.Int = 0,

    /* userid */
    @SerializedName("userid")
    val userid: kotlin.Int,

    /* usermodified */
    @SerializedName("usermodified")
    val usermodified: kotlin.Int = 0

) {


}

