/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param convid The conversation id
 * @param currentuserid The current user's id
 * @param limitfrom Limit from
 * @param limitnum Limit number
 * @param newest Newest first?
 * @param timefrom The timestamp from which the messages were created
 */


data class ElearningCoreMessageGetConversationMessagesRequest (

    /* The conversation id */
    @SerializedName("convid")
    val convid: kotlin.Int,

    /* The current user's id */
    @SerializedName("currentuserid")
    val currentuserid: kotlin.Int,

    /* Limit from */
    @SerializedName("limitfrom")
    val limitfrom: kotlin.Int? = 0,

    /* Limit number */
    @SerializedName("limitnum")
    val limitnum: kotlin.Int? = 0,

    /* Newest first? */
    @SerializedName("newest")
    val newest: kotlin.Boolean? = false,

    /* The timestamp from which the messages were created */
    @SerializedName("timefrom")
    val timefrom: kotlin.Int? = 0

) {


}

