/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param aggregateonlygraded exclude empty grades
 * @param aggregateoutcomes aggregate outcomes
 * @param aggregation aggregation method
 * @param aggregationcoef2 weight coefficient
 * @param decimals the decimal count
 * @param display the display type
 * @param droplow drop low grades
 * @param grademax the grade max
 * @param grademin the grade min
 * @param gradepass the grade to pass
 * @param gradetype the grade type
 * @param hiddenuntil grades hidden until
 * @param idnumber the category idnumber
 * @param iteminfo the category iteminfo
 * @param itemname the category total name
 * @param locktime lock grades after
 * @param parentcategoryid The parent category id
 * @param parentcategoryidnumber the parent category idnumber
 * @param weightoverride weight adjusted
 */


data class ElearningCoreGradesCreateGradecategoriesRequestCategoriesInnerOptions (

    /* exclude empty grades */
    @SerializedName("aggregateonlygraded")
    val aggregateonlygraded: kotlin.Boolean? = null,

    /* aggregate outcomes */
    @SerializedName("aggregateoutcomes")
    val aggregateoutcomes: kotlin.Boolean? = null,

    /* aggregation method */
    @SerializedName("aggregation")
    val aggregation: kotlin.Int? = null,

    /* weight coefficient */
    @SerializedName("aggregationcoef2")
    val aggregationcoef2: kotlin.String? = null,

    /* the decimal count */
    @SerializedName("decimals")
    val decimals: kotlin.Int? = null,

    /* the display type */
    @SerializedName("display")
    val display: kotlin.Int? = null,

    /* drop low grades */
    @SerializedName("droplow")
    val droplow: kotlin.Int? = null,

    /* the grade max */
    @SerializedName("grademax")
    val grademax: kotlin.Int? = null,

    /* the grade min */
    @SerializedName("grademin")
    val grademin: kotlin.Int? = null,

    /* the grade to pass */
    @SerializedName("gradepass")
    val gradepass: kotlin.Int? = null,

    /* the grade type */
    @SerializedName("gradetype")
    val gradetype: kotlin.Int? = null,

    /* grades hidden until */
    @SerializedName("hiddenuntil")
    val hiddenuntil: kotlin.Int? = null,

    /* the category idnumber */
    @SerializedName("idnumber")
    val idnumber: kotlin.String? = null,

    /* the category iteminfo */
    @SerializedName("iteminfo")
    val iteminfo: kotlin.String? = null,

    /* the category total name */
    @SerializedName("itemname")
    val itemname: kotlin.String? = null,

    /* lock grades after */
    @SerializedName("locktime")
    val locktime: kotlin.Int? = null,

    /* The parent category id */
    @SerializedName("parentcategoryid")
    val parentcategoryid: kotlin.Int? = null,

    /* the parent category idnumber */
    @SerializedName("parentcategoryidnumber")
    val parentcategoryidnumber: kotlin.String? = null,

    /* weight adjusted */
    @SerializedName("weightoverride")
    val weightoverride: kotlin.Boolean? = null

) {


}

