/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param action action: cm_hide, cm_show, section_hide, section_show, cm_moveleft...
 * @param courseid course id
 * @param ids 
 * @param targetcmid Optional target cm id
 * @param targetsectionid Optional target section id
 */


data class ElearningCoreCourseformatUpdateCourseRequest (

    /* action: cm_hide, cm_show, section_hide, section_show, cm_moveleft... */
    @SerializedName("action")
    val action: kotlin.String,

    /* course id */
    @SerializedName("courseid")
    val courseid: kotlin.Int,

    @SerializedName("ids")
    val ids: kotlin.collections.List<kotlin.Any>? = null,

    /* Optional target cm id */
    @SerializedName("targetcmid")
    val targetcmid: kotlin.Int? = null,

    /* Optional target section id */
    @SerializedName("targetsectionid")
    val targetsectionid: kotlin.Int? = null

) {


}

