/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningCoreCourseDuplicateCourseRequestOptionsInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param categoryid duplicated course category parent
 * @param courseid course to duplicate id
 * @param fullname duplicated course full name
 * @param shortname duplicated course short name
 * @param options 
 * @param visible duplicated course visible, default to yes
 */


data class ElearningCoreCourseDuplicateCourseRequest (

    /* duplicated course category parent */
    @SerializedName("categoryid")
    val categoryid: kotlin.Int,

    /* course to duplicate id */
    @SerializedName("courseid")
    val courseid: kotlin.Int,

    /* duplicated course full name */
    @SerializedName("fullname")
    val fullname: kotlin.String,

    /* duplicated course short name */
    @SerializedName("shortname")
    val shortname: kotlin.String,

    @SerializedName("options")
    val options: kotlin.collections.List<ElearningCoreCourseDuplicateCourseRequestOptionsInner>? = null,

    /* duplicated course visible, default to yes */
    @SerializedName("visible")
    val visible: kotlin.Int? = 1

) {


}

