/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param action The action to perform
 * @param additionaloptions Additional options
 * @param bigbluebuttonbnid bigbluebuttonbn instance id, this might be a different one from the one set in recordingid in case of importing
 * @param recordingid The moodle internal recording ID
 */


data class ElearningModBigbluebuttonbnUpdateRecordingRequest (

    /* The action to perform */
    @SerializedName("action")
    val action: kotlin.String,

    /* Additional options */
    @SerializedName("additionaloptions")
    val additionaloptions: kotlin.String,

    /* bigbluebuttonbn instance id, this might be a different one from the one set in recordingid in case of importing */
    @SerializedName("bigbluebuttonbnid")
    val bigbluebuttonbnid: kotlin.Int,

    /* The moodle internal recording ID */
    @SerializedName("recordingid")
    val recordingid: kotlin.Int

) {


}

