/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningAuthEmailSignupUser200ResponseWarningsInner
import org.openapitools.client.models.ElearningCoreTagGetTagAreas200ResponseAreasInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param areas 
 * @param warnings 
 */


data class ElearningCoreTagGetTagAreas200Response (

    @SerializedName("areas")
    val areas: kotlin.collections.List<ElearningCoreTagGetTagAreas200ResponseAreasInner>,

    @SerializedName("warnings")
    val warnings: kotlin.collections.List<ElearningAuthEmailSignupUser200ResponseWarningsInner>? = null

) {


}

