/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id ID of the grade item
 * @param name The full name of the grade item
 */


data class ElearningGradereportSingleviewGetGradeItemsForSearchWidget200ResponseGradeitemsInner (

    /* ID of the grade item */
    @SerializedName("id")
    val id: kotlin.Int? = null,

    /* The full name of the grade item */
    @SerializedName("name")
    val name: kotlin.String? = null

) {


}

