/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param component component responsible for the update
 * @param itemid identifier of the updated item
 * @param itemtype type of the updated item inside the component
 * @param `value` new value
 */


data class ElearningCoreUpdateInplaceEditableRequest (

    /* component responsible for the update */
    @SerializedName("component")
    val component: kotlin.String,

    /* identifier of the updated item */
    @SerializedName("itemid")
    val itemid: kotlin.String,

    /* type of the updated item inside the component */
    @SerializedName("itemtype")
    val itemtype: kotlin.String,

    /* new value */
    @SerializedName("value")
    val `value`: kotlin.String

) {


}

