/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningAuthEmailSignupUser200ResponseWarningsInner
import org.openapitools.client.models.ElearningModLessonGetPageData200ResponseMessagesInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param attemptsremaining Number of attempts remaining.
 * @param correctanswer Whether the answer is correct.
 * @param displaymenu Whether we should display the menu or not in this page.
 * @param feedback The response feedback.
 * @param inmediatejump Whether the page processing redirect directly to anoter page.
 * @param isessayquestion Whether is a essay question.
 * @param maxattemptsreached Whether we reachered the max number of attempts.
 * @param messages 
 * @param newpageid New page id (if a jump was made).
 * @param noanswer Whether there aren't answers.
 * @param nodefaultresponse Whether there is not a default response.
 * @param ongoingscore The ongoing message.
 * @param progress Progress percentage in the lesson.
 * @param response The response.
 * @param reviewmode Whether the user is reviewing.
 * @param studentanswer The student answer.
 * @param userresponse The user response.
 * @param warnings 
 */


data class ElearningModLessonProcessPage200Response (

    /* Number of attempts remaining. */
    @SerializedName("attemptsremaining")
    val attemptsremaining: kotlin.Int,

    /* Whether the answer is correct. */
    @SerializedName("correctanswer")
    val correctanswer: kotlin.Boolean,

    /* Whether we should display the menu or not in this page. */
    @SerializedName("displaymenu")
    val displaymenu: kotlin.Boolean,

    /* The response feedback. */
    @SerializedName("feedback")
    val feedback: kotlin.String,

    /* Whether the page processing redirect directly to anoter page. */
    @SerializedName("inmediatejump")
    val inmediatejump: kotlin.Boolean,

    /* Whether is a essay question. */
    @SerializedName("isessayquestion")
    val isessayquestion: kotlin.Boolean,

    /* Whether we reachered the max number of attempts. */
    @SerializedName("maxattemptsreached")
    val maxattemptsreached: kotlin.Boolean,

    @SerializedName("messages")
    val messages: kotlin.collections.List<ElearningModLessonGetPageData200ResponseMessagesInner>,

    /* New page id (if a jump was made). */
    @SerializedName("newpageid")
    val newpageid: kotlin.Int,

    /* Whether there aren't answers. */
    @SerializedName("noanswer")
    val noanswer: kotlin.Boolean,

    /* Whether there is not a default response. */
    @SerializedName("nodefaultresponse")
    val nodefaultresponse: kotlin.Boolean,

    /* The ongoing message. */
    @SerializedName("ongoingscore")
    val ongoingscore: kotlin.String,

    /* Progress percentage in the lesson. */
    @SerializedName("progress")
    val progress: kotlin.Int,

    /* The response. */
    @SerializedName("response")
    val response: kotlin.String,

    /* Whether the user is reviewing. */
    @SerializedName("reviewmode")
    val reviewmode: kotlin.Boolean,

    /* The student answer. */
    @SerializedName("studentanswer")
    val studentanswer: kotlin.String,

    /* The user response. */
    @SerializedName("userresponse")
    val userresponse: kotlin.String,

    @SerializedName("warnings")
    val warnings: kotlin.collections.List<ElearningAuthEmailSignupUser200ResponseWarningsInner>? = null

) {


}

