/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param userid Id of the user, default to current user.
 */


data class ElearningCoreUserGetPrivateFilesInfoRequest (

    /* Id of the user, default to current user. */
    @SerializedName("userid")
    val userid: kotlin.Int? = 0

) {


}

