/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param key the user column to search, expected keys (value format) are:                                 \"id\" (int) matching user id,                                 \"name\" (string) license name (Note: you can use % for searching but it may be considerably slower!),                                 \"startdate\" (int) license start date in unix time,                                 \"expirydate\" (int) license expiry date in unix time,                                 \"companyid\" (int) license company id,                                 \"parentid\"  (int) license parent id for split licenses,                                 \"program\"  (bool) license is program,                                 \"instant\"  (bool) license is instant,                                 \"type\"  (int) license type (0 = standard, 1 = reusable, 3 = educator),                                 \"reference\" license reference (Note: you can use % for searching but it may be considerably slower!)
 * @param `value` the value to search
 */


data class ElearningBlockIomadCompanyAdminGetLicenseInfoRequestCriteriaInner (

    /* the user column to search, expected keys (value format) are:                                 \"id\" (int) matching user id,                                 \"name\" (string) license name (Note: you can use % for searching but it may be considerably slower!),                                 \"startdate\" (int) license start date in unix time,                                 \"expirydate\" (int) license expiry date in unix time,                                 \"companyid\" (int) license company id,                                 \"parentid\"  (int) license parent id for split licenses,                                 \"program\"  (bool) license is program,                                 \"instant\"  (bool) license is instant,                                 \"type\"  (int) license type (0 = standard, 1 = reusable, 3 = educator),                                 \"reference\" license reference (Note: you can use % for searching but it may be considerably slower!) */
    @SerializedName("key")
    val key: kotlin.String? = null,

    /* the value to search */
    @SerializedName("value")
    val `value`: kotlin.String? = null

) {


}

