/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningCoreUserSetUserPreferencesRequestPreferencesInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param preferences 
 */


data class ElearningCoreUserSetUserPreferencesRequest (

    @SerializedName("preferences")
    val preferences: kotlin.collections.List<ElearningCoreUserSetUserPreferencesRequestPreferencesInner>

) {


}

