/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param workshopid Workshop instance id.
 * @param groupid Group id, 0 means that the function will determine the user group.                                                    It will return submissions done by users in the given group.
 * @param page The page of records to return.
 * @param perpage The number of records to return per page.
 * @param userid Get submissions done by this user. Use 0 or empty for the current user
 */


data class ElearningModWorkshopGetSubmissionsRequest (

    /* Workshop instance id. */
    @SerializedName("workshopid")
    val workshopid: kotlin.Int,

    /* Group id, 0 means that the function will determine the user group.                                                    It will return submissions done by users in the given group. */
    @SerializedName("groupid")
    val groupid: kotlin.Int? = 0,

    /* The page of records to return. */
    @SerializedName("page")
    val page: kotlin.Int? = 0,

    /* The number of records to return per page. */
    @SerializedName("perpage")
    val perpage: kotlin.Int? = 0,

    /* Get submissions done by this user. Use 0 or empty for the current user */
    @SerializedName("userid")
    val userid: kotlin.Int? = 0

) {


}

