/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param bigbluebuttonbnid bigbluebuttonbn instance id
 * @param groupid Group ID
 * @param tools a set of enabled tools
 */


data class ElearningModBigbluebuttonbnGetRecordingsRequest (

    /* bigbluebuttonbn instance id */
    @SerializedName("bigbluebuttonbnid")
    val bigbluebuttonbnid: kotlin.Int,

    /* Group ID */
    @SerializedName("groupid")
    val groupid: kotlin.Int? = null,

    /* a set of enabled tools */
    @SerializedName("tools")
    val tools: kotlin.String? = "protect,unprotect,publish,unpublish,delete"

) {


}

