/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * functions that are available
 *
 * @param name function name
 * @param version The version number of the component to which the function belongs
 */


data class ElearningCoreWebserviceGetSiteInfo200ResponseFunctionsInner (

    /* function name */
    @SerializedName("name")
    val name: kotlin.String? = null,

    /* The version number of the component to which the function belongs */
    @SerializedName("version")
    val version: kotlin.String? = null

) {


}

