/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param iomadcertificateid iomadcertificate instance id
 */


data class ElearningModIomadcertificateGetIssuedIomadcertificatesRequest (

    /* iomadcertificate instance id */
    @SerializedName("iomadcertificateid")
    val iomadcertificateid: kotlin.Int

) {


}

