/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningCoreBlockGetDashboardBlocks200ResponseBlocksInnerContentsFilesInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param contentfiles 
 * @param course Course id
 * @param coursemodule Course module id
 * @param display How to display the resource
 * @param displayoptions Display options (width, height)
 * @param filterfiles If filters should be applied to the resource content
 * @param groupingid Group id
 * @param groupmode Group mode
 * @param id Activity instance id
 * @param intro Activity introduction
 * @param introfiles 
 * @param introformat intro format (1 = HTML, 0 = MOODLE, 2 = PLAIN, or 4 = MARKDOWN)
 * @param lang Forced activity language
 * @param legacyfiles Legacy files flag
 * @param legacyfileslast Legacy files last control flag
 * @param name Activity name
 * @param revision Incremented when after each file changes, to avoid cache
 * @param section Course section id
 * @param timemodified Last time the resource was modified
 * @param tobemigrated Whether this resource was migrated
 * @param visible Visible
 */


data class ElearningModResourceGetResourcesByCourses200ResponseResourcesInner (

    @SerializedName("contentfiles")
    val contentfiles: kotlin.collections.List<ElearningCoreBlockGetDashboardBlocks200ResponseBlocksInnerContentsFilesInner>? = null,

    /* Course id */
    @SerializedName("course")
    val course: kotlin.Int? = null,

    /* Course module id */
    @SerializedName("coursemodule")
    val coursemodule: kotlin.Int? = null,

    /* How to display the resource */
    @SerializedName("display")
    val display: kotlin.Int? = null,

    /* Display options (width, height) */
    @SerializedName("displayoptions")
    val displayoptions: kotlin.String? = null,

    /* If filters should be applied to the resource content */
    @SerializedName("filterfiles")
    val filterfiles: kotlin.Int? = null,

    /* Group id */
    @SerializedName("groupingid")
    val groupingid: kotlin.Int? = null,

    /* Group mode */
    @SerializedName("groupmode")
    val groupmode: kotlin.Int? = null,

    /* Activity instance id */
    @SerializedName("id")
    val id: kotlin.Int? = null,

    /* Activity introduction */
    @SerializedName("intro")
    val intro: kotlin.String? = null,

    @SerializedName("introfiles")
    val introfiles: kotlin.collections.List<ElearningCoreBlockGetDashboardBlocks200ResponseBlocksInnerContentsFilesInner>? = null,

    /* intro format (1 = HTML, 0 = MOODLE, 2 = PLAIN, or 4 = MARKDOWN) */
    @SerializedName("introformat")
    val introformat: kotlin.Int? = null,

    /* Forced activity language */
    @SerializedName("lang")
    val lang: kotlin.String? = null,

    /* Legacy files flag */
    @SerializedName("legacyfiles")
    val legacyfiles: kotlin.Int? = null,

    /* Legacy files last control flag */
    @SerializedName("legacyfileslast")
    val legacyfileslast: kotlin.Int? = null,

    /* Activity name */
    @SerializedName("name")
    val name: kotlin.String? = null,

    /* Incremented when after each file changes, to avoid cache */
    @SerializedName("revision")
    val revision: kotlin.Int? = null,

    /* Course section id */
    @SerializedName("section")
    val section: kotlin.Int? = null,

    /* Last time the resource was modified */
    @SerializedName("timemodified")
    val timemodified: kotlin.Int? = null,

    /* Whether this resource was migrated */
    @SerializedName("tobemigrated")
    val tobemigrated: kotlin.Int? = null,

    /* Visible */
    @SerializedName("visible")
    val visible: kotlin.Boolean? = null

) {


}

