/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param key the user column to search, expected keys (value format) are:                                 \"id\" (int) matching user id,                                 \"lastname\" (string) user last name (Note: you can use % for searching but it may be considerably slower!),                                 \"firstname\" (string) user first name (Note: you can use % for searching but it may be considerably slower!),                                 \"idnumber\" (string) matching user idnumber,                                 \"username\" (string) matching user username,                                 \"email\" (string) user email (Note: you can use % for searching but it may be considerably slower!),                                 \"auth\" (string) matching user auth plugin
 * @param `value` the value to search
 */


data class ElearningCoreUserGetUsersRequestCriteriaInner (

    /* the user column to search, expected keys (value format) are:                                 \"id\" (int) matching user id,                                 \"lastname\" (string) user last name (Note: you can use % for searching but it may be considerably slower!),                                 \"firstname\" (string) user first name (Note: you can use % for searching but it may be considerably slower!),                                 \"idnumber\" (string) matching user idnumber,                                 \"username\" (string) matching user username,                                 \"email\" (string) user email (Note: you can use % for searching but it may be considerably slower!),                                 \"auth\" (string) matching user auth plugin */
    @SerializedName("key")
    val key: kotlin.String? = null,

    /* the value to search */
    @SerializedName("value")
    val `value`: kotlin.String? = null

) {


}

