/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningCoreCompetencyCreateCompetency200Response
import org.openapitools.client.models.ElearningToolLpDataForCompetencySummary200ResponseComppath
import org.openapitools.client.models.ElearningToolLpDataForCourseCompetenciesPage200ResponseCompetenciesInnerCoursecompetency
import org.openapitools.client.models.ElearningToolLpDataForCourseCompetenciesPage200ResponseCompetenciesInnerCoursemodulesInner
import org.openapitools.client.models.ElearningToolLpDataForCourseCompetenciesPage200ResponseCompetenciesInnerPlansInner
import org.openapitools.client.models.ElearningToolLpDataForCourseCompetenciesPage200ResponseCompetenciesInnerRuleoutcomeoptionsInner
import org.openapitools.client.models.ElearningToolLpDataForCourseCompetenciesPage200ResponseCompetenciesInnerUsercompetencycourse

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param competency 
 * @param comppath 
 * @param coursecompetency 
 * @param coursemodules 
 * @param plans 
 * @param ruleoutcomeoptions 
 * @param usercompetencycourse 
 */


data class ElearningToolLpDataForCourseCompetenciesPage200ResponseCompetenciesInner (

    @SerializedName("competency")
    val competency: ElearningCoreCompetencyCreateCompetency200Response? = null,

    @SerializedName("comppath")
    val comppath: ElearningToolLpDataForCompetencySummary200ResponseComppath? = null,

    @SerializedName("coursecompetency")
    val coursecompetency: ElearningToolLpDataForCourseCompetenciesPage200ResponseCompetenciesInnerCoursecompetency? = null,

    @SerializedName("coursemodules")
    val coursemodules: kotlin.collections.List<ElearningToolLpDataForCourseCompetenciesPage200ResponseCompetenciesInnerCoursemodulesInner>? = null,

    @SerializedName("plans")
    val plans: kotlin.collections.List<ElearningToolLpDataForCourseCompetenciesPage200ResponseCompetenciesInnerPlansInner>? = null,

    @SerializedName("ruleoutcomeoptions")
    val ruleoutcomeoptions: kotlin.collections.List<ElearningToolLpDataForCourseCompetenciesPage200ResponseCompetenciesInnerRuleoutcomeoptionsInner>? = null,

    @SerializedName("usercompetencycourse")
    val usercompetencycourse: ElearningToolLpDataForCourseCompetenciesPage200ResponseCompetenciesInnerUsercompetencycourse? = null

) {


}

