/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param useridto the user id who received the message, 0 for any user
 */


data class ElearningCoreMessageGetUnreadConversationsCountRequest (

    /* the user id who received the message, 0 for any user */
    @SerializedName("useridto")
    val useridto: kotlin.Int

) {


}

