/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param entryid Record entry id.
 */


data class ElearningModDataDeleteEntryRequest (

    /* Record entry id. */
    @SerializedName("entryid")
    val entryid: kotlin.Int

) {


}

