/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param clientmsgid your own client id for the message. If this id is provided, the fail message id will be returned to you
 * @param text the text of the message
 * @param textformat text format (1 = HTML, 0 = MOODLE, 2 = PLAIN, or 4 = MARKDOWN)
 * @param touserid id of the user to send the private message
 */


data class ElearningCoreMessageSendInstantMessagesRequestMessagesInner (

    /* your own client id for the message. If this id is provided, the fail message id will be returned to you */
    @SerializedName("clientmsgid")
    val clientmsgid: kotlin.String? = null,

    /* the text of the message */
    @SerializedName("text")
    val text: kotlin.String? = null,

    /* text format (1 = HTML, 0 = MOODLE, 2 = PLAIN, or 4 = MARKDOWN) */
    @SerializedName("textformat")
    val textformat: kotlin.Int? = 0,

    /* id of the user to send the private message */
    @SerializedName("touserid")
    val touserid: kotlin.Int? = null

) {


}

