/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningModLessonGetUserAttempt200ResponseUserstatsGradeinfo

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param completed Time completed.
 * @param grade Attempt final grade.
 * @param timetotake Time taken.
 * @param gradeinfo 
 */


data class ElearningModLessonGetUserAttempt200ResponseUserstats (

    /* Time completed. */
    @SerializedName("completed")
    val completed: kotlin.Int,

    /* Attempt final grade. */
    @SerializedName("grade")
    val grade: java.math.BigDecimal,

    /* Time taken. */
    @SerializedName("timetotake")
    val timetotake: kotlin.Int,

    @SerializedName("gradeinfo")
    val gradeinfo: ElearningModLessonGetUserAttempt200ResponseUserstatsGradeinfo? = null

) {


}

