/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param author File owner
 * @param component 
 * @param contextid 
 * @param filearea 
 * @param filename 
 * @param filepath 
 * @param filesize File size
 * @param isdir 
 * @param itemid 
 * @param license File license
 * @param timecreated Time created
 * @param timemodified 
 * @param url 
 */


data class ElearningCoreFilesGetFiles200ResponseFilesInner (

    /* File owner */
    @SerializedName("author")
    val author: kotlin.String? = null,

    @SerializedName("component")
    val component: kotlin.String? = null,

    @SerializedName("contextid")
    val contextid: kotlin.Int? = null,

    @SerializedName("filearea")
    val filearea: kotlin.String? = null,

    @SerializedName("filename")
    val filename: kotlin.String? = null,

    @SerializedName("filepath")
    val filepath: kotlin.String? = null,

    /* File size */
    @SerializedName("filesize")
    val filesize: kotlin.Int? = null,

    @SerializedName("isdir")
    val isdir: kotlin.Boolean? = null,

    @SerializedName("itemid")
    val itemid: kotlin.Int? = null,

    /* File license */
    @SerializedName("license")
    val license: kotlin.String? = null,

    /* Time created */
    @SerializedName("timecreated")
    val timecreated: kotlin.Int? = null,

    @SerializedName("timemodified")
    val timemodified: kotlin.Int? = null,

    @SerializedName("url")
    val url: kotlin.String? = null

) {


}

