/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningAuthEmailSignupUser200ResponseWarningsInner
import org.openapitools.client.models.ElearningModLessonGetUserAttempt200ResponseAnswerpagesInner
import org.openapitools.client.models.ElearningModLessonGetUserAttempt200ResponseUserstats

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param answerpages 
 * @param userstats 
 * @param warnings 
 */


data class ElearningModLessonGetUserAttempt200Response (

    @SerializedName("answerpages")
    val answerpages: kotlin.collections.List<ElearningModLessonGetUserAttempt200ResponseAnswerpagesInner>,

    @SerializedName("userstats")
    val userstats: ElearningModLessonGetUserAttempt200ResponseUserstats,

    @SerializedName("warnings")
    val warnings: kotlin.collections.List<ElearningAuthEmailSignupUser200ResponseWarningsInner>? = null

) {


}

