/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningCoreCompletionGetCourseCompletionStatus200ResponseCompletionstatusCompletionsInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param aggregation aggregation method 1 means all, 2 means any
 * @param completed true if the course is complete, false otherwise
 * @param completions 
 */


data class ElearningCoreCompletionGetCourseCompletionStatus200ResponseCompletionstatus (

    /* aggregation method 1 means all, 2 means any */
    @SerializedName("aggregation")
    val aggregation: kotlin.Int,

    /* true if the course is complete, false otherwise */
    @SerializedName("completed")
    val completed: kotlin.Boolean,

    @SerializedName("completions")
    val completions: kotlin.collections.List<ElearningCoreCompletionGetCourseCompletionStatus200ResponseCompletionstatusCompletionsInner>

) {


}

