/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param debuginfo Debug information
 * @param errorcode Error code
 * @param exception Type of the exception
 * @param message Error message
 */


data class ElearningErrorResponse (

    /* Debug information */
    @SerializedName("debuginfo")
    val debuginfo: kotlin.String? = null,

    /* Error code */
    @SerializedName("errorcode")
    val errorcode: kotlin.String? = null,

    /* Type of the exception */
    @SerializedName("exception")
    val exception: kotlin.String? = null,

    /* Error message */
    @SerializedName("message")
    val message: kotlin.String? = null

) {


}

