/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param groupid group record id
 * @param groupingid grouping record id
 */


data class ElearningCoreGroupUnassignGroupingRequestUnassignmentsInner (

    /* group record id */
    @SerializedName("groupid")
    val groupid: kotlin.Int? = null,

    /* grouping record id */
    @SerializedName("groupingid")
    val groupingid: kotlin.Int? = null

) {


}

