/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param coursecategory coursecategory
 * @param courseimage courseimage
 * @param enddate enddate
 * @param fullname fullname
 * @param fullnamedisplay fullnamedisplay
 * @param hasprogress hasprogress
 * @param hidden hidden
 * @param id id
 * @param idnumber idnumber
 * @param isfavourite isfavourite
 * @param pdfexportfont pdfexportfont
 * @param progress progress
 * @param shortname shortname
 * @param showactivitydates showactivitydates
 * @param showcompletionconditions showcompletionconditions
 * @param showshortname showshortname
 * @param startdate startdate
 * @param summary summary
 * @param summaryformat summary format (1 = HTML, 0 = MOODLE, 2 = PLAIN, or 4 = MARKDOWN)
 * @param timeaccess timeaccess
 * @param viewurl viewurl
 * @param visible visible
 */


data class ElearningCoreCourseGetEnrolledCoursesByTimelineClassification200ResponseCoursesInner (

    /* coursecategory */
    @SerializedName("coursecategory")
    val coursecategory: kotlin.String? = null,

    /* courseimage */
    @SerializedName("courseimage")
    val courseimage: kotlin.String? = null,

    /* enddate */
    @SerializedName("enddate")
    val enddate: kotlin.Int? = null,

    /* fullname */
    @SerializedName("fullname")
    val fullname: kotlin.String? = null,

    /* fullnamedisplay */
    @SerializedName("fullnamedisplay")
    val fullnamedisplay: kotlin.String? = null,

    /* hasprogress */
    @SerializedName("hasprogress")
    val hasprogress: kotlin.Boolean? = null,

    /* hidden */
    @SerializedName("hidden")
    val hidden: kotlin.Boolean? = null,

    /* id */
    @SerializedName("id")
    val id: kotlin.Int? = null,

    /* idnumber */
    @SerializedName("idnumber")
    val idnumber: kotlin.String? = null,

    /* isfavourite */
    @SerializedName("isfavourite")
    val isfavourite: kotlin.Boolean? = null,

    /* pdfexportfont */
    @SerializedName("pdfexportfont")
    val pdfexportfont: kotlin.String? = null,

    /* progress */
    @SerializedName("progress")
    val progress: kotlin.Int? = null,

    /* shortname */
    @SerializedName("shortname")
    val shortname: kotlin.String? = null,

    /* showactivitydates */
    @SerializedName("showactivitydates")
    val showactivitydates: kotlin.Boolean? = null,

    /* showcompletionconditions */
    @SerializedName("showcompletionconditions")
    val showcompletionconditions: kotlin.Boolean? = null,

    /* showshortname */
    @SerializedName("showshortname")
    val showshortname: kotlin.Boolean? = null,

    /* startdate */
    @SerializedName("startdate")
    val startdate: kotlin.Int? = null,

    /* summary */
    @SerializedName("summary")
    val summary: kotlin.String? = null,

    /* summary format (1 = HTML, 0 = MOODLE, 2 = PLAIN, or 4 = MARKDOWN) */
    @SerializedName("summaryformat")
    val summaryformat: kotlin.Int? = null,

    /* timeaccess */
    @SerializedName("timeaccess")
    val timeaccess: kotlin.Int? = null,

    /* viewurl */
    @SerializedName("viewurl")
    val viewurl: kotlin.String? = null,

    /* visible */
    @SerializedName("visible")
    val visible: kotlin.Boolean? = null

) {


}

