/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param key Timestamp key
 * @param timestamp Unix timestamp
 */


data class ElearningCoreCalendarGetTimestamps200ResponseTimestampsInner (

    /* Timestamp key */
    @SerializedName("key")
    val key: kotlin.String? = null,

    /* Unix timestamp */
    @SerializedName("timestamp")
    val timestamp: kotlin.Int? = null

) {


}

