/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningAuthEmailSignupUser200ResponseWarningsInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param privatetoken Private token used for auto-login processes.
 * @param token A valid WebService token for the official mobile app service.
 * @param warnings 
 */


data class ElearningToolMobileGetTokensForQrLogin200Response (

    /* Private token used for auto-login processes. */
    @SerializedName("privatetoken")
    val privatetoken: kotlin.String,

    /* A valid WebService token for the official mobile app service. */
    @SerializedName("token")
    val token: kotlin.String,

    @SerializedName("warnings")
    val warnings: kotlin.collections.List<ElearningAuthEmailSignupUser200ResponseWarningsInner>? = null

) {


}

