/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningAuthEmailSignupUserRequestCustomprofilefieldsInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param email A valid and unique email address
 * @param firstname The first name(s) of the user
 * @param lastname The family name of the user
 * @param password Plain text password
 * @param username Username
 * @param city Home city of the user
 * @param country Home country code
 * @param customprofilefields 
 * @param recaptchachallengehash Recaptcha challenge hash
 * @param recaptcharesponse Recaptcha response
 * @param redirect Redirect the user to this site url after confirmation.
 */


data class ElearningAuthEmailSignupUserRequest (

    /* A valid and unique email address */
    @SerializedName("email")
    val email: kotlin.String,

    /* The first name(s) of the user */
    @SerializedName("firstname")
    val firstname: kotlin.String,

    /* The family name of the user */
    @SerializedName("lastname")
    val lastname: kotlin.String,

    /* Plain text password */
    @SerializedName("password")
    val password: kotlin.String,

    /* Username */
    @SerializedName("username")
    val username: kotlin.String,

    /* Home city of the user */
    @SerializedName("city")
    val city: kotlin.String? = "",

    /* Home country code */
    @SerializedName("country")
    val country: kotlin.String? = "",

    @SerializedName("customprofilefields")
    val customprofilefields: kotlin.collections.List<ElearningAuthEmailSignupUserRequestCustomprofilefieldsInner>? = null,

    /* Recaptcha challenge hash */
    @SerializedName("recaptchachallengehash")
    val recaptchachallengehash: kotlin.String? = "",

    /* Recaptcha response */
    @SerializedName("recaptcharesponse")
    val recaptcharesponse: kotlin.String? = "",

    /* Redirect the user to this site url after confirmation. */
    @SerializedName("redirect")
    val redirect: kotlin.String? = ""

) {


}

