/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningCoreCourseGetCoursesByField200ResponseCoursesInnerCustomfieldsInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param customfields 
 * @param description cohort description
 * @param descriptionformat description format (1 = HTML, 0 = MOODLE, 2 = PLAIN, or 4 = MARKDOWN)
 * @param id ID of the cohort
 * @param idnumber cohort idnumber
 * @param name cohort name
 * @param theme cohort theme
 * @param visible cohort visible
 */


data class ElearningToolLpSearchCohorts200ResponseCohortsInner (

    @SerializedName("customfields")
    val customfields: kotlin.collections.List<ElearningCoreCourseGetCoursesByField200ResponseCoursesInnerCustomfieldsInner>? = null,

    /* cohort description */
    @SerializedName("description")
    val description: kotlin.String? = null,

    /* description format (1 = HTML, 0 = MOODLE, 2 = PLAIN, or 4 = MARKDOWN) */
    @SerializedName("descriptionformat")
    val descriptionformat: kotlin.Int? = null,

    /* ID of the cohort */
    @SerializedName("id")
    val id: kotlin.Int? = null,

    /* cohort idnumber */
    @SerializedName("idnumber")
    val idnumber: kotlin.String? = null,

    /* cohort name */
    @SerializedName("name")
    val name: kotlin.String? = null,

    /* cohort theme */
    @SerializedName("theme")
    val theme: kotlin.String? = null,

    /* cohort visible */
    @SerializedName("visible")
    val visible: kotlin.Boolean? = null

) {


}

