/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param instance The module instance id
 * @param module The module name
 */


data class ElearningCoreCourseGetCourseModuleByInstanceRequest (

    /* The module instance id */
    @SerializedName("instance")
    val instance: kotlin.Int,

    /* The module name */
    @SerializedName("module")
    val module: kotlin.String

) {


}

