/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param ignorehidden Ignore hidden events or not
 * @param siteevents Set to true to return site events
 * @param timeend Time to which the events should be returned. We treat 0 and null as no end
 * @param timestart Time from which events should be returned
 * @param userevents Set to true to return current user's user events
 */


data class ElearningCoreCalendarGetCalendarEventsRequestOptions (

    /* Ignore hidden events or not */
    @SerializedName("ignorehidden")
    val ignorehidden: kotlin.Boolean? = true,

    /* Set to true to return site events */
    @SerializedName("siteevents")
    val siteevents: kotlin.Boolean? = true,

    /* Time to which the events should be returned. We treat 0 and null as no end */
    @SerializedName("timeend")
    val timeend: kotlin.Int? = 0,

    /* Time from which events should be returned */
    @SerializedName("timestart")
    val timestart: kotlin.Int? = 0,

    /* Set to true to return current user's user events */
    @SerializedName("userevents")
    val userevents: kotlin.Boolean? = true

) {


}

