/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param canmanage canmanage
 * @param competenciescount competenciescount
 * @param contextid contextid
 * @param contextname contextname
 * @param contextnamenoprefix contextnamenoprefix
 * @param description description
 * @param descriptionformat description format (1 = HTML, 0 = MOODLE, 2 = PLAIN, or 4 = MARKDOWN)
 * @param id id
 * @param idnumber idnumber
 * @param scaleconfiguration scaleconfiguration
 * @param scaleid scaleid
 * @param shortname shortname
 * @param taxonomies taxonomies
 * @param timecreated timecreated
 * @param timemodified timemodified
 * @param usermodified usermodified
 * @param visible visible
 */


data class ElearningToolLpDataForCompetencyFrameworksManagePage200ResponseCompetencyframeworksInner (

    /* canmanage */
    @SerializedName("canmanage")
    val canmanage: kotlin.Boolean? = null,

    /* competenciescount */
    @SerializedName("competenciescount")
    val competenciescount: kotlin.Int? = null,

    /* contextid */
    @SerializedName("contextid")
    val contextid: kotlin.Int? = null,

    /* contextname */
    @SerializedName("contextname")
    val contextname: kotlin.String? = null,

    /* contextnamenoprefix */
    @SerializedName("contextnamenoprefix")
    val contextnamenoprefix: kotlin.String? = null,

    /* description */
    @SerializedName("description")
    val description: kotlin.String? = "",

    /* description format (1 = HTML, 0 = MOODLE, 2 = PLAIN, or 4 = MARKDOWN) */
    @SerializedName("descriptionformat")
    val descriptionformat: kotlin.Int? = 1,

    /* id */
    @SerializedName("id")
    val id: kotlin.Int? = 0,

    /* idnumber */
    @SerializedName("idnumber")
    val idnumber: kotlin.String? = null,

    /* scaleconfiguration */
    @SerializedName("scaleconfiguration")
    val scaleconfiguration: kotlin.String? = null,

    /* scaleid */
    @SerializedName("scaleid")
    val scaleid: kotlin.Int? = null,

    /* shortname */
    @SerializedName("shortname")
    val shortname: kotlin.String? = null,

    /* taxonomies */
    @SerializedName("taxonomies")
    val taxonomies: kotlin.String? = "",

    /* timecreated */
    @SerializedName("timecreated")
    val timecreated: kotlin.Int? = 0,

    /* timemodified */
    @SerializedName("timemodified")
    val timemodified: kotlin.Int? = 0,

    /* usermodified */
    @SerializedName("usermodified")
    val usermodified: kotlin.Int? = 0,

    /* visible */
    @SerializedName("visible")
    val visible: kotlin.Boolean? = 1

) {


}

