/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningCoreBlockGetDashboardBlocks200ResponseBlocksInnerContentsFilesInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param course Course id
 * @param coursemodule Course module id
 * @param display Display type of folder contents on a separate page or inline
 * @param forcedownload Whether file download is forced
 * @param groupingid Group id
 * @param groupmode Group mode
 * @param id Activity instance id
 * @param intro Activity introduction
 * @param introfiles 
 * @param introformat intro format (1 = HTML, 0 = MOODLE, 2 = PLAIN, or 4 = MARKDOWN)
 * @param lang Forced activity language
 * @param name Activity name
 * @param revision Incremented when after each file changes, to avoid cache
 * @param section Course section id
 * @param showdownloadfolder Whether to show the download folder button
 * @param showexpanded 1 = expanded, 0 = collapsed for sub-folders
 * @param timemodified Last time the folder was modified
 * @param visible Visible
 */


data class ElearningModFolderGetFoldersByCourses200ResponseFoldersInner (

    /* Course id */
    @SerializedName("course")
    val course: kotlin.Int? = null,

    /* Course module id */
    @SerializedName("coursemodule")
    val coursemodule: kotlin.Int? = null,

    /* Display type of folder contents on a separate page or inline */
    @SerializedName("display")
    val display: kotlin.Int? = null,

    /* Whether file download is forced */
    @SerializedName("forcedownload")
    val forcedownload: kotlin.Int? = null,

    /* Group id */
    @SerializedName("groupingid")
    val groupingid: kotlin.Int? = null,

    /* Group mode */
    @SerializedName("groupmode")
    val groupmode: kotlin.Int? = null,

    /* Activity instance id */
    @SerializedName("id")
    val id: kotlin.Int? = null,

    /* Activity introduction */
    @SerializedName("intro")
    val intro: kotlin.String? = null,

    @SerializedName("introfiles")
    val introfiles: kotlin.collections.List<ElearningCoreBlockGetDashboardBlocks200ResponseBlocksInnerContentsFilesInner>? = null,

    /* intro format (1 = HTML, 0 = MOODLE, 2 = PLAIN, or 4 = MARKDOWN) */
    @SerializedName("introformat")
    val introformat: kotlin.Int? = null,

    /* Forced activity language */
    @SerializedName("lang")
    val lang: kotlin.String? = null,

    /* Activity name */
    @SerializedName("name")
    val name: kotlin.String? = null,

    /* Incremented when after each file changes, to avoid cache */
    @SerializedName("revision")
    val revision: kotlin.Int? = null,

    /* Course section id */
    @SerializedName("section")
    val section: kotlin.Int? = null,

    /* Whether to show the download folder button */
    @SerializedName("showdownloadfolder")
    val showdownloadfolder: kotlin.Int? = null,

    /* 1 = expanded, 0 = collapsed for sub-folders */
    @SerializedName("showexpanded")
    val showexpanded: kotlin.Int? = null,

    /* Last time the folder was modified */
    @SerializedName("timemodified")
    val timemodified: kotlin.Int? = null,

    /* Visible */
    @SerializedName("visible")
    val visible: kotlin.Boolean? = null

) {


}

