/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id Response id
 * @param name Response name
 * @param printval Response ready for output
 * @param rawval Response raw value
 */


data class ElearningModFeedbackGetResponsesAnalysis200ResponseAnonattemptsInnerResponsesInner (

    /* Response id */
    @SerializedName("id")
    val id: kotlin.Int? = null,

    /* Response name */
    @SerializedName("name")
    val name: kotlin.String? = null,

    /* Response ready for output */
    @SerializedName("printval")
    val printval: kotlin.String? = null,

    /* Response raw value */
    @SerializedName("rawval")
    val rawval: kotlin.String? = null

) {


}

