/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param day day
 * @param hour hour
 * @param key key
 * @param minute minute
 * @param month month
 * @param year year
 */


data class ElearningCoreCalendarGetTimestampsRequestDataInner (

    /* day */
    @SerializedName("day")
    val day: kotlin.Int? = null,

    /* hour */
    @SerializedName("hour")
    val hour: kotlin.Int? = null,

    /* key */
    @SerializedName("key")
    val key: kotlin.String? = null,

    /* minute */
    @SerializedName("minute")
    val minute: kotlin.Int? = null,

    /* month */
    @SerializedName("month")
    val month: kotlin.Int? = null,

    /* year */
    @SerializedName("year")
    val year: kotlin.Int? = null

) {


}

