/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningAuthEmailSignupUser200ResponseWarningsInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param assessmentgradehidden Whether the grade is hidden or not.
 * @param assessmentlongstrgrade The assessment string grade.
 * @param assessmentrawgrade The assessment raw (numeric) grade.
 * @param submissiongradehidden Whether the grade is hidden or not.
 * @param submissionlongstrgrade The submission string grade.
 * @param submissionrawgrade The submission raw (numeric) grade.
 * @param warnings 
 */


data class ElearningModWorkshopGetGrades200Response (

    /* Whether the grade is hidden or not. */
    @SerializedName("assessmentgradehidden")
    val assessmentgradehidden: kotlin.Boolean? = null,

    /* The assessment string grade. */
    @SerializedName("assessmentlongstrgrade")
    val assessmentlongstrgrade: kotlin.String? = null,

    /* The assessment raw (numeric) grade. */
    @SerializedName("assessmentrawgrade")
    val assessmentrawgrade: java.math.BigDecimal? = null,

    /* Whether the grade is hidden or not. */
    @SerializedName("submissiongradehidden")
    val submissiongradehidden: kotlin.Boolean? = null,

    /* The submission string grade. */
    @SerializedName("submissionlongstrgrade")
    val submissionlongstrgrade: kotlin.String? = null,

    /* The submission raw (numeric) grade. */
    @SerializedName("submissionrawgrade")
    val submissionrawgrade: java.math.BigDecimal? = null,

    @SerializedName("warnings")
    val warnings: kotlin.collections.List<ElearningAuthEmailSignupUser200ResponseWarningsInner>? = null

) {


}

