/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * warning
 *
 * @param item item can be 'course' (errorcode 1 or 2) or 'module' (errorcode 1)
 * @param itemid When item is a course then itemid is a course id. When the item is a module then itemid is a module id
 * @param message untranslated english message to explain the warning
 * @param warningcode errorcode can be 1 (no access rights) or 2 (not enrolled or no permissions)
 */


data class ElearningModAssignGetAssignments200ResponseWarningsInner (

    /* item can be 'course' (errorcode 1 or 2) or 'module' (errorcode 1) */
    @SerializedName("item")
    val item: kotlin.String? = null,

    /* When item is a course then itemid is a course id. When the item is a module then itemid is a module id */
    @SerializedName("itemid")
    val itemid: kotlin.Int? = null,

    /* untranslated english message to explain the warning */
    @SerializedName("message")
    val message: kotlin.String? = null,

    /* errorcode can be 1 (no access rights) or 2 (not enrolled or no permissions) */
    @SerializedName("warningcode")
    val warningcode: kotlin.String? = null

) {


}

