/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningCoreGradingSaveDefinitionsRequestAreasInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param areas 
 */


data class ElearningCoreGradingSaveDefinitionsRequest (

    @SerializedName("areas")
    val areas: kotlin.collections.List<ElearningCoreGradingSaveDefinitionsRequestAreasInner>

) {


}

