/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningCoreBlockGetDashboardBlocks200ResponseBlocksInnerContentsFilesInner

import com.google.gson.annotations.SerializedName

/**
 * Choices
 *
 * @param allowmultiple Allow multiple choices
 * @param allowupdate Allow update
 * @param completionsubmit Completion on user submission
 * @param course Course id
 * @param coursemodule Course module id
 * @param display Display mode (vertical, horizontal)
 * @param groupingid Group id
 * @param groupmode Group mode
 * @param id Activity instance id
 * @param includeinactive Include inactive users
 * @param intro Activity introduction
 * @param introfiles 
 * @param introformat intro format (1 = HTML, 0 = MOODLE, 2 = PLAIN, or 4 = MARKDOWN)
 * @param lang Forced activity language
 * @param limitanswers Limit unswers
 * @param name Activity name
 * @param publish If choice is published
 * @param section Course section id
 * @param showavailable Show available spaces
 * @param showpreview Show preview before timeopen
 * @param showresults 0 never, 1 after answer, 2 after close, 3 always
 * @param showunanswered Show users who not answered yet
 * @param timeclose Date of closing validity
 * @param timemodified Time of last modification
 * @param timeopen Date of opening validity
 * @param visible Visible
 */


data class ElearningModChoiceGetChoicesByCourses200ResponseChoicesInner (

    /* Allow multiple choices */
    @SerializedName("allowmultiple")
    val allowmultiple: kotlin.Boolean? = null,

    /* Allow update */
    @SerializedName("allowupdate")
    val allowupdate: kotlin.Boolean? = null,

    /* Completion on user submission */
    @SerializedName("completionsubmit")
    val completionsubmit: kotlin.Boolean? = null,

    /* Course id */
    @SerializedName("course")
    val course: kotlin.Int? = null,

    /* Course module id */
    @SerializedName("coursemodule")
    val coursemodule: kotlin.Int? = null,

    /* Display mode (vertical, horizontal) */
    @SerializedName("display")
    val display: kotlin.Int? = null,

    /* Group id */
    @SerializedName("groupingid")
    val groupingid: kotlin.Int? = null,

    /* Group mode */
    @SerializedName("groupmode")
    val groupmode: kotlin.Int? = null,

    /* Activity instance id */
    @SerializedName("id")
    val id: kotlin.Int? = null,

    /* Include inactive users */
    @SerializedName("includeinactive")
    val includeinactive: kotlin.Boolean? = null,

    /* Activity introduction */
    @SerializedName("intro")
    val intro: kotlin.String? = null,

    @SerializedName("introfiles")
    val introfiles: kotlin.collections.List<ElearningCoreBlockGetDashboardBlocks200ResponseBlocksInnerContentsFilesInner>? = null,

    /* intro format (1 = HTML, 0 = MOODLE, 2 = PLAIN, or 4 = MARKDOWN) */
    @SerializedName("introformat")
    val introformat: kotlin.Int? = null,

    /* Forced activity language */
    @SerializedName("lang")
    val lang: kotlin.String? = null,

    /* Limit unswers */
    @SerializedName("limitanswers")
    val limitanswers: kotlin.Boolean? = null,

    /* Activity name */
    @SerializedName("name")
    val name: kotlin.String? = null,

    /* If choice is published */
    @SerializedName("publish")
    val publish: kotlin.Boolean? = null,

    /* Course section id */
    @SerializedName("section")
    val section: kotlin.Int? = null,

    /* Show available spaces */
    @SerializedName("showavailable")
    val showavailable: kotlin.Boolean? = null,

    /* Show preview before timeopen */
    @SerializedName("showpreview")
    val showpreview: kotlin.Boolean? = null,

    /* 0 never, 1 after answer, 2 after close, 3 always */
    @SerializedName("showresults")
    val showresults: kotlin.Int? = null,

    /* Show users who not answered yet */
    @SerializedName("showunanswered")
    val showunanswered: kotlin.Boolean? = null,

    /* Date of closing validity */
    @SerializedName("timeclose")
    val timeclose: kotlin.Int? = null,

    /* Time of last modification */
    @SerializedName("timemodified")
    val timemodified: kotlin.Int? = null,

    /* Date of opening validity */
    @SerializedName("timeopen")
    val timeopen: kotlin.Int? = null,

    /* Visible */
    @SerializedName("visible")
    val visible: kotlin.Boolean? = null

) {


}

