/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningToolLpDataForTemplatesManagePage200ResponseTemplatesInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param canmanage Whether the user manage the templates
 * @param navigation 
 * @param pagecontextid The page context id
 * @param pluginbaseurl Url to the tool_lp plugin folder on this Moodle site
 * @param templates 
 */


data class ElearningToolLpDataForTemplatesManagePage200Response (

    /* Whether the user manage the templates */
    @SerializedName("canmanage")
    val canmanage: kotlin.Boolean,

    @SerializedName("navigation")
    val navigation: kotlin.collections.List<kotlin.Any>,

    /* The page context id */
    @SerializedName("pagecontextid")
    val pagecontextid: kotlin.Int,

    /* Url to the tool_lp plugin folder on this Moodle site */
    @SerializedName("pluginbaseurl")
    val pluginbaseurl: kotlin.String,

    @SerializedName("templates")
    val templates: kotlin.collections.List<ElearningToolLpDataForTemplatesManagePage200ResponseTemplatesInner>

) {


}

