/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningModForumAddDiscussionPost200ResponsePostTagsInnerUrls

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param displayname The display name of the tag
 * @param flag Wehther this tag is flagged
 * @param id The ID of the Tag
 * @param isstandard Whether this is a standard tag
 * @param tagid The tagid
 * @param urls 
 */


data class ElearningModForumAddDiscussionPost200ResponsePostTagsInner (

    /* The display name of the tag */
    @SerializedName("displayname")
    val displayname: kotlin.String? = null,

    /* Wehther this tag is flagged */
    @SerializedName("flag")
    val flag: kotlin.Boolean? = null,

    /* The ID of the Tag */
    @SerializedName("id")
    val id: kotlin.Int? = null,

    /* Whether this is a standard tag */
    @SerializedName("isstandard")
    val isstandard: kotlin.Boolean? = null,

    /* The tagid */
    @SerializedName("tagid")
    val tagid: kotlin.Int? = null,

    @SerializedName("urls")
    val urls: ElearningModForumAddDiscussionPost200ResponsePostTagsInnerUrls? = null

) {


}

