/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningAuthEmailSignupUser200ResponseWarningsInner
import org.openapitools.client.models.ElearningModImscpGetImscpsByCourses200ResponseImscpsInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param imscps 
 * @param warnings 
 */


data class ElearningModImscpGetImscpsByCourses200Response (

    @SerializedName("imscps")
    val imscps: kotlin.collections.List<ElearningModImscpGetImscpsByCourses200ResponseImscpsInner>,

    @SerializedName("warnings")
    val warnings: kotlin.collections.List<ElearningAuthEmailSignupUser200ResponseWarningsInner>? = null

) {


}

