/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningModGlossaryGetEntriesByAuthorRequestOptions

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id Glossary entry ID
 * @param from Start returning records from here
 * @param limit Number of records to return
 * @param options 
 * @param order Order the records by: 'CREATION' or 'UPDATE'.
 * @param sort The direction of the order: 'ASC' or 'DESC'
 */


data class ElearningModGlossaryGetEntriesByDateRequest (

    /* Glossary entry ID */
    @SerializedName("id")
    val id: kotlin.Int,

    /* Start returning records from here */
    @SerializedName("from")
    val from: kotlin.Int? = 0,

    /* Number of records to return */
    @SerializedName("limit")
    val limit: kotlin.Int? = 20,

    @SerializedName("options")
    val options: ElearningModGlossaryGetEntriesByAuthorRequestOptions? = null,

    /* Order the records by: 'CREATION' or 'UPDATE'. */
    @SerializedName("order")
    val order: kotlin.String? = "UPDATE",

    /* The direction of the order: 'ASC' or 'DESC' */
    @SerializedName("sort")
    val sort: kotlin.String? = "DESC"

) {


}

