/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param age Age
 * @param country Country of residence
 */


data class ElearningCoreAuthIsMinorRequest (

    /* Age */
    @SerializedName("age")
    val age: kotlin.Int,

    /* Country of residence */
    @SerializedName("country")
    val country: kotlin.String

) {


}

