/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param ext The file extension associated with the file type
 * @param key The file type identifier
 * @param name The file type name
 * @param selected Should it be marked as selected
 */


data class ElearningCoreFormGetFiletypesBrowserData200ResponseGroupsInnerTypesInner (

    /* The file extension associated with the file type */
    @SerializedName("ext")
    val ext: kotlin.String? = null,

    /* The file type identifier */
    @SerializedName("key")
    val key: kotlin.String? = null,

    /* The file type name */
    @SerializedName("name")
    val name: kotlin.String? = null,

    /* Should it be marked as selected */
    @SerializedName("selected")
    val selected: kotlin.Boolean? = null

) {


}

