/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningCoreWebserviceGetSiteInfo200ResponseAdvancedfeaturesInner
import org.openapitools.client.models.ElearningCoreWebserviceGetSiteInfo200ResponseFunctionsInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param firstname first name
 * @param fullname user full name
 * @param functions 
 * @param lang Current language.
 * @param lastname last name
 * @param sitename site name
 * @param siteurl site url
 * @param userid user id
 * @param username username
 * @param userpictureurl the user profile picture.                     Warning: this url is the public URL that only works when forcelogin is set to NO and guestaccess is set to YES.                     In order to retrieve user profile pictures independently of the Moodle config, replace \"pluginfile.php\" by                     \"webservice/pluginfile.php?token=WSTOKEN&file=\"                     Of course the user can only see profile picture depending                     on his/her permissions. Moreover it is recommended to use HTTPS too.
 * @param advancedfeatures 
 * @param downloadfiles 1 if users are allowed to download files, 0 if not
 * @param limitconcurrentlogins Number of concurrent sessions allowed
 * @param mobilecssurl Mobile custom CSS theme
 * @param release Moodle release number
 * @param sitecalendartype Calendar type set in the site.
 * @param siteid Site course ID
 * @param theme Current theme for the user.
 * @param uploadfiles 1 if users are allowed to upload files, 0 if not
 * @param usercalendartype Calendar typed used by the user.
 * @param usercanmanageownfiles true if the user can manage his own files
 * @param userhomepage the default home page for the user: 0 for the site home, 1 for dashboard
 * @param userissiteadmin Whether the user is a site admin or not.
 * @param usermaxuploadfilesize user max upload file size (bytes). -1 means the user can ignore the upload file size
 * @param userprivateaccesskey Private user access key for fetching files.
 * @param userquota user quota (bytes). 0 means user can ignore the quota
 * @param usersessionscount Number of active sessions for current user.                     Only returned when limitconcurrentlogins is used.
 * @param version Moodle version number
 */


data class ElearningCoreWebserviceGetSiteInfo200Response (

    /* first name */
    @SerializedName("firstname")
    val firstname: kotlin.String,

    /* user full name */
    @SerializedName("fullname")
    val fullname: kotlin.String,

    @SerializedName("functions")
    val functions: kotlin.collections.List<ElearningCoreWebserviceGetSiteInfo200ResponseFunctionsInner>,

    /* Current language. */
    @SerializedName("lang")
    val lang: kotlin.String,

    /* last name */
    @SerializedName("lastname")
    val lastname: kotlin.String,

    /* site name */
    @SerializedName("sitename")
    val sitename: kotlin.String,

    /* site url */
    @SerializedName("siteurl")
    val siteurl: kotlin.String,

    /* user id */
    @SerializedName("userid")
    val userid: kotlin.Int,

    /* username */
    @SerializedName("username")
    val username: kotlin.String,

    /* the user profile picture.                     Warning: this url is the public URL that only works when forcelogin is set to NO and guestaccess is set to YES.                     In order to retrieve user profile pictures independently of the Moodle config, replace \"pluginfile.php\" by                     \"webservice/pluginfile.php?token=WSTOKEN&file=\"                     Of course the user can only see profile picture depending                     on his/her permissions. Moreover it is recommended to use HTTPS too. */
    @SerializedName("userpictureurl")
    val userpictureurl: kotlin.String,

    @SerializedName("advancedfeatures")
    val advancedfeatures: kotlin.collections.List<ElearningCoreWebserviceGetSiteInfo200ResponseAdvancedfeaturesInner>? = null,

    /* 1 if users are allowed to download files, 0 if not */
    @SerializedName("downloadfiles")
    val downloadfiles: kotlin.Int? = null,

    /* Number of concurrent sessions allowed */
    @SerializedName("limitconcurrentlogins")
    val limitconcurrentlogins: kotlin.Int? = null,

    /* Mobile custom CSS theme */
    @SerializedName("mobilecssurl")
    val mobilecssurl: kotlin.String? = null,

    /* Moodle release number */
    @SerializedName("release")
    val release: kotlin.String? = null,

    /* Calendar type set in the site. */
    @SerializedName("sitecalendartype")
    val sitecalendartype: kotlin.String? = null,

    /* Site course ID */
    @SerializedName("siteid")
    val siteid: kotlin.Int? = null,

    /* Current theme for the user. */
    @SerializedName("theme")
    val theme: kotlin.String? = null,

    /* 1 if users are allowed to upload files, 0 if not */
    @SerializedName("uploadfiles")
    val uploadfiles: kotlin.Int? = null,

    /* Calendar typed used by the user. */
    @SerializedName("usercalendartype")
    val usercalendartype: kotlin.String? = null,

    /* true if the user can manage his own files */
    @SerializedName("usercanmanageownfiles")
    val usercanmanageownfiles: kotlin.Boolean? = null,

    /* the default home page for the user: 0 for the site home, 1 for dashboard */
    @SerializedName("userhomepage")
    val userhomepage: kotlin.Int? = null,

    /* Whether the user is a site admin or not. */
    @SerializedName("userissiteadmin")
    val userissiteadmin: kotlin.Boolean? = null,

    /* user max upload file size (bytes). -1 means the user can ignore the upload file size */
    @SerializedName("usermaxuploadfilesize")
    val usermaxuploadfilesize: kotlin.Int? = null,

    /* Private user access key for fetching files. */
    @SerializedName("userprivateaccesskey")
    val userprivateaccesskey: kotlin.String? = null,

    /* user quota (bytes). 0 means user can ignore the quota */
    @SerializedName("userquota")
    val userquota: kotlin.Int? = null,

    /* Number of active sessions for current user.                     Only returned when limitconcurrentlogins is used. */
    @SerializedName("usersessionscount")
    val usersessionscount: kotlin.Int? = null,

    /* Moodle version number */
    @SerializedName("version")
    val version: kotlin.String? = null

) {


}

