/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param contextid The editing context id
 * @param formdata The data from the tag form
 * @param questionid The question id
 */


data class ElearningCoreQuestionSubmitTagsFormRequest (

    /* The editing context id */
    @SerializedName("contextid")
    val contextid: kotlin.Int,

    /* The data from the tag form */
    @SerializedName("formdata")
    val formdata: kotlin.String,

    /* The question id */
    @SerializedName("questionid")
    val questionid: kotlin.Int

) {


}

