/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param messageid id of the message in the messages table
 * @param timeread timestamp for when the message should be marked read
 */


data class ElearningCoreMessageMarkMessageReadRequest (

    /* id of the message in the messages table */
    @SerializedName("messageid")
    val messageid: kotlin.Int,

    /* timestamp for when the message should be marked read */
    @SerializedName("timeread")
    val timeread: kotlin.Int? = 0

) {


}

