/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param area string comment area
 * @param component component
 * @param content component
 * @param contextlevel contextlevel system, course, user...
 * @param instanceid the id of item associated with the contextlevel
 * @param itemid associated id
 */


data class ElearningCoreCommentAddCommentsRequestCommentsInner (

    /* string comment area */
    @SerializedName("area")
    val area: kotlin.String? = "",

    /* component */
    @SerializedName("component")
    val component: kotlin.String? = null,

    /* component */
    @SerializedName("content")
    val content: kotlin.String? = null,

    /* contextlevel system, course, user... */
    @SerializedName("contextlevel")
    val contextlevel: kotlin.String? = null,

    /* the id of item associated with the contextlevel */
    @SerializedName("instanceid")
    val instanceid: kotlin.Int? = null,

    /* associated id */
    @SerializedName("itemid")
    val itemid: kotlin.Int? = null

) {


}

