/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningAuthEmailSignupUser200ResponseWarningsInner
import org.openapitools.client.models.ElearningModWikiGetWikisByCourses200ResponseWikisInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param wikis 
 * @param warnings 
 */


data class ElearningModWikiGetWikisByCourses200Response (

    @SerializedName("wikis")
    val wikis: kotlin.collections.List<ElearningModWikiGetWikisByCourses200ResponseWikisInner>,

    @SerializedName("warnings")
    val warnings: kotlin.collections.List<ElearningAuthEmailSignupUser200ResponseWarningsInner>? = null

) {


}

