/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param contextid Context id
 * @param displayname Display name
 * @param hassettings Whether has settings
 * @param name Processor name
 * @param userconfigured Whether is configured by the user
 */


data class ElearningCoreMessageGetUserMessagePreferences200ResponsePreferencesProcessorsInner (

    /* Context id */
    @SerializedName("contextid")
    val contextid: kotlin.Int? = null,

    /* Display name */
    @SerializedName("displayname")
    val displayname: kotlin.String? = null,

    /* Whether has settings */
    @SerializedName("hassettings")
    val hassettings: kotlin.Boolean? = null,

    /* Processor name */
    @SerializedName("name")
    val name: kotlin.String? = null,

    /* Whether is configured by the user */
    @SerializedName("userconfigured")
    val userconfigured: kotlin.Int? = null

) {


}

