/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param companyid Course company ID
 * @param courseid Course ID
 */


data class ElearningBlockIomadCompanyAdminUnassignCoursesRequestCoursesInner (

    /* Course company ID */
    @SerializedName("companyid")
    val companyid: kotlin.Int? = 0,

    /* Course ID */
    @SerializedName("courseid")
    val courseid: kotlin.Int? = 0

) {


}

