/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param profile The URL for the use profile page
 * @param profileimage The URL for the use profile image
 */


data class ElearningModForumAddDiscussionPost200ResponsePostAuthorUrls (

    /* The URL for the use profile page */
    @SerializedName("profile")
    val profile: kotlin.String? = null,

    /* The URL for the use profile image */
    @SerializedName("profileimage")
    val profileimage: kotlin.String? = null

) {


}

