/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningModGlossaryGetEntriesByAuthorRequestOptions

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id Glossary entry ID
 * @param letter First letter of firstname or lastname, or either keywords: 'ALL' or 'SPECIAL'.
 * @param `field` Search and order using: 'FIRSTNAME' or 'LASTNAME'
 * @param from Start returning records from here
 * @param limit Number of records to return
 * @param options 
 * @param sort The direction of the order: 'ASC' or 'DESC'
 */


data class ElearningModGlossaryGetEntriesByAuthorRequest (

    /* Glossary entry ID */
    @SerializedName("id")
    val id: kotlin.Int,

    /* First letter of firstname or lastname, or either keywords: 'ALL' or 'SPECIAL'. */
    @SerializedName("letter")
    val letter: kotlin.String,

    /* Search and order using: 'FIRSTNAME' or 'LASTNAME' */
    @SerializedName("field")
    val `field`: kotlin.String? = "LASTNAME",

    /* Start returning records from here */
    @SerializedName("from")
    val from: kotlin.Int? = 0,

    /* Number of records to return */
    @SerializedName("limit")
    val limit: kotlin.Int? = 20,

    @SerializedName("options")
    val options: ElearningModGlossaryGetEntriesByAuthorRequestOptions? = null,

    /* The direction of the order: 'ASC' or 'DESC' */
    @SerializedName("sort")
    val sort: kotlin.String? = "ASC"

) {


}

