/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param course The course we are adding to
 * @param profileurl The profile url that the user has given us
 * @param section The section within the course we are adding to
 */


data class ElearningToolMoodlenetVerifyWebfingerRequest (

    /* The course we are adding to */
    @SerializedName("course")
    val course: kotlin.Int,

    /* The profile url that the user has given us */
    @SerializedName("profileurl")
    val profileurl: kotlin.String,

    /* The section within the course we are adding to */
    @SerializedName("section")
    val section: kotlin.Int

) {


}

