/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param component component
 * @param key key
 * @param title title
 */


data class ElearningCoreReportbuilderColumnsDelete200ResponseSortablecolumnsInnerSorticon (

    /* component */
    @SerializedName("component")
    val component: kotlin.String,

    /* key */
    @SerializedName("key")
    val key: kotlin.String,

    /* title */
    @SerializedName("title")
    val title: kotlin.String

) {


}

