/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param code Task code.
 * @param completed Completion information (maybe empty, maybe a boolean or generic info.
 * @param details Task details.
 * @param link Link to task.
 * @param title Task title.
 */


data class ElearningModWorkshopGetUserPlan200ResponseUserplanPhasesInnerTasksInner (

    /* Task code. */
    @SerializedName("code")
    val code: kotlin.String? = null,

    /* Completion information (maybe empty, maybe a boolean or generic info. */
    @SerializedName("completed")
    val completed: kotlin.String? = null,

    /* Task details. */
    @SerializedName("details")
    val details: kotlin.String? = null,

    /* Link to task. */
    @SerializedName("link")
    val link: kotlin.String? = null,

    /* Task title. */
    @SerializedName("title")
    val title: kotlin.String? = null

) {


}

