/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param criterionid criterion id
 * @param levelid level id
 * @param remark remark
 * @param remarkformat remark format (1 = HTML, 0 = MOODLE, 2 = PLAIN, or 4 = MARKDOWN)
 */


data class ElearningModAssignSaveGradeRequestAdvancedgradingdataRubricCriteriaInnerFillingsInner (

    /* criterion id */
    @SerializedName("criterionid")
    val criterionid: kotlin.Int? = null,

    /* level id */
    @SerializedName("levelid")
    val levelid: kotlin.Int? = null,

    /* remark */
    @SerializedName("remark")
    val remark: kotlin.String? = null,

    /* remark format (1 = HTML, 0 = MOODLE, 2 = PLAIN, or 4 = MARKDOWN) */
    @SerializedName("remarkformat")
    val remarkformat: kotlin.Int? = null

) {


}

