/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param key The data that failed the validation
 * @param message The error message
 */


data class ElearningCoreEnrolUnenrolUserEnrolment200ResponseErrorsInner (

    /* The data that failed the validation */
    @SerializedName("key")
    val key: kotlin.String? = null,

    /* The error message */
    @SerializedName("message")
    val message: kotlin.String? = null

) {


}

