/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param badgeid Badge id
 * @param id Alignment id
 * @param targetCode Target code
 * @param targetDescription Target description
 * @param targetFramework Target framework
 * @param targetName Target name
 * @param targetUrl Target URL
 */


data class ElearningCoreBadgesGetUserBadgeByHash200ResponseBadgeInnerAlignmentInner (

    /* Badge id */
    @SerializedName("badgeid")
    val badgeid: kotlin.Int? = null,

    /* Alignment id */
    @SerializedName("id")
    val id: kotlin.Int? = null,

    /* Target code */
    @SerializedName("targetCode")
    val targetCode: kotlin.String? = null,

    /* Target description */
    @SerializedName("targetDescription")
    val targetDescription: kotlin.String? = null,

    /* Target framework */
    @SerializedName("targetFramework")
    val targetFramework: kotlin.String? = null,

    /* Target name */
    @SerializedName("targetName")
    val targetName: kotlin.String? = null,

    /* Target URL */
    @SerializedName("targetUrl")
    val targetUrl: kotlin.String? = null

) {


}

