/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id Data base record id for the framework
 */


data class ElearningCoreCompetencyDuplicateCompetencyFrameworkRequest (

    /* Data base record id for the framework */
    @SerializedName("id")
    val id: kotlin.Int

) {


}

