/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param courseid Course ID
 * @param showinactivitychooser Show in activity chooser
 * @param tooltypeid Tool type ID
 */


data class ElearningModLtiToggleShowinactivitychooserRequest (

    /* Course ID */
    @SerializedName("courseid")
    val courseid: kotlin.Int,

    /* Show in activity chooser */
    @SerializedName("showinactivitychooser")
    val showinactivitychooser: kotlin.Boolean,

    /* Tool type ID */
    @SerializedName("tooltypeid")
    val tooltypeid: kotlin.Int

) {


}

