/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param component component containing the template
 * @param template name of the template
 */


data class ElearningToolTemplatelibraryLoadCanonicalTemplateRequest (

    /* component containing the template */
    @SerializedName("component")
    val component: kotlin.String,

    /* name of the template */
    @SerializedName("template")
    val template: kotlin.String

) {


}

