/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param areaids 
 * @param cat category to filter areas
 * @param contextids 
 * @param courseids 
 * @param groupids 
 * @param mycoursesonly only results from my courses
 * @param order how to order
 * @param timeend docs modified before this date
 * @param timestart docs modified after this date
 * @param title result title
 * @param userids 
 */


data class ElearningCoreSearchGetTopResultsRequestFilters (

    @SerializedName("areaids")
    val areaids: kotlin.collections.List<kotlin.Any>? = null,

    /* category to filter areas */
    @SerializedName("cat")
    val cat: kotlin.String? = "",

    @SerializedName("contextids")
    val contextids: kotlin.collections.List<kotlin.Any>? = null,

    @SerializedName("courseids")
    val courseids: kotlin.collections.List<kotlin.Any>? = null,

    @SerializedName("groupids")
    val groupids: kotlin.collections.List<kotlin.Any>? = null,

    /* only results from my courses */
    @SerializedName("mycoursesonly")
    val mycoursesonly: kotlin.Boolean? = false,

    /* how to order */
    @SerializedName("order")
    val order: kotlin.String? = "",

    /* docs modified before this date */
    @SerializedName("timeend")
    val timeend: kotlin.Int? = 0,

    /* docs modified after this date */
    @SerializedName("timestart")
    val timestart: kotlin.Int? = 0,

    /* result title */
    @SerializedName("title")
    val title: kotlin.String? = null,

    @SerializedName("userids")
    val userids: kotlin.collections.List<kotlin.Any>? = null

) {


}

