/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningToolPolicyGetPolicyVersion200ResponseResultPolicy

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param policy 
 */


data class ElearningToolPolicyGetPolicyVersion200ResponseResult (

    @SerializedName("policy")
    val policy: ElearningToolPolicyGetPolicyVersion200ResponseResultPolicy? = null

) {


}

