/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param element element name
 * @param `value` element value
 */


data class ElearningModScormGetScormScoes200ResponseScoesInnerExtradataInner (

    /* element name */
    @SerializedName("element")
    val element: kotlin.String? = null,

    /* element value */
    @SerializedName("value")
    val `value`: kotlin.String? = null

) {


}

