/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param password Plain text password.
 * @param username Username.
 * @param redirect Redirect the user to this site url after confirmation.
 */


data class ElearningCoreAuthResendConfirmationEmailRequest (

    /* Plain text password. */
    @SerializedName("password")
    val password: kotlin.String,

    /* Username. */
    @SerializedName("username")
    val username: kotlin.String,

    /* Redirect the user to this site url after confirmation. */
    @SerializedName("redirect")
    val redirect: kotlin.String? = ""

) {


}

