/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param blockeduserid The id of the user being blocked
 * @param userid The id of the user who is blocking
 */


data class ElearningCoreMessageBlockUserRequest (

    /* The id of the user being blocked */
    @SerializedName("blockeduserid")
    val blockeduserid: kotlin.Int,

    /* The id of the user who is blocking */
    @SerializedName("userid")
    val userid: kotlin.Int

) {


}

