/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * information about conversation
 *
 * @param id Conversations id
 * @param name Multilang compatible conversation name2
 * @param timecreated The timecreated timestamp for the conversation
 * @param type Conversation type: private or public
 */


data class ElearningCoreMessageGetConversation200ResponseMembersInnerConversationsInner (

    /* Conversations id */
    @SerializedName("id")
    val id: kotlin.Int? = null,

    /* Multilang compatible conversation name2 */
    @SerializedName("name")
    val name: kotlin.String? = null,

    /* The timecreated timestamp for the conversation */
    @SerializedName("timecreated")
    val timecreated: kotlin.Int? = null,

    /* Conversation type: private or public */
    @SerializedName("type")
    val type: kotlin.Int? = null

) {


}

