/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningModAssignGetUserFlags200ResponseAssignmentsInnerUserflagsInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param assignmentid assignment id
 * @param userflags 
 */


data class ElearningModAssignGetUserFlags200ResponseAssignmentsInner (

    /* assignment id */
    @SerializedName("assignmentid")
    val assignmentid: kotlin.Int? = null,

    @SerializedName("userflags")
    val userflags: kotlin.collections.List<ElearningModAssignGetUserFlags200ResponseAssignmentsInnerUserflagsInner>? = null

) {


}

