/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param name Name of the extrafield.
 * @param `value` Value of the extrafield.
 */


data class ElearningCoreUserSearchIdentity200ResponseListInnerExtrafieldsInner (

    /* Name of the extrafield. */
    @SerializedName("name")
    val name: kotlin.String? = null,

    /* Value of the extrafield. */
    @SerializedName("value")
    val `value`: kotlin.String? = null

) {


}

