/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param courseid id of the course, 0 for site
 */


data class ElearningCoreUserViewUserListRequest (

    /* id of the course, 0 for site */
    @SerializedName("courseid")
    val courseid: kotlin.Int

) {


}

