/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningAuthEmailSignupUser200ResponseWarningsInner
import org.openapitools.client.models.ElearningCoreGroupGetCourseUserGroups200ResponseGroupsInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param groups 
 * @param warnings 
 */


data class ElearningCoreGroupGetCourseUserGroups200Response (

    @SerializedName("groups")
    val groups: kotlin.collections.List<ElearningCoreGroupGetCourseUserGroups200ResponseGroupsInner>,

    @SerializedName("warnings")
    val warnings: kotlin.collections.List<ElearningAuthEmailSignupUser200ResponseWarningsInner>? = null

) {


}

