/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * User responses
 *
 * @param answerid answer id
 * @param fullname user full name
 * @param profileimageurl profile user image url
 * @param timemodified time of modification
 * @param userid user id
 */


data class ElearningModChoiceGetChoiceResults200ResponseOptionsInnerUserresponsesInner (

    /* answer id */
    @SerializedName("answerid")
    val answerid: kotlin.Int? = null,

    /* user full name */
    @SerializedName("fullname")
    val fullname: kotlin.String? = null,

    /* profile user image url */
    @SerializedName("profileimageurl")
    val profileimageurl: kotlin.String? = null,

    /* time of modification */
    @SerializedName("timemodified")
    val timemodified: kotlin.Int? = null,

    /* user id */
    @SerializedName("userid")
    val userid: kotlin.Int? = null

) {


}

