/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param name The response name (usually type[index]_id).
 * @param `value` The response value.
 */


data class ElearningModFeedbackProcessPageRequestResponsesInner (

    /* The response name (usually type[index]_id). */
    @SerializedName("name")
    val name: kotlin.String? = null,

    /* The response value. */
    @SerializedName("value")
    val `value`: kotlin.String? = null

) {


}

