/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param dataid Id of the data activity
 * @param presetnames 
 */


data class ElearningModDataDeleteSavedPresetRequest (

    /* Id of the data activity */
    @SerializedName("dataid")
    val dataid: kotlin.Int,

    @SerializedName("presetnames")
    val presetnames: kotlin.collections.List<kotlin.Any>

) {


}

