/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningCoreCohortSearchCohortsRequestContext
import org.openapitools.client.models.ElearningCoreReportbuilderCanViewSystemReportRequestParametersInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param context 
 * @param source Report class path
 * @param area Report area
 * @param component Report component
 * @param itemid Report item ID
 * @param page Page number
 * @param parameters 
 * @param perpage Reports per page
 */


data class ElearningCoreReportbuilderRetrieveSystemReportRequest (

    @SerializedName("context")
    val context: ElearningCoreCohortSearchCohortsRequestContext,

    /* Report class path */
    @SerializedName("source")
    val source: kotlin.String,

    /* Report area */
    @SerializedName("area")
    val area: kotlin.String? = "",

    /* Report component */
    @SerializedName("component")
    val component: kotlin.String? = "",

    /* Report item ID */
    @SerializedName("itemid")
    val itemid: kotlin.Int? = 0,

    /* Page number */
    @SerializedName("page")
    val page: kotlin.Int? = 0,

    @SerializedName("parameters")
    val parameters: kotlin.collections.List<ElearningCoreReportbuilderCanViewSystemReportRequestParametersInner>? = null,

    /* Reports per page */
    @SerializedName("perpage")
    val perpage: kotlin.Int? = 10

) {


}

