/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningAuthEmailSignupUser200ResponseWarningsInner
import org.openapitools.client.models.ElearningModQuizGetAttemptReview200ResponseAdditionaldataInner
import org.openapitools.client.models.ElearningModQuizGetAttemptReview200ResponseAttempt
import org.openapitools.client.models.ElearningModQuizGetAttemptReview200ResponseQuestionsInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param additionaldata 
 * @param attempt 
 * @param grade grade for the quiz (or empty or \"notyetgraded\")
 * @param questions 
 * @param warnings 
 */


data class ElearningModQuizGetAttemptReview200Response (

    @SerializedName("additionaldata")
    val additionaldata: kotlin.collections.List<ElearningModQuizGetAttemptReview200ResponseAdditionaldataInner>,

    @SerializedName("attempt")
    val attempt: ElearningModQuizGetAttemptReview200ResponseAttempt,

    /* grade for the quiz (or empty or \"notyetgraded\") */
    @SerializedName("grade")
    val grade: kotlin.String,

    @SerializedName("questions")
    val questions: kotlin.collections.List<ElearningModQuizGetAttemptReview200ResponseQuestionsInner>,

    @SerializedName("warnings")
    val warnings: kotlin.collections.List<ElearningAuthEmailSignupUser200ResponseWarningsInner>? = null

) {


}

