/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningAuthEmailSignupUser200ResponseWarningsInner
import org.openapitools.client.models.ElearningModLtiGetLtisByCourses200ResponseLtisInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param ltis 
 * @param warnings 
 */


data class ElearningModLtiGetLtisByCourses200Response (

    @SerializedName("ltis")
    val ltis: kotlin.collections.List<ElearningModLtiGetLtisByCourses200ResponseLtisInner>,

    @SerializedName("warnings")
    val warnings: kotlin.collections.List<ElearningAuthEmailSignupUser200ResponseWarningsInner>? = null

) {


}

