/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningCoreUserCreateUsersRequestUsersInnerCustomfieldsInner
import org.openapitools.client.models.ElearningCoreUserUpdateUsersRequestUsersInnerPreferencesInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param address Postal address
 * @param alternatename The alternate name of the user
 * @param auth Auth plugins include manual, ldap, etc
 * @param calendartype Calendar type such as \"gregorian\", must exist on server
 * @param city Home city of the user
 * @param country Home country code of the user, such as AU or CZ
 * @param customfields 
 * @param department Department
 * @param description User profile description, no HTML
 * @param email A valid and unique email address
 * @param firstname The first name(s) of the user
 * @param firstnamephonetic The first name(s) phonetically of the user
 * @param id ID of the user
 * @param idnumber An arbitrary ID code number perhaps from the institution
 * @param institution Institution
 * @param interests User interests (separated by commas)
 * @param lang Language code such as \"en\", must exist on server
 * @param lastname The family name of the user
 * @param lastnamephonetic The family name phonetically of the user
 * @param maildisplay Email visibility
 * @param mailformat Mail format code is 0 for plain text, 1 for HTML etc
 * @param middlename The middle name of the user
 * @param password Plain text password consisting of any characters
 * @param phone1 Phone
 * @param phone2 Mobile phone
 * @param preferences 
 * @param suspended Suspend user account, either false to enable user login or true to disable it
 * @param theme Theme name such as \"standard\", must exist on server
 * @param timezone Timezone code such as Australia/Perth, or 99 for default
 * @param username Username policy is defined in Moodle security config.
 * @param userpicture The itemid where the new user picture has been uploaded to, 0 to delete
 */


data class ElearningCoreUserUpdateUsersRequestUsersInner (

    /* Postal address */
    @SerializedName("address")
    val address: kotlin.String? = null,

    /* The alternate name of the user */
    @SerializedName("alternatename")
    val alternatename: kotlin.String? = null,

    /* Auth plugins include manual, ldap, etc */
    @SerializedName("auth")
    val auth: kotlin.String? = "",

    /* Calendar type such as \"gregorian\", must exist on server */
    @SerializedName("calendartype")
    val calendartype: kotlin.String? = "",

    /* Home city of the user */
    @SerializedName("city")
    val city: kotlin.String? = null,

    /* Home country code of the user, such as AU or CZ */
    @SerializedName("country")
    val country: kotlin.String? = null,

    @SerializedName("customfields")
    val customfields: kotlin.collections.List<ElearningCoreUserCreateUsersRequestUsersInnerCustomfieldsInner>? = null,

    /* Department */
    @SerializedName("department")
    val department: kotlin.String? = null,

    /* User profile description, no HTML */
    @SerializedName("description")
    val description: kotlin.String? = null,

    /* A valid and unique email address */
    @SerializedName("email")
    val email: kotlin.String? = "",

    /* The first name(s) of the user */
    @SerializedName("firstname")
    val firstname: kotlin.String? = "",

    /* The first name(s) phonetically of the user */
    @SerializedName("firstnamephonetic")
    val firstnamephonetic: kotlin.String? = null,

    /* ID of the user */
    @SerializedName("id")
    val id: kotlin.Int? = null,

    /* An arbitrary ID code number perhaps from the institution */
    @SerializedName("idnumber")
    val idnumber: kotlin.String? = null,

    /* Institution */
    @SerializedName("institution")
    val institution: kotlin.String? = null,

    /* User interests (separated by commas) */
    @SerializedName("interests")
    val interests: kotlin.String? = null,

    /* Language code such as \"en\", must exist on server */
    @SerializedName("lang")
    val lang: kotlin.String? = "",

    /* The family name of the user */
    @SerializedName("lastname")
    val lastname: kotlin.String? = null,

    /* The family name phonetically of the user */
    @SerializedName("lastnamephonetic")
    val lastnamephonetic: kotlin.String? = null,

    /* Email visibility */
    @SerializedName("maildisplay")
    val maildisplay: kotlin.Int? = null,

    /* Mail format code is 0 for plain text, 1 for HTML etc */
    @SerializedName("mailformat")
    val mailformat: kotlin.Int? = null,

    /* The middle name of the user */
    @SerializedName("middlename")
    val middlename: kotlin.String? = null,

    /* Plain text password consisting of any characters */
    @SerializedName("password")
    val password: kotlin.String? = "",

    /* Phone */
    @SerializedName("phone1")
    val phone1: kotlin.String? = null,

    /* Mobile phone */
    @SerializedName("phone2")
    val phone2: kotlin.String? = null,

    @SerializedName("preferences")
    val preferences: kotlin.collections.List<ElearningCoreUserUpdateUsersRequestUsersInnerPreferencesInner>? = null,

    /* Suspend user account, either false to enable user login or true to disable it */
    @SerializedName("suspended")
    val suspended: kotlin.Boolean? = null,

    /* Theme name such as \"standard\", must exist on server */
    @SerializedName("theme")
    val theme: kotlin.String? = null,

    /* Timezone code such as Australia/Perth, or 99 for default */
    @SerializedName("timezone")
    val timezone: kotlin.String? = null,

    /* Username policy is defined in Moodle security config. */
    @SerializedName("username")
    val username: kotlin.String? = "",

    /* The itemid where the new user picture has been uploaded to, 0 to delete */
    @SerializedName("userpicture")
    val userpicture: kotlin.Int? = null

) {


}

