/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param competencyid competencyid
 * @param courseid courseid
 * @param id id
 * @param ruleoutcome ruleoutcome
 * @param sortorder sortorder
 * @param timecreated timecreated
 * @param timemodified timemodified
 * @param usermodified usermodified
 */


data class ElearningToolLpDataForCourseCompetenciesPage200ResponseCompetenciesInnerCoursecompetency (

    /* competencyid */
    @SerializedName("competencyid")
    val competencyid: kotlin.Int,

    /* courseid */
    @SerializedName("courseid")
    val courseid: kotlin.Int,

    /* id */
    @SerializedName("id")
    val id: kotlin.Int = 0,

    /* ruleoutcome */
    @SerializedName("ruleoutcome")
    val ruleoutcome: kotlin.Int = 1,

    /* sortorder */
    @SerializedName("sortorder")
    val sortorder: kotlin.Int,

    /* timecreated */
    @SerializedName("timecreated")
    val timecreated: kotlin.Int = 0,

    /* timemodified */
    @SerializedName("timemodified")
    val timemodified: kotlin.Int = 0,

    /* usermodified */
    @SerializedName("usermodified")
    val usermodified: kotlin.Int = 0

) {


}

