/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningAuthEmailSignupUser200ResponseWarningsInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param status True if the submission was created false otherwise.
 * @param submissionid New workshop submission id.
 * @param warnings 
 */


data class ElearningModWorkshopAddSubmission200Response (

    /* True if the submission was created false otherwise. */
    @SerializedName("status")
    val status: kotlin.Boolean,

    /* New workshop submission id. */
    @SerializedName("submissionid")
    val submissionid: kotlin.Int? = null,

    @SerializedName("warnings")
    val warnings: kotlin.collections.List<ElearningAuthEmailSignupUser200ResponseWarningsInner>? = null

) {


}

