/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningCoreCohortAddCohortMembersRequestMembersInnerCohorttype
import org.openapitools.client.models.ElearningCoreCohortAddCohortMembersRequestMembersInnerUsertype

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param cohorttype 
 * @param usertype 
 */


data class ElearningCoreCohortAddCohortMembersRequestMembersInner (

    @SerializedName("cohorttype")
    val cohorttype: ElearningCoreCohortAddCohortMembersRequestMembersInnerCohorttype? = null,

    @SerializedName("usertype")
    val usertype: ElearningCoreCohortAddCohortMembersRequestMembersInnerUsertype? = null

) {


}

