/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param end Attempt time ended.
 * @param grade Attempt grade.
 * @param timeend Attempt last time continued.
 * @param timestart Attempt time started.
 * @param `try` Attempt number.
 */


data class ElearningModLessonGetAttemptsOverview200ResponseDataStudentsInnerAttemptsInner (

    /* Attempt time ended. */
    @SerializedName("end")
    val end: kotlin.Int? = null,

    /* Attempt grade. */
    @SerializedName("grade")
    val grade: java.math.BigDecimal? = null,

    /* Attempt last time continued. */
    @SerializedName("timeend")
    val timeend: kotlin.Int? = null,

    /* Attempt time started. */
    @SerializedName("timestart")
    val timestart: kotlin.Int? = null,

    /* Attempt number. */
    @SerializedName("try")
    val `try`: kotlin.Int? = null

) {


}

