/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param fixday Remove leading zero for day
 * @param fixhour Remove leading zero for hour
 * @param format format string
 * @param timestamp unix timestamp
 * @param type The calendar type
 */


data class ElearningCoreGetUserDatesRequestTimestampsInner (

    /* Remove leading zero for day */
    @SerializedName("fixday")
    val fixday: kotlin.Int? = 1,

    /* Remove leading zero for hour */
    @SerializedName("fixhour")
    val fixhour: kotlin.Int? = 1,

    /* format string */
    @SerializedName("format")
    val format: kotlin.String? = null,

    /* unix timestamp */
    @SerializedName("timestamp")
    val timestamp: kotlin.Int? = null,

    /* The calendar type */
    @SerializedName("type")
    val type: kotlin.String? = null

) {


}

