/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param ta tag area id
 * @param tag tag name
 * @param tc tag collection id
 * @param ctx context id where to search for items
 * @param excl exlusive mode for this tag area
 * @param from context id where the link was displayed
 * @param page page number (0-based)
 * @param rec search in the context recursive
 */


data class ElearningCoreTagGetTagindexRequestTagindex (

    /* tag area id */
    @SerializedName("ta")
    val ta: kotlin.Int,

    /* tag name */
    @SerializedName("tag")
    val tag: kotlin.String,

    /* tag collection id */
    @SerializedName("tc")
    val tc: kotlin.Int,

    /* context id where to search for items */
    @SerializedName("ctx")
    val ctx: kotlin.Int? = 0,

    /* exlusive mode for this tag area */
    @SerializedName("excl")
    val excl: kotlin.Boolean? = 0,

    /* context id where the link was displayed */
    @SerializedName("from")
    val from: kotlin.Int? = 0,

    /* page number (0-based) */
    @SerializedName("page")
    val page: kotlin.Int? = 0,

    /* search in the context recursive */
    @SerializedName("rec")
    val rec: kotlin.Int? = 1

) {


}

