/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningModH5pactivityGetAttempts200ResponseUsersattemptsInnerAttemptsInner
import org.openapitools.client.models.ElearningModH5pactivityGetAttempts200ResponseUsersattemptsInnerScored

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param attempts 
 * @param scored 
 * @param userid The user id
 */


data class ElearningModH5pactivityGetAttempts200ResponseUsersattemptsInner (

    @SerializedName("attempts")
    val attempts: kotlin.collections.List<ElearningModH5pactivityGetAttempts200ResponseUsersattemptsInnerAttemptsInner>? = null,

    @SerializedName("scored")
    val scored: ElearningModH5pactivityGetAttempts200ResponseUsersattemptsInnerScored? = null,

    /* The user id */
    @SerializedName("userid")
    val userid: kotlin.Int? = null

) {


}

