/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param assignmentid The assignment id to operate on
 * @param dates 
 * @param userids 
 */


data class ElearningModAssignSaveUserExtensionsRequest (

    /* The assignment id to operate on */
    @SerializedName("assignmentid")
    val assignmentid: kotlin.Int,

    @SerializedName("dates")
    val dates: kotlin.collections.List<kotlin.Any>,

    @SerializedName("userids")
    val userids: kotlin.collections.List<kotlin.Any>

) {


}

