/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningAuthEmailSignupUser200ResponseWarningsInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param autologinurl Auto-login URL.
 * @param key Auto-login key for a single usage with time expiration.
 * @param warnings 
 */


data class ElearningToolMobileGetAutologinKey200Response (

    /* Auto-login URL. */
    @SerializedName("autologinurl")
    val autologinurl: kotlin.String,

    /* Auto-login key for a single usage with time expiration. */
    @SerializedName("key")
    val key: kotlin.String,

    @SerializedName("warnings")
    val warnings: kotlin.collections.List<ElearningAuthEmailSignupUser200ResponseWarningsInner>? = null

) {


}

