/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningCoreSearchGetTopResults200ResponseResultsInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param results 
 */


data class ElearningCoreSearchGetTopResults200Response (

    @SerializedName("results")
    val results: kotlin.collections.List<ElearningCoreSearchGetTopResults200ResponseResultsInner>

) {


}

