/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningCoreCompetencyGradeCompetency200ResponseActionuser

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param area area
 * @param component component
 * @param conditiondata conditiondata
 * @param contextid contextid
 * @param id id
 * @param itemid itemid
 * @param modifiedby 
 * @param name name
 * @param settingsdata settingsdata
 * @param source source
 * @param sourcename sourcename
 * @param timecreated timecreated
 * @param timemodified timemodified
 * @param type type
 * @param uniquerows uniquerows
 * @param usercreated usercreated
 * @param usermodified usermodified
 */


data class ElearningCoreReportbuilderListReports200ResponseReportsInner (

    /* area */
    @SerializedName("area")
    val area: kotlin.String? = "",

    /* component */
    @SerializedName("component")
    val component: kotlin.String? = "",

    /* conditiondata */
    @SerializedName("conditiondata")
    val conditiondata: kotlin.String? = null,

    /* contextid */
    @SerializedName("contextid")
    val contextid: kotlin.Int? = {},

    /* id */
    @SerializedName("id")
    val id: kotlin.Int? = 0,

    /* itemid */
    @SerializedName("itemid")
    val itemid: kotlin.Int? = 0,

    @SerializedName("modifiedby")
    val modifiedby: ElearningCoreCompetencyGradeCompetency200ResponseActionuser? = null,

    /* name */
    @SerializedName("name")
    val name: kotlin.String? = null,

    /* settingsdata */
    @SerializedName("settingsdata")
    val settingsdata: kotlin.String? = null,

    /* source */
    @SerializedName("source")
    val source: kotlin.String? = null,

    /* sourcename */
    @SerializedName("sourcename")
    val sourcename: kotlin.String? = null,

    /* timecreated */
    @SerializedName("timecreated")
    val timecreated: kotlin.Int? = 0,

    /* timemodified */
    @SerializedName("timemodified")
    val timemodified: kotlin.Int? = 0,

    /* type */
    @SerializedName("type")
    val type: kotlin.Int? = null,

    /* uniquerows */
    @SerializedName("uniquerows")
    val uniquerows: kotlin.Boolean? = false,

    /* usercreated */
    @SerializedName("usercreated")
    val usercreated: kotlin.Int? = {},

    /* usermodified */
    @SerializedName("usermodified")
    val usermodified: kotlin.Int? = 0

) {


}

