/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param destinationinstanceid Id of the other BBB we target for importing recordings into.                 The idea here is to remove already imported recordings.
 * @param groupid Group ID
 * @param sourcebigbluebuttonbnid bigbluebuttonbn instance id
 * @param sourcecourseid source courseid to filter by
 * @param tools a set of enabled tools
 */


data class ElearningModBigbluebuttonbnGetRecordingsToImportRequest (

    /* Id of the other BBB we target for importing recordings into.                 The idea here is to remove already imported recordings. */
    @SerializedName("destinationinstanceid")
    val destinationinstanceid: kotlin.Int,

    /* Group ID */
    @SerializedName("groupid")
    val groupid: kotlin.Int? = null,

    /* bigbluebuttonbn instance id */
    @SerializedName("sourcebigbluebuttonbnid")
    val sourcebigbluebuttonbnid: kotlin.Int? = 0,

    /* source courseid to filter by */
    @SerializedName("sourcecourseid")
    val sourcecourseid: kotlin.Int? = 0,

    /* a set of enabled tools */
    @SerializedName("tools")
    val tools: kotlin.String? = "protect,unprotect,publish,unpublish,delete"

) {


}

