/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningBlockIomadCompanyAdminGetCompaniesRequestCriteriaInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param criteria 
 */


data class ElearningBlockIomadCompanyAdminGetCompaniesRequest (

    @SerializedName("criteria")
    val criteria: kotlin.collections.List<ElearningBlockIomadCompanyAdminGetCompaniesRequestCriteriaInner>

) {


}

