/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param pathid ID of Iomad Learning Path
 * @param userids 
 */


data class ElearningLocalIomadLearningpathRemoveusersRequest (

    /* ID of Iomad Learning Path */
    @SerializedName("pathid")
    val pathid: kotlin.Int,

    @SerializedName("userids")
    val userids: kotlin.collections.List<kotlin.Any>

) {


}

