/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningAuthEmailSignupUser200ResponseWarningsInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param filecount Number of files in the area.
 * @param filesize Total size of the files in the area.
 * @param filesizewithoutreferences Total size of the area excluding file references
 * @param foldercount Number of folders in the area.
 * @param warnings 
 */


data class ElearningCoreUserGetPrivateFilesInfo200Response (

    /* Number of files in the area. */
    @SerializedName("filecount")
    val filecount: kotlin.Int,

    /* Total size of the files in the area. */
    @SerializedName("filesize")
    val filesize: kotlin.Int,

    /* Total size of the area excluding file references */
    @SerializedName("filesizewithoutreferences")
    val filesizewithoutreferences: kotlin.Int,

    /* Number of folders in the area. */
    @SerializedName("foldercount")
    val foldercount: kotlin.Int,

    @SerializedName("warnings")
    val warnings: kotlin.collections.List<ElearningAuthEmailSignupUser200ResponseWarningsInner>? = null

) {


}

