/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param archetype The archetype of the module exposing the content item
 * @param componentname The name of the component exposing the content item
 * @param favourite Has the user favourited the content item
 * @param help Html description / help for the content item
 * @param icon Html containing the icon for the content item
 * @param id The id of the content item
 * @param legacyitem If this item was pulled from the old callback and has no item id.
 * @param link The link to the content item creation page
 * @param name Name of the content item
 * @param purpose The purpose of the component exposing the content item
 * @param recommended Has this item been recommended
 * @param title The string title of the content item, human readable
 */


data class ElearningCoreCourseAddContentItemToUserFavourites200Response (

    /* The archetype of the module exposing the content item */
    @SerializedName("archetype")
    val archetype: kotlin.String,

    /* The name of the component exposing the content item */
    @SerializedName("componentname")
    val componentname: kotlin.String,

    /* Has the user favourited the content item */
    @SerializedName("favourite")
    val favourite: kotlin.Boolean,

    /* Html description / help for the content item */
    @SerializedName("help")
    val help: kotlin.String,

    /* Html containing the icon for the content item */
    @SerializedName("icon")
    val icon: kotlin.String,

    /* The id of the content item */
    @SerializedName("id")
    val id: kotlin.Int,

    /* If this item was pulled from the old callback and has no item id. */
    @SerializedName("legacyitem")
    val legacyitem: kotlin.Boolean,

    /* The link to the content item creation page */
    @SerializedName("link")
    val link: kotlin.String,

    /* Name of the content item */
    @SerializedName("name")
    val name: kotlin.String,

    /* The purpose of the component exposing the content item */
    @SerializedName("purpose")
    val purpose: kotlin.String,

    /* Has this item been recommended */
    @SerializedName("recommended")
    val recommended: kotlin.Boolean,

    /* The string title of the content item, human readable */
    @SerializedName("title")
    val title: kotlin.String

) {


}

