/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param type The name of the field: id                                         (numeric value of id) or username (alphanumeric value of username) 
 * @param `value` The value of the cohort
 */


data class ElearningCoreCohortAddCohortMembersRequestMembersInnerUsertype (

    /* The name of the field: id                                         (numeric value of id) or username (alphanumeric value of username)  */
    @SerializedName("type")
    val type: kotlin.String,

    /* The value of the cohort */
    @SerializedName("value")
    val `value`: kotlin.String

) {


}

