/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningAuthEmailSignupUser200ResponseWarningsInner
import org.openapitools.client.models.ElearningCoreCourseGetUserNavigationOptions200ResponseCoursesInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param courses 
 * @param warnings 
 */


data class ElearningCoreCourseGetUserNavigationOptions200Response (

    @SerializedName("courses")
    val courses: kotlin.collections.List<ElearningCoreCourseGetUserNavigationOptions200ResponseCoursesInner>,

    @SerializedName("warnings")
    val warnings: kotlin.collections.List<ElearningAuthEmailSignupUser200ResponseWarningsInner>? = null

) {


}

