/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param versionid The policy version ID
 * @param behalfid The id of user on whose behalf the user is viewing the policy
 */


data class ElearningToolPolicyGetPolicyVersionRequest (

    /* The policy version ID */
    @SerializedName("versionid")
    val versionid: kotlin.Int,

    /* The id of user on whose behalf the user is viewing the policy */
    @SerializedName("behalfid")
    val behalfid: kotlin.Int? = 0

) {


}

