/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningAuthEmailSignupUser200ResponseWarningsInner
import org.openapitools.client.models.ElearningModGlossaryPrepareEntryForEdition200ResponseAreasInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param aliases 
 * @param areas 
 * @param attachmentsid Draft item id for the file manager.
 * @param categories 
 * @param inlineattachmentsid Draft item id for the text editor.
 * @param warnings 
 */


data class ElearningModGlossaryPrepareEntryForEdition200Response (

    @SerializedName("aliases")
    val aliases: kotlin.collections.List<kotlin.Any>,

    @SerializedName("areas")
    val areas: kotlin.collections.List<ElearningModGlossaryPrepareEntryForEdition200ResponseAreasInner>,

    /* Draft item id for the file manager. */
    @SerializedName("attachmentsid")
    val attachmentsid: kotlin.Int,

    @SerializedName("categories")
    val categories: kotlin.collections.List<kotlin.Any>,

    /* Draft item id for the text editor. */
    @SerializedName("inlineattachmentsid")
    val inlineattachmentsid: kotlin.Int,

    @SerializedName("warnings")
    val warnings: kotlin.collections.List<ElearningAuthEmailSignupUser200ResponseWarningsInner>? = null

) {


}

