/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param conversationids 
 * @param userid The user id of who we want to delete the conversation for
 */


data class ElearningCoreMessageDeleteConversationsByIdRequest (

    @SerializedName("conversationids")
    val conversationids: kotlin.collections.List<kotlin.Any>,

    /* The user id of who we want to delete the conversation for */
    @SerializedName("userid")
    val userid: kotlin.Int

) {


}

