/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningAuthEmailSignupUser200ResponseWarningsInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param result Whether the record was properly marked for deletion or not
 * @param warnings 
 */


data class ElearningToolDataprivacyConfirmContextsForDeletion200Response (

    /* Whether the record was properly marked for deletion or not */
    @SerializedName("result")
    val result: kotlin.Boolean,

    @SerializedName("warnings")
    val warnings: kotlin.collections.List<ElearningAuthEmailSignupUser200ResponseWarningsInner>? = null

) {


}

