/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param chatid Chat instance id.
 * @param groupid Get messages from users in this group.                                                 0 means that the function will determine the user group
 * @param showall Whether to show completed sessions or not.
 */


data class ElearningModChatGetSessionsRequest (

    /* Chat instance id. */
    @SerializedName("chatid")
    val chatid: kotlin.Int,

    /* Get messages from users in this group.                                                 0 means that the function will determine the user group */
    @SerializedName("groupid")
    val groupid: kotlin.Int? = 0,

    /* Whether to show completed sessions or not. */
    @SerializedName("showall")
    val showall: kotlin.Boolean? = false

) {


}

