/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param submissionid Submission id
 */


data class ElearningModWorkshopGetSubmissionRequest (

    /* Submission id */
    @SerializedName("submissionid")
    val submissionid: kotlin.Int

) {


}

