/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningCoreFiltersGetAvailableInContextRequestContextsInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param contexts 
 */


data class ElearningCoreFiltersGetAvailableInContextRequest (

    @SerializedName("contexts")
    val contexts: kotlin.collections.List<ElearningCoreFiltersGetAvailableInContextRequestContextsInner>

) {


}

