/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param scoid sco id
 * @param userid user id
 * @param attempt attempt number (0 for last attempt)
 */


data class ElearningModScormGetScormScoTracksRequest (

    /* sco id */
    @SerializedName("scoid")
    val scoid: kotlin.Int,

    /* user id */
    @SerializedName("userid")
    val userid: kotlin.Int,

    /* attempt number (0 for last attempt) */
    @SerializedName("attempt")
    val attempt: kotlin.Int? = 0

) {


}

