/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param conversationid The conversation id who who we are marking the messages as read for
 * @param userid The user id who who we are marking the messages as read for
 */


data class ElearningCoreMessageMarkAllConversationMessagesAsReadRequest (

    /* The conversation id who who we are marking the messages as read for */
    @SerializedName("conversationid")
    val conversationid: kotlin.Int,

    /* The user id who who we are marking the messages as read for */
    @SerializedName("userid")
    val userid: kotlin.Int

) {


}

