/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param filter Filter plugin name
 * @param inheritedstate 1 or 0 to use when localstate is set to inherit
 * @param localstate Filter state: 1 for on, -1 for off, 0 if inherit
 */


data class ElearningCoreCourseGetCoursesByField200ResponseCoursesInnerFiltersInner (

    /* Filter plugin name */
    @SerializedName("filter")
    val filter: kotlin.String? = null,

    /* 1 or 0 to use when localstate is set to inherit */
    @SerializedName("inheritedstate")
    val inheritedstate: kotlin.Int? = null,

    /* Filter state: 1 for on, -1 for off, 0 if inherit */
    @SerializedName("localstate")
    val localstate: kotlin.Int? = null

) {


}

