/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param key the user column to search, expected keys (value format) are:                                 \"id\" (int) matching department id,                                 \"name\" (string) department name (Note: you can use % for searching but it may be considerably slower!),                                 \"shortname\" (string) department short name (Note: you can use % for searching but it may be considerably slower!),                                 \"company\" (int) matching company id,                                 \"parent\" (int) matching department parent id
 * @param `value` the value to search
 */


data class ElearningBlockIomadCompanyAdminGetDepartmentsRequestCriteriaInner (

    /* the user column to search, expected keys (value format) are:                                 \"id\" (int) matching department id,                                 \"name\" (string) department name (Note: you can use % for searching but it may be considerably slower!),                                 \"shortname\" (string) department short name (Note: you can use % for searching but it may be considerably slower!),                                 \"company\" (int) matching company id,                                 \"parent\" (int) matching department parent id */
    @SerializedName("key")
    val key: kotlin.String? = null,

    /* the value to search */
    @SerializedName("value")
    val `value`: kotlin.String? = null

) {


}

