/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningModForumGetDiscussionPost200ResponsePostAuthorGroupsInner
import org.openapitools.client.models.ElearningModForumGetDiscussionPost200ResponsePostAuthorUrls

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param urls 
 * @param fullname fullname
 * @param groups 
 * @param id id
 * @param isdeleted isdeleted
 */


data class ElearningModForumGetDiscussionPost200ResponsePostAuthor (

    @SerializedName("urls")
    val urls: ElearningModForumGetDiscussionPost200ResponsePostAuthorUrls,

    /* fullname */
    @SerializedName("fullname")
    val fullname: kotlin.String? = null,

    @SerializedName("groups")
    val groups: kotlin.collections.List<ElearningModForumGetDiscussionPost200ResponsePostAuthorGroupsInner>? = null,

    /* id */
    @SerializedName("id")
    val id: kotlin.Int? = null,

    /* isdeleted */
    @SerializedName("isdeleted")
    val isdeleted: kotlin.Boolean? = null

) {


}

