/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param cmid course module id
 * @param newstate the new activity completion state
 * @param userid user id
 */


data class ElearningCoreCompletionOverrideActivityCompletionStatusRequest (

    /* course module id */
    @SerializedName("cmid")
    val cmid: kotlin.Int,

    /* the new activity completion state */
    @SerializedName("newstate")
    val newstate: kotlin.Int,

    /* user id */
    @SerializedName("userid")
    val userid: kotlin.Int

) {


}

