/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningModGlossaryGetEntriesByAuthorRequestOptions

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param categoryid The category ID. Use '0' for all categories, or '-1' for uncategorised entries.
 * @param id The glossary ID.
 * @param from Start returning records from here
 * @param limit Number of records to return
 * @param options 
 */


data class ElearningModGlossaryGetEntriesByCategoryRequest (

    /* The category ID. Use '0' for all categories, or '-1' for uncategorised entries. */
    @SerializedName("categoryid")
    val categoryid: kotlin.Int,

    /* The glossary ID. */
    @SerializedName("id")
    val id: kotlin.Int,

    /* Start returning records from here */
    @SerializedName("from")
    val from: kotlin.Int? = 0,

    /* Number of records to return */
    @SerializedName("limit")
    val limit: kotlin.Int? = 20,

    @SerializedName("options")
    val options: ElearningModGlossaryGetEntriesByAuthorRequestOptions? = null

) {


}

