/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param plugin The name of the plugin
 * @param state The target state
 */


data class ElearningCoreAdminSetBlockProtectionRequest (

    /* The name of the plugin */
    @SerializedName("plugin")
    val plugin: kotlin.String,

    /* The target state */
    @SerializedName("state")
    val state: kotlin.Int

) {


}

