/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningAuthEmailSignupUser200ResponseWarningsInner
import org.openapitools.client.models.ElearningModResourceGetResourcesByCourses200ResponseResourcesInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param resources 
 * @param warnings 
 */


data class ElearningModResourceGetResourcesByCourses200Response (

    @SerializedName("resources")
    val resources: kotlin.collections.List<ElearningModResourceGetResourcesByCourses200ResponseResourcesInner>,

    @SerializedName("warnings")
    val warnings: kotlin.collections.List<ElearningAuthEmailSignupUser200ResponseWarningsInner>? = null

) {


}

