/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param component component containing the template
 * @param template name of the template
 * @param themename The current theme.
 * @param includecomments Include comments or not
 * @param lang lang
 */


data class ElearningCoreOutputLoadTemplateWithDependenciesRequest (

    /* component containing the template */
    @SerializedName("component")
    val component: kotlin.String,

    /* name of the template */
    @SerializedName("template")
    val template: kotlin.String,

    /* The current theme. */
    @SerializedName("themename")
    val themename: kotlin.String,

    /* Include comments or not */
    @SerializedName("includecomments")
    val includecomments: kotlin.Boolean? = false,

    /* lang */
    @SerializedName("lang")
    val lang: kotlin.String? = null

) {


}

