/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param pathid ID of (target) learning path
 * @param category Show only courses in this category (and children)
 * @param filter Filter course list returned
 * @param program Show only courses assigned to this program license
 */


data class ElearningLocalIomadLearningpathGetprospectivecoursesRequest (

    /* ID of (target) learning path */
    @SerializedName("pathid")
    val pathid: kotlin.Int,

    /* Show only courses in this category (and children) */
    @SerializedName("category")
    val category: kotlin.Int? = 0,

    /* Filter course list returned */
    @SerializedName("filter")
    val filter: kotlin.String? = "",

    /* Show only courses assigned to this program license */
    @SerializedName("program")
    val program: kotlin.Int? = 0

) {


}

