/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param columnid Column ID
 * @param reportid Report ID
 */


data class ElearningCoreReportbuilderColumnsDeleteRequest (

    /* Column ID */
    @SerializedName("columnid")
    val columnid: kotlin.Int,

    /* Report ID */
    @SerializedName("reportid")
    val reportid: kotlin.Int

) {


}

