/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param eventid The event id to be retrieved
 */


data class ElearningCoreCalendarGetCalendarEventByIdRequest (

    /* The event id to be retrieved */
    @SerializedName("eventid")
    val eventid: kotlin.Int

) {


}

