/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param actionable actionable
 * @param itemcount itemcount
 * @param name name
 * @param showitemcount showitemcount
 * @param url url
 */


data class ElearningCoreCalendarGetActionEventsByCourses200ResponseGroupedbycourseInnerEventsInnerAction (

    /* actionable */
    @SerializedName("actionable")
    val actionable: kotlin.Boolean,

    /* itemcount */
    @SerializedName("itemcount")
    val itemcount: kotlin.Int,

    /* name */
    @SerializedName("name")
    val name: kotlin.String,

    /* showitemcount */
    @SerializedName("showitemcount")
    val showitemcount: kotlin.Boolean = false,

    /* url */
    @SerializedName("url")
    val url: kotlin.String

) {


}

