/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningModFeedbackGetAnalysis200ResponseItemsdataInnerItemItemfilesInner
import org.openapitools.client.models.ElearningModForumGetDiscussionPost200ResponsePostAttachmentsInner
import org.openapitools.client.models.ElearningModForumGetDiscussionPost200ResponsePostAuthor
import org.openapitools.client.models.ElearningModForumGetDiscussionPost200ResponsePostCapabilities
import org.openapitools.client.models.ElearningModForumGetDiscussionPost200ResponsePostHtml
import org.openapitools.client.models.ElearningModForumGetDiscussionPost200ResponsePostTagsInner
import org.openapitools.client.models.ElearningModForumGetDiscussionPost200ResponsePostUrls

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param attachments 
 * @param author 
 * @param capabilities 
 * @param charcount charcount
 * @param discussionid discussionid
 * @param hasparent hasparent
 * @param haswordcount haswordcount
 * @param html 
 * @param id id
 * @param isdeleted isdeleted
 * @param isprivatereply isprivatereply
 * @param message message
 * @param messageformat message format (1 = HTML, 0 = MOODLE, 2 = PLAIN, or 4 = MARKDOWN)
 * @param messageinlinefiles 
 * @param parentid parentid
 * @param replysubject replysubject
 * @param subject subject
 * @param tags 
 * @param timecreated timecreated
 * @param timemodified timemodified
 * @param unread unread
 * @param urls 
 * @param wordcount wordcount
 */


data class ElearningModForumGetDiscussionPosts200ResponsePostsInner (

    @SerializedName("attachments")
    val attachments: kotlin.collections.List<ElearningModForumGetDiscussionPost200ResponsePostAttachmentsInner>? = null,

    @SerializedName("author")
    val author: ElearningModForumGetDiscussionPost200ResponsePostAuthor? = null,

    @SerializedName("capabilities")
    val capabilities: ElearningModForumGetDiscussionPost200ResponsePostCapabilities? = null,

    /* charcount */
    @SerializedName("charcount")
    val charcount: kotlin.Int? = null,

    /* discussionid */
    @SerializedName("discussionid")
    val discussionid: kotlin.Int? = null,

    /* hasparent */
    @SerializedName("hasparent")
    val hasparent: kotlin.Boolean? = null,

    /* haswordcount */
    @SerializedName("haswordcount")
    val haswordcount: kotlin.Boolean? = null,

    @SerializedName("html")
    val html: ElearningModForumGetDiscussionPost200ResponsePostHtml? = null,

    /* id */
    @SerializedName("id")
    val id: kotlin.Int? = null,

    /* isdeleted */
    @SerializedName("isdeleted")
    val isdeleted: kotlin.Boolean? = null,

    /* isprivatereply */
    @SerializedName("isprivatereply")
    val isprivatereply: kotlin.Boolean? = null,

    /* message */
    @SerializedName("message")
    val message: kotlin.String? = null,

    /* message format (1 = HTML, 0 = MOODLE, 2 = PLAIN, or 4 = MARKDOWN) */
    @SerializedName("messageformat")
    val messageformat: kotlin.Int? = null,

    @SerializedName("messageinlinefiles")
    val messageinlinefiles: kotlin.collections.List<ElearningModFeedbackGetAnalysis200ResponseItemsdataInnerItemItemfilesInner>? = null,

    /* parentid */
    @SerializedName("parentid")
    val parentid: kotlin.Int? = null,

    /* replysubject */
    @SerializedName("replysubject")
    val replysubject: kotlin.String? = null,

    /* subject */
    @SerializedName("subject")
    val subject: kotlin.String? = null,

    @SerializedName("tags")
    val tags: kotlin.collections.List<ElearningModForumGetDiscussionPost200ResponsePostTagsInner>? = null,

    /* timecreated */
    @SerializedName("timecreated")
    val timecreated: kotlin.Int? = null,

    /* timemodified */
    @SerializedName("timemodified")
    val timemodified: kotlin.Int? = null,

    /* unread */
    @SerializedName("unread")
    val unread: kotlin.Boolean? = null,

    @SerializedName("urls")
    val urls: ElearningModForumGetDiscussionPost200ResponsePostUrls? = null,

    /* wordcount */
    @SerializedName("wordcount")
    val wordcount: kotlin.Int? = null

) {


}

