/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningCoreCompetencyGradeCompetency200ResponseActionuser

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param comments comments
 * @param commentsformat commentsformat
 * @param creationmethod creationmethod
 * @param dpo dpo
 * @param dpocomment dpocomment
 * @param dpocommentformat dpocommentformat
 * @param foruser 
 * @param id id
 * @param requestedby requestedby
 * @param status status
 * @param statuslabel statuslabel
 * @param statuslabelclass statuslabelclass
 * @param systemapproved systemapproved
 * @param timecreated timecreated
 * @param timemodified timemodified
 * @param type type
 * @param typename typename
 * @param typenameshort typenameshort
 * @param userid userid
 * @param usermodified usermodified
 * @param allowfiltering allowfiltering
 * @param approvedeny approvedeny
 * @param canmarkcomplete canmarkcomplete
 * @param canreview canreview
 * @param dpouser 
 * @param messagehtml messagehtml
 * @param requestedbyuser 
 */


data class ElearningToolDataprivacyGetDataRequest200ResponseResult (

    /* comments */
    @SerializedName("comments")
    val comments: kotlin.String = "",

    /* commentsformat */
    @SerializedName("commentsformat")
    val commentsformat: kotlin.Int = 2,

    /* creationmethod */
    @SerializedName("creationmethod")
    val creationmethod: kotlin.Int = 0,

    /* dpo */
    @SerializedName("dpo")
    val dpo: kotlin.Int = 0,

    /* dpocomment */
    @SerializedName("dpocomment")
    val dpocomment: kotlin.String = "",

    /* dpocommentformat */
    @SerializedName("dpocommentformat")
    val dpocommentformat: kotlin.Int = 2,

    @SerializedName("foruser")
    val foruser: ElearningCoreCompetencyGradeCompetency200ResponseActionuser,

    /* id */
    @SerializedName("id")
    val id: kotlin.Int = 0,

    /* requestedby */
    @SerializedName("requestedby")
    val requestedby: kotlin.Int = 0,

    /* status */
    @SerializedName("status")
    val status: kotlin.Int = 2,

    /* statuslabel */
    @SerializedName("statuslabel")
    val statuslabel: kotlin.String,

    /* statuslabelclass */
    @SerializedName("statuslabelclass")
    val statuslabelclass: kotlin.String,

    /* systemapproved */
    @SerializedName("systemapproved")
    val systemapproved: kotlin.Boolean = false,

    /* timecreated */
    @SerializedName("timecreated")
    val timecreated: kotlin.Int = 0,

    /* timemodified */
    @SerializedName("timemodified")
    val timemodified: kotlin.Int = 0,

    /* type */
    @SerializedName("type")
    val type: kotlin.Int,

    /* typename */
    @SerializedName("typename")
    val typename: kotlin.String,

    /* typenameshort */
    @SerializedName("typenameshort")
    val typenameshort: kotlin.String,

    /* userid */
    @SerializedName("userid")
    val userid: kotlin.Int = {},

    /* usermodified */
    @SerializedName("usermodified")
    val usermodified: kotlin.Int = 0,

    /* allowfiltering */
    @SerializedName("allowfiltering")
    val allowfiltering: kotlin.Boolean? = false,

    /* approvedeny */
    @SerializedName("approvedeny")
    val approvedeny: kotlin.Boolean? = false,

    /* canmarkcomplete */
    @SerializedName("canmarkcomplete")
    val canmarkcomplete: kotlin.Boolean? = false,

    /* canreview */
    @SerializedName("canreview")
    val canreview: kotlin.Boolean? = false,

    @SerializedName("dpouser")
    val dpouser: ElearningCoreCompetencyGradeCompetency200ResponseActionuser? = null,

    /* messagehtml */
    @SerializedName("messagehtml")
    val messagehtml: kotlin.String? = null,

    @SerializedName("requestedbyuser")
    val requestedbyuser: ElearningCoreCompetencyGradeCompetency200ResponseActionuser? = null

) {


}

