/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param allowall Allows to select All file types, does not apply with onlytypes are set.
 * @param current Current types that should be selected.
 * @param onlytypes Limit the browser to the given groups and extensions
 */


data class ElearningCoreFormGetFiletypesBrowserDataRequest (

    /* Allows to select All file types, does not apply with onlytypes are set. */
    @SerializedName("allowall")
    val allowall: kotlin.Boolean? = true,

    /* Current types that should be selected. */
    @SerializedName("current")
    val current: kotlin.String? = "",

    /* Limit the browser to the given groups and extensions */
    @SerializedName("onlytypes")
    val onlytypes: kotlin.String? = ""

) {


}

