/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningCoreBlockGetDashboardBlocks200ResponseBlocksInnerContentsFilesInner

import com.google.gson.annotations.SerializedName

/**
 * IMS content packages
 *
 * @param course Course id
 * @param coursemodule Course module id
 * @param groupingid Group id
 * @param groupmode Group mode
 * @param id Activity instance id
 * @param intro Activity introduction
 * @param introfiles 
 * @param introformat intro format (1 = HTML, 0 = MOODLE, 2 = PLAIN, or 4 = MARKDOWN)
 * @param keepold Number of old IMSCP to keep
 * @param lang Forced activity language
 * @param name Activity name
 * @param revision Revision
 * @param section Course section id
 * @param structure IMSCP structure
 * @param timemodified Time of last modification
 * @param visible Visible
 */


data class ElearningModImscpGetImscpsByCourses200ResponseImscpsInner (

    /* Course id */
    @SerializedName("course")
    val course: kotlin.Int? = null,

    /* Course module id */
    @SerializedName("coursemodule")
    val coursemodule: kotlin.Int? = null,

    /* Group id */
    @SerializedName("groupingid")
    val groupingid: kotlin.Int? = null,

    /* Group mode */
    @SerializedName("groupmode")
    val groupmode: kotlin.Int? = null,

    /* Activity instance id */
    @SerializedName("id")
    val id: kotlin.Int? = null,

    /* Activity introduction */
    @SerializedName("intro")
    val intro: kotlin.String? = null,

    @SerializedName("introfiles")
    val introfiles: kotlin.collections.List<ElearningCoreBlockGetDashboardBlocks200ResponseBlocksInnerContentsFilesInner>? = null,

    /* intro format (1 = HTML, 0 = MOODLE, 2 = PLAIN, or 4 = MARKDOWN) */
    @SerializedName("introformat")
    val introformat: kotlin.Int? = null,

    /* Number of old IMSCP to keep */
    @SerializedName("keepold")
    val keepold: kotlin.Int? = null,

    /* Forced activity language */
    @SerializedName("lang")
    val lang: kotlin.String? = null,

    /* Activity name */
    @SerializedName("name")
    val name: kotlin.String? = null,

    /* Revision */
    @SerializedName("revision")
    val revision: kotlin.Int? = null,

    /* Course section id */
    @SerializedName("section")
    val section: kotlin.Int? = null,

    /* IMSCP structure */
    @SerializedName("structure")
    val structure: kotlin.String? = null,

    /* Time of last modification */
    @SerializedName("timemodified")
    val timemodified: kotlin.String? = null,

    /* Visible */
    @SerializedName("visible")
    val visible: kotlin.Boolean? = null

) {


}

