/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningAuthEmailSignupUser200ResponseWarningsInner
import org.openapitools.client.models.ElearningModDataGetEntries200ResponseEntriesInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param propertyEntries 
 * @param totalcount Total count of records.
 * @param totalfilesize Total size (bytes) of the files included in the records.
 * @param listviewcontents The list view contents as is rendered in the site.
 * @param warnings 
 */


data class ElearningModDataGetEntries200Response (

    @SerializedName("entries")
    val propertyEntries: kotlin.collections.List<ElearningModDataGetEntries200ResponseEntriesInner>,

    /* Total count of records. */
    @SerializedName("totalcount")
    val totalcount: kotlin.Int,

    /* Total size (bytes) of the files included in the records. */
    @SerializedName("totalfilesize")
    val totalfilesize: kotlin.Int,

    /* The list view contents as is rendered in the site. */
    @SerializedName("listviewcontents")
    val listviewcontents: kotlin.String? = null,

    @SerializedName("warnings")
    val warnings: kotlin.collections.List<ElearningAuthEmailSignupUser200ResponseWarningsInner>? = null

) {


}

