/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param definition definition
 * @param definitionformat definition format (1 = HTML, 0 = MOODLE, 2 = PLAIN, or 4 = MARKDOWN)
 * @param id level id
 * @param score score
 */


data class ElearningCoreGradingSaveDefinitionsRequestAreasInnerDefinitionsInnerRubricRubricCriteriaInnerLevelsInner (

    /* definition */
    @SerializedName("definition")
    val definition: kotlin.String? = null,

    /* definition format (1 = HTML, 0 = MOODLE, 2 = PLAIN, or 4 = MARKDOWN) */
    @SerializedName("definitionformat")
    val definitionformat: kotlin.Int? = null,

    /* level id */
    @SerializedName("id")
    val id: kotlin.Int? = null,

    /* score */
    @SerializedName("score")
    val score: java.math.BigDecimal? = null

) {


}

