/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * warning
 *
 * @param item item
 * @param itemid item id
 * @param message untranslated english message to explain the warning
 * @param warningcode the warning code can be used by the client app to implement specific behaviour
 */


data class ElearningAuthEmailGetSignupSettings200ResponseWarningsInner (

    /* item */
    @SerializedName("item")
    val item: kotlin.String? = null,

    /* item id */
    @SerializedName("itemid")
    val itemid: kotlin.Int? = null,

    /* untranslated english message to explain the warning */
    @SerializedName("message")
    val message: kotlin.String? = null,

    /* the warning code can be used by the client app to implement specific behaviour */
    @SerializedName("warningcode")
    val warningcode: kotlin.String? = null

) {


}

