/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningAuthEmailSignupUser200ResponseWarningsInner
import org.openapitools.client.models.ElearningModScormGetScormUserData200ResponseDataInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param `data` 
 * @param warnings 
 */


data class ElearningModScormGetScormUserData200Response (

    @SerializedName("data")
    val `data`: kotlin.collections.List<ElearningModScormGetScormUserData200ResponseDataInner>,

    @SerializedName("warnings")
    val warnings: kotlin.collections.List<ElearningAuthEmailSignupUser200ResponseWarningsInner>? = null

) {


}

