/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param form Form class
 * @param formdata url-encoded form data
 */


data class ElearningCoreFormDynamicFormRequest (

    /* Form class */
    @SerializedName("form")
    val form: kotlin.String,

    /* url-encoded form data */
    @SerializedName("formdata")
    val formdata: kotlin.String

) {


}

