/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningCoreCalendarGetActionEventsByCourse200ResponseEventsInnerAction
import org.openapitools.client.models.ElearningCoreCalendarGetActionEventsByCourse200ResponseEventsInnerCategory
import org.openapitools.client.models.ElearningCoreCalendarGetActionEventsByCourse200ResponseEventsInnerCourse
import org.openapitools.client.models.ElearningCoreCalendarGetActionEventsByCourse200ResponseEventsInnerIcon
import org.openapitools.client.models.ElearningCoreCalendarGetActionEventsByCourse200ResponseEventsInnerSubscription

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param action 
 * @param activityname activityname
 * @param activitystr activitystr
 * @param candelete candelete
 * @param canedit canedit
 * @param category 
 * @param categoryid categoryid
 * @param component component
 * @param course 
 * @param deleteurl deleteurl
 * @param description description
 * @param descriptionformat description format (1 = HTML, 0 = MOODLE, 2 = PLAIN, or 4 = MARKDOWN)
 * @param editurl editurl
 * @param eventcount eventcount
 * @param eventtype eventtype
 * @param formattedlocation formattedlocation
 * @param formattedtime formattedtime
 * @param groupid groupid
 * @param groupname groupname
 * @param icon 
 * @param id id
 * @param instance instance
 * @param isactionevent isactionevent
 * @param iscategoryevent iscategoryevent
 * @param iscourseevent iscourseevent
 * @param location location
 * @param modulename modulename
 * @param name name
 * @param normalisedeventtype normalisedeventtype
 * @param normalisedeventtypetext normalisedeventtypetext
 * @param overdue overdue
 * @param purpose purpose
 * @param repeatid repeatid
 * @param subscription 
 * @param timeduration timeduration
 * @param timemodified timemodified
 * @param timesort timesort
 * @param timestart timestart
 * @param timeusermidnight timeusermidnight
 * @param url url
 * @param userid userid
 * @param viewurl viewurl
 * @param visible visible
 */


data class ElearningCoreCalendarGetActionEventsByCourse200ResponseEventsInner (

    @SerializedName("action")
    val action: ElearningCoreCalendarGetActionEventsByCourse200ResponseEventsInnerAction? = null,

    /* activityname */
    @SerializedName("activityname")
    val activityname: kotlin.String? = null,

    /* activitystr */
    @SerializedName("activitystr")
    val activitystr: kotlin.String? = null,

    /* candelete */
    @SerializedName("candelete")
    val candelete: kotlin.Boolean? = null,

    /* canedit */
    @SerializedName("canedit")
    val canedit: kotlin.Boolean? = null,

    @SerializedName("category")
    val category: ElearningCoreCalendarGetActionEventsByCourse200ResponseEventsInnerCategory? = null,

    /* categoryid */
    @SerializedName("categoryid")
    val categoryid: kotlin.Int? = null,

    /* component */
    @SerializedName("component")
    val component: kotlin.String? = null,

    @SerializedName("course")
    val course: ElearningCoreCalendarGetActionEventsByCourse200ResponseEventsInnerCourse? = null,

    /* deleteurl */
    @SerializedName("deleteurl")
    val deleteurl: kotlin.String? = null,

    /* description */
    @SerializedName("description")
    val description: kotlin.String? = null,

    /* description format (1 = HTML, 0 = MOODLE, 2 = PLAIN, or 4 = MARKDOWN) */
    @SerializedName("descriptionformat")
    val descriptionformat: kotlin.Int? = 1,

    /* editurl */
    @SerializedName("editurl")
    val editurl: kotlin.String? = null,

    /* eventcount */
    @SerializedName("eventcount")
    val eventcount: kotlin.Int? = null,

    /* eventtype */
    @SerializedName("eventtype")
    val eventtype: kotlin.String? = null,

    /* formattedlocation */
    @SerializedName("formattedlocation")
    val formattedlocation: kotlin.String? = null,

    /* formattedtime */
    @SerializedName("formattedtime")
    val formattedtime: kotlin.String? = null,

    /* groupid */
    @SerializedName("groupid")
    val groupid: kotlin.Int? = null,

    /* groupname */
    @SerializedName("groupname")
    val groupname: kotlin.String? = null,

    @SerializedName("icon")
    val icon: ElearningCoreCalendarGetActionEventsByCourse200ResponseEventsInnerIcon? = null,

    /* id */
    @SerializedName("id")
    val id: kotlin.Int? = null,

    /* instance */
    @SerializedName("instance")
    val instance: kotlin.Int? = null,

    /* isactionevent */
    @SerializedName("isactionevent")
    val isactionevent: kotlin.Boolean? = null,

    /* iscategoryevent */
    @SerializedName("iscategoryevent")
    val iscategoryevent: kotlin.Boolean? = null,

    /* iscourseevent */
    @SerializedName("iscourseevent")
    val iscourseevent: kotlin.Boolean? = null,

    /* location */
    @SerializedName("location")
    val location: kotlin.String? = null,

    /* modulename */
    @SerializedName("modulename")
    val modulename: kotlin.String? = null,

    /* name */
    @SerializedName("name")
    val name: kotlin.String? = null,

    /* normalisedeventtype */
    @SerializedName("normalisedeventtype")
    val normalisedeventtype: kotlin.String? = null,

    /* normalisedeventtypetext */
    @SerializedName("normalisedeventtypetext")
    val normalisedeventtypetext: kotlin.String? = null,

    /* overdue */
    @SerializedName("overdue")
    val overdue: kotlin.Boolean? = false,

    /* purpose */
    @SerializedName("purpose")
    val purpose: kotlin.String? = null,

    /* repeatid */
    @SerializedName("repeatid")
    val repeatid: kotlin.Int? = null,

    @SerializedName("subscription")
    val subscription: ElearningCoreCalendarGetActionEventsByCourse200ResponseEventsInnerSubscription? = null,

    /* timeduration */
    @SerializedName("timeduration")
    val timeduration: kotlin.Int? = null,

    /* timemodified */
    @SerializedName("timemodified")
    val timemodified: kotlin.Int? = null,

    /* timesort */
    @SerializedName("timesort")
    val timesort: kotlin.Int? = null,

    /* timestart */
    @SerializedName("timestart")
    val timestart: kotlin.Int? = null,

    /* timeusermidnight */
    @SerializedName("timeusermidnight")
    val timeusermidnight: kotlin.Int? = null,

    /* url */
    @SerializedName("url")
    val url: kotlin.String? = null,

    /* userid */
    @SerializedName("userid")
    val userid: kotlin.Int? = null,

    /* viewurl */
    @SerializedName("viewurl")
    val viewurl: kotlin.String? = null,

    /* visible */
    @SerializedName("visible")
    val visible: kotlin.Int? = null

) {


}

