/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningAuthEmailSignupUser200ResponseWarningsInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param validated Whether the password was successfully validated
 * @param hint Password hint (if enabled)
 * @param warnings 
 */


data class ElearningEnrolGuestValidatePassword200Response (

    /* Whether the password was successfully validated */
    @SerializedName("validated")
    val validated: kotlin.Boolean,

    /* Password hint (if enabled) */
    @SerializedName("hint")
    val hint: kotlin.String? = null,

    @SerializedName("warnings")
    val warnings: kotlin.collections.List<ElearningAuthEmailSignupUser200ResponseWarningsInner>? = null

) {


}

