/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param backupid Backup id
 * @param contextid Context id
 */


data class ElearningCoreBackupGetAsyncBackupLinksRestoreRequest (

    /* Backup id */
    @SerializedName("backupid")
    val backupid: kotlin.String,

    /* Context id */
    @SerializedName("contextid")
    val contextid: kotlin.Int

) {


}

