/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param cohortid cohort record id
 * @param userid user id
 */


data class ElearningCoreCohortDeleteCohortMembersRequestMembersInner (

    /* cohort record id */
    @SerializedName("cohortid")
    val cohortid: kotlin.Int? = null,

    /* user id */
    @SerializedName("userid")
    val userid: kotlin.Int? = null

) {


}

