/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param pageid Wiki page ID.
 */


data class ElearningModWikiViewPageRequest (

    /* Wiki page ID. */
    @SerializedName("pageid")
    val pageid: kotlin.Int

) {


}

