/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param attemptnumber attempt number
 * @param grade grade
 * @param grader grader, -1 if grader is hidden
 * @param id grade id
 * @param timecreated grade creation time
 * @param timemodified grade last modified time
 * @param userid student id
 * @param assignment assignment id
 * @param gradefordisplay grade rendered into a format suitable for display
 */


data class ElearningModAssignGetSubmissionStatus200ResponseFeedbackGrade (

    /* attempt number */
    @SerializedName("attemptnumber")
    val attemptnumber: kotlin.Int,

    /* grade */
    @SerializedName("grade")
    val grade: kotlin.String,

    /* grader, -1 if grader is hidden */
    @SerializedName("grader")
    val grader: kotlin.Int,

    /* grade id */
    @SerializedName("id")
    val id: kotlin.Int,

    /* grade creation time */
    @SerializedName("timecreated")
    val timecreated: kotlin.Int,

    /* grade last modified time */
    @SerializedName("timemodified")
    val timemodified: kotlin.Int,

    /* student id */
    @SerializedName("userid")
    val userid: kotlin.Int,

    /* assignment id */
    @SerializedName("assignment")
    val assignment: kotlin.Int? = null,

    /* grade rendered into a format suitable for display */
    @SerializedName("gradefordisplay")
    val gradefordisplay: kotlin.String? = null

) {


}

