/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param licensecourseid Course ID
 * @param licenseid License ID
 * @param userid User ID
 */


data class ElearningBlockIomadCompanyAdminUnallocateLicensesRequestLicensesInner (

    /* Course ID */
    @SerializedName("licensecourseid")
    val licensecourseid: kotlin.Int? = null,

    /* License ID */
    @SerializedName("licenseid")
    val licenseid: kotlin.Int? = null,

    /* User ID */
    @SerializedName("userid")
    val userid: kotlin.Int? = null

) {


}

