/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningCoreCompetencyCreateCompetency200Response
import org.openapitools.client.models.ElearningToolLpDataForCompetencySummary200ResponseComppath
import org.openapitools.client.models.ElearningToolLpDataForPlanPage200ResponseCompetenciesInnerUsercompetency
import org.openapitools.client.models.ElearningToolLpDataForPlanPage200ResponseCompetenciesInnerUsercompetencyplan

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param competency 
 * @param comppath 
 * @param usercompetency 
 * @param usercompetencyplan 
 */


data class ElearningToolLpDataForPlanPage200ResponseCompetenciesInner (

    @SerializedName("competency")
    val competency: ElearningCoreCompetencyCreateCompetency200Response? = null,

    @SerializedName("comppath")
    val comppath: ElearningToolLpDataForCompetencySummary200ResponseComppath? = null,

    @SerializedName("usercompetency")
    val usercompetency: ElearningToolLpDataForPlanPage200ResponseCompetenciesInnerUsercompetency? = null,

    @SerializedName("usercompetencyplan")
    val usercompetencyplan: ElearningToolLpDataForPlanPage200ResponseCompetenciesInnerUsercompetencyplan? = null

) {


}

