/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningCoreCourseGetCourseContentItems200ResponseContentItemsInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param contentItems 
 */


data class ElearningCoreCourseGetCourseContentItems200Response (

    @SerializedName("content_items")
    val contentItems: kotlin.collections.List<ElearningCoreCourseGetCourseContentItems200ResponseContentItemsInner>

) {


}

