/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param component component
 * @param filearea file area
 * @param filecontent file content
 * @param filename file name
 * @param filepath file path
 * @param itemid associated id
 * @param contextid context id
 * @param contextlevel The context level to put the file in,                         (block, course, coursecat, system, user, module)
 * @param instanceid The Instance id of item associated                          with the context level
 */


data class ElearningCoreFilesUploadRequest (

    /* component */
    @SerializedName("component")
    val component: kotlin.String,

    /* file area */
    @SerializedName("filearea")
    val filearea: kotlin.String,

    /* file content */
    @SerializedName("filecontent")
    val filecontent: kotlin.String,

    /* file name */
    @SerializedName("filename")
    val filename: kotlin.String,

    /* file path */
    @SerializedName("filepath")
    val filepath: kotlin.String,

    /* associated id */
    @SerializedName("itemid")
    val itemid: kotlin.Int,

    /* context id */
    @SerializedName("contextid")
    val contextid: kotlin.Int? = null,

    /* The context level to put the file in,                         (block, course, coursecat, system, user, module) */
    @SerializedName("contextlevel")
    val contextlevel: kotlin.String? = null,

    /* The Instance id of item associated                          with the context level */
    @SerializedName("instanceid")
    val instanceid: kotlin.Int? = null

) {


}

