/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param conversationid The id of the conversation
 * @param fullname The user's name
 * @param isblocked If the user has been blocked
 * @param ismessaging If we are messaging the user
 * @param isonline The user's online status
 * @param isread If the user has read the message
 * @param lastmessage The user's last message
 * @param lastmessagedate Timestamp for last message
 * @param messageid The unique search message id
 * @param profileimageurl User picture URL
 * @param profileimageurlsmall Small user picture URL
 * @param sentfromcurrentuser Was the last message sent from the current user?
 * @param showonlinestatus Show the user's online status?
 * @param unreadcount The number of unread messages in this conversation
 * @param userid The user's id
 */


data class ElearningCoreMessageDataForMessageareaSearchMessages200ResponseContactsInner (

    /* The id of the conversation */
    @SerializedName("conversationid")
    val conversationid: kotlin.Int? = null,

    /* The user's name */
    @SerializedName("fullname")
    val fullname: kotlin.String? = null,

    /* If the user has been blocked */
    @SerializedName("isblocked")
    val isblocked: kotlin.Boolean? = null,

    /* If we are messaging the user */
    @SerializedName("ismessaging")
    val ismessaging: kotlin.Boolean? = null,

    /* The user's online status */
    @SerializedName("isonline")
    val isonline: kotlin.Boolean? = null,

    /* If the user has read the message */
    @SerializedName("isread")
    val isread: kotlin.Boolean? = null,

    /* The user's last message */
    @SerializedName("lastmessage")
    val lastmessage: kotlin.String? = null,

    /* Timestamp for last message */
    @SerializedName("lastmessagedate")
    val lastmessagedate: kotlin.Int? = null,

    /* The unique search message id */
    @SerializedName("messageid")
    val messageid: kotlin.Int? = null,

    /* User picture URL */
    @SerializedName("profileimageurl")
    val profileimageurl: kotlin.String? = null,

    /* Small user picture URL */
    @SerializedName("profileimageurlsmall")
    val profileimageurlsmall: kotlin.String? = null,

    /* Was the last message sent from the current user? */
    @SerializedName("sentfromcurrentuser")
    val sentfromcurrentuser: kotlin.Boolean? = null,

    /* Show the user's online status? */
    @SerializedName("showonlinestatus")
    val showonlinestatus: kotlin.Boolean? = null,

    /* The number of unread messages in this conversation */
    @SerializedName("unreadcount")
    val unreadcount: kotlin.Int? = null,

    /* The user's id */
    @SerializedName("userid")
    val userid: kotlin.Int? = null

) {


}

