/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param allocatedmarker allocated marker
 * @param extensionduedate extension due date
 * @param id user flag id
 * @param locked locked
 * @param mailed mailed
 * @param userid student id
 * @param workflowstate marking workflow state
 */


data class ElearningModAssignGetUserFlags200ResponseAssignmentsInnerUserflagsInner (

    /* allocated marker */
    @SerializedName("allocatedmarker")
    val allocatedmarker: kotlin.Int? = null,

    /* extension due date */
    @SerializedName("extensionduedate")
    val extensionduedate: kotlin.Int? = null,

    /* user flag id */
    @SerializedName("id")
    val id: kotlin.Int? = null,

    /* locked */
    @SerializedName("locked")
    val locked: kotlin.Int? = null,

    /* mailed */
    @SerializedName("mailed")
    val mailed: kotlin.Int? = null,

    /* student id */
    @SerializedName("userid")
    val userid: kotlin.Int? = null,

    /* marking workflow state */
    @SerializedName("workflowstate")
    val workflowstate: kotlin.String? = null

) {


}

