/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningAuthEmailSignupUser200ResponseWarningsInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param canaddinstance Whether the user has the capability mod/h5pactivity:addinstance allowed.
 * @param canreviewattempts Whether the user has the capability mod/h5pactivity:reviewattempts allowed.
 * @param cansubmit Whether the user has the capability mod/h5pactivity:submit allowed.
 * @param canview Whether the user has the capability mod/h5pactivity:view allowed.
 * @param warnings 
 */


data class ElearningModH5pactivityGetH5pactivityAccessInformation200Response (

    /* Whether the user has the capability mod/h5pactivity:addinstance allowed. */
    @SerializedName("canaddinstance")
    val canaddinstance: kotlin.Boolean? = null,

    /* Whether the user has the capability mod/h5pactivity:reviewattempts allowed. */
    @SerializedName("canreviewattempts")
    val canreviewattempts: kotlin.Boolean? = null,

    /* Whether the user has the capability mod/h5pactivity:submit allowed. */
    @SerializedName("cansubmit")
    val cansubmit: kotlin.Boolean? = null,

    /* Whether the user has the capability mod/h5pactivity:view allowed. */
    @SerializedName("canview")
    val canview: kotlin.Boolean? = null,

    @SerializedName("warnings")
    val warnings: kotlin.collections.List<ElearningAuthEmailSignupUser200ResponseWarningsInner>? = null

) {


}

