/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param userid the user whose blocked users we want to retrieve
 */


data class ElearningCoreMessageGetBlockedUsersRequest (

    /* the user whose blocked users we want to retrieve */
    @SerializedName("userid")
    val userid: kotlin.Int

) {


}

