/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningAuthEmailSignupUser200ResponseWarningsInner
import org.openapitools.client.models.ElearningCoreTagGetTagCollections200ResponseCollectionsInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param collections 
 * @param warnings 
 */


data class ElearningCoreTagGetTagCollections200Response (

    @SerializedName("collections")
    val collections: kotlin.collections.List<ElearningCoreTagGetTagCollections200ResponseCollectionsInner>,

    @SerializedName("warnings")
    val warnings: kotlin.collections.List<ElearningAuthEmailSignupUser200ResponseWarningsInner>? = null

) {


}

