/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningAuthEmailSignupUser200ResponseWarningsInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param status status: true if the assessment was added or updated false otherwise.
 * @param rawgrade Raw percentual grade (0.00000 to 100.00000) for submission.
 * @param warnings 
 */


data class ElearningModWorkshopUpdateAssessment200Response (

    /* status: true if the assessment was added or updated false otherwise. */
    @SerializedName("status")
    val status: kotlin.Boolean,

    /* Raw percentual grade (0.00000 to 100.00000) for submission. */
    @SerializedName("rawgrade")
    val rawgrade: java.math.BigDecimal? = null,

    @SerializedName("warnings")
    val warnings: kotlin.collections.List<ElearningAuthEmailSignupUser200ResponseWarningsInner>? = null

) {


}

