/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningModQuizGetAttemptDataRequestPreflightdataInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param quizid quiz instance id
 * @param forcenew Whether to force a new attempt or not.
 * @param preflightdata 
 */


data class ElearningModQuizStartAttemptRequest (

    /* quiz instance id */
    @SerializedName("quizid")
    val quizid: kotlin.Int,

    /* Whether to force a new attempt or not. */
    @SerializedName("forcenew")
    val forcenew: kotlin.Boolean? = false,

    @SerializedName("preflightdata")
    val preflightdata: kotlin.collections.List<ElearningModQuizGetAttemptDataRequestPreflightdataInner>? = null

) {


}

