/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param contextid The context to assign the user role in
 * @param contextlevel The context level to assign the user role in                                     (block, course, coursecat, system, user, module)
 * @param instanceid The Instance id of item where the role needs to be assigned
 * @param roleid Role to assign to the user
 * @param userid The user that is going to be assigned
 */


data class ElearningCoreRoleAssignRolesRequestAssignmentsInner (

    /* The context to assign the user role in */
    @SerializedName("contextid")
    val contextid: kotlin.Int? = null,

    /* The context level to assign the user role in                                     (block, course, coursecat, system, user, module) */
    @SerializedName("contextlevel")
    val contextlevel: kotlin.String? = null,

    /* The Instance id of item where the role needs to be assigned */
    @SerializedName("instanceid")
    val instanceid: kotlin.Int? = null,

    /* Role to assign to the user */
    @SerializedName("roleid")
    val roleid: kotlin.Int? = null,

    /* The user that is going to be assigned */
    @SerializedName("userid")
    val userid: kotlin.Int? = null

) {


}

