/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningAuthEmailSignupUser200ResponseWarningsInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param groupmode group mode:                                                     0 for no groups, 1 for separate groups, 2 for visible groups
 * @param warnings 
 */


data class ElearningCoreGroupGetActivityGroupmode200Response (

    /* group mode:                                                     0 for no groups, 1 for separate groups, 2 for visible groups */
    @SerializedName("groupmode")
    val groupmode: kotlin.Int,

    @SerializedName("warnings")
    val warnings: kotlin.collections.List<ElearningAuthEmailSignupUser200ResponseWarningsInner>? = null

) {


}

