/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * message
 *
 * @param component The component that generated the notification
 * @param contexturl Context URL
 * @param contexturlname Context URL link name
 * @param customdata Custom data to be passed to the message processor.                                 The data here is serialised using json_encode().
 * @param deleted notification deletion status
 * @param eventtype The type of notification
 * @param fullmessage The message
 * @param fullmessageformat fullmessage format (1 = HTML, 0 = MOODLE, 2 = PLAIN, or 4 = MARKDOWN)
 * @param fullmessagehtml The message in html
 * @param iconurl URL for notification icon
 * @param id Notification id (this is not guaranteed to be unique                                 within this result set)
 * @param read notification read status
 * @param shortenedsubject The notification subject shortened                                 with ellipsis
 * @param smallmessage The shorten message
 * @param subject The notification subject
 * @param text The message text formated
 * @param timecreated Time created
 * @param timecreatedpretty Time created in a pretty format
 * @param timeread Time read
 * @param useridfrom User from id
 * @param useridto User to id
 */


data class ElearningMessagePopupGetPopupNotifications200ResponseNotificationsInner (

    /* The component that generated the notification */
    @SerializedName("component")
    val component: kotlin.String? = null,

    /* Context URL */
    @SerializedName("contexturl")
    val contexturl: kotlin.String? = null,

    /* Context URL link name */
    @SerializedName("contexturlname")
    val contexturlname: kotlin.String? = null,

    /* Custom data to be passed to the message processor.                                 The data here is serialised using json_encode(). */
    @SerializedName("customdata")
    val customdata: kotlin.String? = null,

    /* notification deletion status */
    @SerializedName("deleted")
    val deleted: kotlin.Boolean? = null,

    /* The type of notification */
    @SerializedName("eventtype")
    val eventtype: kotlin.String? = null,

    /* The message */
    @SerializedName("fullmessage")
    val fullmessage: kotlin.String? = null,

    /* fullmessage format (1 = HTML, 0 = MOODLE, 2 = PLAIN, or 4 = MARKDOWN) */
    @SerializedName("fullmessageformat")
    val fullmessageformat: kotlin.Int? = null,

    /* The message in html */
    @SerializedName("fullmessagehtml")
    val fullmessagehtml: kotlin.String? = null,

    /* URL for notification icon */
    @SerializedName("iconurl")
    val iconurl: kotlin.String? = null,

    /* Notification id (this is not guaranteed to be unique                                 within this result set) */
    @SerializedName("id")
    val id: kotlin.Int? = null,

    /* notification read status */
    @SerializedName("read")
    val read: kotlin.Boolean? = null,

    /* The notification subject shortened                                 with ellipsis */
    @SerializedName("shortenedsubject")
    val shortenedsubject: kotlin.String? = null,

    /* The shorten message */
    @SerializedName("smallmessage")
    val smallmessage: kotlin.String? = null,

    /* The notification subject */
    @SerializedName("subject")
    val subject: kotlin.String? = null,

    /* The message text formated */
    @SerializedName("text")
    val text: kotlin.String? = null,

    /* Time created */
    @SerializedName("timecreated")
    val timecreated: kotlin.Int? = null,

    /* Time created in a pretty format */
    @SerializedName("timecreatedpretty")
    val timecreatedpretty: kotlin.String? = null,

    /* Time read */
    @SerializedName("timeread")
    val timeread: kotlin.Int? = null,

    /* User from id */
    @SerializedName("useridfrom")
    val useridfrom: kotlin.Int? = null,

    /* User to id */
    @SerializedName("useridto")
    val useridto: kotlin.Int? = null

) {


}

