/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param lessonid lesson instance id
 * @param pageid the page id
 * @param password optional password (the lesson may be protected)
 * @param returncontents if we must return the complete page contents once rendered
 * @param review if we want to review just after finishing (1 hour margin)
 */


data class ElearningModLessonGetPageDataRequest (

    /* lesson instance id */
    @SerializedName("lessonid")
    val lessonid: kotlin.Int,

    /* the page id */
    @SerializedName("pageid")
    val pageid: kotlin.Int,

    /* optional password (the lesson may be protected) */
    @SerializedName("password")
    val password: kotlin.String? = "",

    /* if we must return the complete page contents once rendered */
    @SerializedName("returncontents")
    val returncontents: kotlin.Boolean? = false,

    /* if we want to review just after finishing (1 hour margin) */
    @SerializedName("review")
    val review: kotlin.Boolean? = false

) {


}

