/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param competencyid Data base record id for the competency
 * @param userid Data base record id for the user
 */


data class ElearningToolLpDataForUserCompetencySummaryRequest (

    /* Data base record id for the competency */
    @SerializedName("competencyid")
    val competencyid: kotlin.Int,

    /* Data base record id for the user */
    @SerializedName("userid")
    val userid: kotlin.Int

) {


}

