/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningCoreUserGetCourseUserProfilesRequestUserlistInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param userlist 
 */


data class ElearningCoreUserGetCourseUserProfilesRequest (

    @SerializedName("userlist")
    val userlist: kotlin.collections.List<ElearningCoreUserGetCourseUserProfilesRequestUserlistInner>

) {


}

