/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param discussionid The discussion to subscribe or unsubscribe
 * @param forumid Forum that the discussion is in
 * @param targetstate The target state
 */


data class ElearningModForumSetSubscriptionStateRequest (

    /* The discussion to subscribe or unsubscribe */
    @SerializedName("discussionid")
    val discussionid: kotlin.Int,

    /* Forum that the discussion is in */
    @SerializedName("forumid")
    val forumid: kotlin.Int,

    /* The target state */
    @SerializedName("targetstate")
    val targetstate: kotlin.Boolean

) {


}

