/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * Copy data
 *
 * @param backupid Backup id
 * @param operation Operation type
 * @param restoreid Restore id
 */


data class ElearningCoreBackupGetCopyProgressRequestCopiesInner (

    /* Backup id */
    @SerializedName("backupid")
    val backupid: kotlin.String? = null,

    /* Operation type */
    @SerializedName("operation")
    val operation: kotlin.String? = null,

    /* Restore id */
    @SerializedName("restoreid")
    val restoreid: kotlin.String? = null

) {


}

