/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param canJoin Can join session
 * @param cmid course module id
 */


data class ElearningModBigbluebuttonbnCanJoin200Response (

    /* Can join session */
    @SerializedName("can_join")
    val canJoin: kotlin.Boolean,

    /* course module id */
    @SerializedName("cmid")
    val cmid: kotlin.Int

) {


}

