/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param nodefaults Whether to fetch all activities or only those without defaults
 */


data class ElearningToolDataprivacyGetActivityOptionsRequest (

    /* Whether to fetch all activities or only those without defaults */
    @SerializedName("nodefaults")
    val nodefaults: kotlin.Boolean? = false

) {


}

