/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningBlockIomadCompanyAdminEditCompaniesRequestCompaniesInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param companies 
 */


data class ElearningBlockIomadCompanyAdminEditCompaniesRequest (

    @SerializedName("companies")
    val companies: kotlin.collections.List<ElearningBlockIomadCompanyAdminEditCompaniesRequestCompaniesInner>

) {


}

