/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param name course format option name
 * @param `value` course format option value
 */


data class ElearningCoreCourseUpdateCoursesRequestCoursesInnerCourseformatoptionsInner (

    /* course format option name */
    @SerializedName("name")
    val name: kotlin.String? = null,

    /* course format option value */
    @SerializedName("value")
    val `value`: kotlin.String? = null

) {


}

