/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningModAssignGetSubmissionStatus200ResponseFeedbackPluginsInnerEditorfieldsInner
import org.openapitools.client.models.ElearningModAssignGetSubmissionStatus200ResponseFeedbackPluginsInnerFileareasInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param editorfields 
 * @param fileareas 
 * @param name submission plugin name
 * @param type submission plugin type
 */


data class ElearningModAssignGetSubmissionStatus200ResponseFeedbackPluginsInner (

    @SerializedName("editorfields")
    val editorfields: kotlin.collections.List<ElearningModAssignGetSubmissionStatus200ResponseFeedbackPluginsInnerEditorfieldsInner>? = null,

    @SerializedName("fileareas")
    val fileareas: kotlin.collections.List<ElearningModAssignGetSubmissionStatus200ResponseFeedbackPluginsInnerFileareasInner>? = null,

    /* submission plugin name */
    @SerializedName("name")
    val name: kotlin.String? = null,

    /* submission plugin type */
    @SerializedName("type")
    val type: kotlin.String? = null

) {


}

