/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningCoreCourseGetUserNavigationOptions200ResponseCoursesInnerOptionsInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id Course id
 * @param options 
 */


data class ElearningCoreCourseGetUserNavigationOptions200ResponseCoursesInner (

    /* Course id */
    @SerializedName("id")
    val id: kotlin.Int? = null,

    @SerializedName("options")
    val options: kotlin.collections.List<ElearningCoreCourseGetUserNavigationOptions200ResponseCoursesInnerOptionsInner>? = null

) {


}

