/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param name preference name, empty for all
 * @param userid id of the user, default to current user
 */


data class ElearningCoreUserGetUserPreferencesRequest (

    /* preference name, empty for all */
    @SerializedName("name")
    val name: kotlin.String? = "",

    /* id of the user, default to current user */
    @SerializedName("userid")
    val userid: kotlin.Int? = 0

) {


}

