/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param workshopid Workshop instance id.
 * @param userid User id (empty or 0 for current user).
 */


data class ElearningModWorkshopGetUserPlanRequest (

    /* Workshop instance id. */
    @SerializedName("workshopid")
    val workshopid: kotlin.Int,

    /* User id (empty or 0 for current user). */
    @SerializedName("userid")
    val userid: kotlin.Int? = 0

) {


}

