/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningAuthEmailSignupUser200ResponseWarningsInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param formattedgrade The lesson final grade formatted
 * @param grade The lesson final raw grade
 * @param warnings 
 */


data class ElearningModLessonGetUserGrade200Response (

    /* The lesson final grade formatted */
    @SerializedName("formattedgrade")
    val formattedgrade: kotlin.String,

    /* The lesson final raw grade */
    @SerializedName("grade")
    val grade: java.math.BigDecimal,

    @SerializedName("warnings")
    val warnings: kotlin.collections.List<ElearningAuthEmailSignupUser200ResponseWarningsInner>? = null

) {


}

