/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param discussionid The ID of the discussion from which to fetch posts.
 * @param includeinlineattachments Whether inline attachments should be included or not
 * @param sortby Sort by this element: id, created or modified
 * @param sortdirection Sort direction: ASC or DESC
 */


data class ElearningModForumGetDiscussionPostsRequest (

    /* The ID of the discussion from which to fetch posts. */
    @SerializedName("discussionid")
    val discussionid: kotlin.Int,

    /* Whether inline attachments should be included or not */
    @SerializedName("includeinlineattachments")
    val includeinlineattachments: kotlin.Boolean? = false,

    /* Sort by this element: id, created or modified */
    @SerializedName("sortby")
    val sortby: kotlin.String? = "created",

    /* Sort direction: ASC or DESC */
    @SerializedName("sortdirection")
    val sortdirection: kotlin.String? = "DESC"

) {


}

