/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param status True if the user is considered to be a digital minor,                     false if not
 */


data class ElearningCoreAuthIsMinor200Response (

    /* True if the user is considered to be a digital minor,                     false if not */
    @SerializedName("status")
    val status: kotlin.Boolean

) {


}

