/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param action The action taken by user
 * @param contextid The context id of the page the user is in
 */


data class ElearningCoreCreateUserfeedbackActionRecordRequest (

    /* The action taken by user */
    @SerializedName("action")
    val action: kotlin.String,

    /* The context id of the page the user is in */
    @SerializedName("contextid")
    val contextid: kotlin.Int

) {


}

