/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningCoreCohortSearchCohortsRequestContext

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param context 
 * @param query Query string
 * @param includes What other contexts to fetch the frameworks from. (all, parents, self)
 * @param limitfrom limitfrom we are fetching the records from
 * @param limitnum Number of records to fetch
 */


data class ElearningToolLpSearchCohortsRequest (

    @SerializedName("context")
    val context: ElearningCoreCohortSearchCohortsRequestContext,

    /* Query string */
    @SerializedName("query")
    val query: kotlin.String,

    /* What other contexts to fetch the frameworks from. (all, parents, self) */
    @SerializedName("includes")
    val includes: kotlin.String? = "parents",

    /* limitfrom we are fetching the records from */
    @SerializedName("limitfrom")
    val limitfrom: kotlin.Int? = 0,

    /* Number of records to fetch */
    @SerializedName("limitnum")
    val limitnum: kotlin.Int? = 25

) {


}

