/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param requestid The request ID
 */


data class ElearningToolDataprivacyApproveDataRequestRequest (

    /* The request ID */
    @SerializedName("requestid")
    val requestid: kotlin.Int

) {


}

