/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param description the new category description
 * @param descriptionformat description format (1 = HTML, 0 = MOODLE, 2 = PLAIN, or 4 = MARKDOWN)
 * @param idnumber the new category idnumber
 * @param name new category name
 * @param parent the parent category id inside which the new category will be created                                          - set to 0 for a root category
 * @param theme the new category theme. This option must be enabled on moodle
 */


data class ElearningCoreCourseCreateCategoriesRequestCategoriesInner (

    /* the new category description */
    @SerializedName("description")
    val description: kotlin.String? = null,

    /* description format (1 = HTML, 0 = MOODLE, 2 = PLAIN, or 4 = MARKDOWN) */
    @SerializedName("descriptionformat")
    val descriptionformat: kotlin.Int? = 1,

    /* the new category idnumber */
    @SerializedName("idnumber")
    val idnumber: kotlin.String? = null,

    /* new category name */
    @SerializedName("name")
    val name: kotlin.String? = null,

    /* the parent category id inside which the new category will be created                                          - set to 0 for a root category */
    @SerializedName("parent")
    val parent: kotlin.Int? = 0,

    /* the new category theme. This option must be enabled on moodle */
    @SerializedName("theme")
    val theme: kotlin.String? = null

) {


}

