/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param propertyClass class
 * @param content cell content
 * @param headers headers
 */


data class ElearningGradereportUserGetGradesTable200ResponseTablesInnerTabledataInnerContributiontocoursetotal (

    /* class */
    @SerializedName("class")
    val propertyClass: kotlin.String,

    /* cell content */
    @SerializedName("content")
    val content: kotlin.String,

    /* headers */
    @SerializedName("headers")
    val headers: kotlin.String

) {


}

