/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param bigbluebuttonbnid bigbluebuttonbn instance id
 * @param groupid bigbluebuttonbn group id
 * @param updatecache update cache ?
 */


data class ElearningModBigbluebuttonbnMeetingInfoRequest (

    /* bigbluebuttonbn instance id */
    @SerializedName("bigbluebuttonbnid")
    val bigbluebuttonbnid: kotlin.Int,

    /* bigbluebuttonbn group id */
    @SerializedName("groupid")
    val groupid: kotlin.Int? = 0,

    /* update cache ? */
    @SerializedName("updatecache")
    val updatecache: kotlin.Boolean? = false

) {


}

