/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningAuthEmailSignupUser200ResponseWarningsInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param canaddinstance Whether the user has the capability mod/forum:addinstance allowed.
 * @param canaddnews Whether the user has the capability mod/forum:addnews allowed.
 * @param canaddquestion Whether the user has the capability mod/forum:addquestion allowed.
 * @param canallowforcesubscribe Whether the user has the capability mod/forum:allowforcesubscribe allowed.
 * @param cancanmailnow Whether the user has the capability mod/forum:canmailnow allowed.
 * @param cancanoverridecutoff Whether the user has the capability mod/forum:canoverridecutoff allowed.
 * @param cancanoverridediscussionlock Whether the user has the capability mod/forum:canoverridediscussionlock allowed.
 * @param cancanposttomygroups Whether the user has the capability mod/forum:canposttomygroups allowed.
 * @param cancantogglefavourite Whether the user has the capability mod/forum:cantogglefavourite allowed.
 * @param cancreateattachment Whether the user has the capability mod/forum:createattachment allowed.
 * @param candeleteanypost Whether the user has the capability mod/forum:deleteanypost allowed.
 * @param candeleteownpost Whether the user has the capability mod/forum:deleteownpost allowed.
 * @param caneditanypost Whether the user has the capability mod/forum:editanypost allowed.
 * @param canexportdiscussion Whether the user has the capability mod/forum:exportdiscussion allowed.
 * @param canexportforum Whether the user has the capability mod/forum:exportforum allowed.
 * @param canexportownpost Whether the user has the capability mod/forum:exportownpost allowed.
 * @param canexportpost Whether the user has the capability mod/forum:exportpost allowed.
 * @param cangrade Whether the user has the capability mod/forum:grade allowed.
 * @param canmanagesubscriptions Whether the user has the capability mod/forum:managesubscriptions allowed.
 * @param canmovediscussions Whether the user has the capability mod/forum:movediscussions allowed.
 * @param canpindiscussions Whether the user has the capability mod/forum:pindiscussions allowed.
 * @param canpostprivatereply Whether the user has the capability mod/forum:postprivatereply allowed.
 * @param canpostwithoutthrottling Whether the user has the capability mod/forum:postwithoutthrottling allowed.
 * @param canrate Whether the user has the capability mod/forum:rate allowed.
 * @param canreadprivatereplies Whether the user has the capability mod/forum:readprivatereplies allowed.
 * @param canreplynews Whether the user has the capability mod/forum:replynews allowed.
 * @param canreplypost Whether the user has the capability mod/forum:replypost allowed.
 * @param cansplitdiscussions Whether the user has the capability mod/forum:splitdiscussions allowed.
 * @param canstartdiscussion Whether the user has the capability mod/forum:startdiscussion allowed.
 * @param canviewallratings Whether the user has the capability mod/forum:viewallratings allowed.
 * @param canviewanyrating Whether the user has the capability mod/forum:viewanyrating allowed.
 * @param canviewdiscussion Whether the user has the capability mod/forum:viewdiscussion allowed.
 * @param canviewhiddentimedposts Whether the user has the capability mod/forum:viewhiddentimedposts allowed.
 * @param canviewqandawithoutposting Whether the user has the capability mod/forum:viewqandawithoutposting allowed.
 * @param canviewrating Whether the user has the capability mod/forum:viewrating allowed.
 * @param canviewsubscribers Whether the user has the capability mod/forum:viewsubscribers allowed.
 * @param warnings 
 */


data class ElearningModForumGetForumAccessInformation200Response (

    /* Whether the user has the capability mod/forum:addinstance allowed. */
    @SerializedName("canaddinstance")
    val canaddinstance: kotlin.Boolean? = null,

    /* Whether the user has the capability mod/forum:addnews allowed. */
    @SerializedName("canaddnews")
    val canaddnews: kotlin.Boolean? = null,

    /* Whether the user has the capability mod/forum:addquestion allowed. */
    @SerializedName("canaddquestion")
    val canaddquestion: kotlin.Boolean? = null,

    /* Whether the user has the capability mod/forum:allowforcesubscribe allowed. */
    @SerializedName("canallowforcesubscribe")
    val canallowforcesubscribe: kotlin.Boolean? = null,

    /* Whether the user has the capability mod/forum:canmailnow allowed. */
    @SerializedName("cancanmailnow")
    val cancanmailnow: kotlin.Boolean? = null,

    /* Whether the user has the capability mod/forum:canoverridecutoff allowed. */
    @SerializedName("cancanoverridecutoff")
    val cancanoverridecutoff: kotlin.Boolean? = null,

    /* Whether the user has the capability mod/forum:canoverridediscussionlock allowed. */
    @SerializedName("cancanoverridediscussionlock")
    val cancanoverridediscussionlock: kotlin.Boolean? = null,

    /* Whether the user has the capability mod/forum:canposttomygroups allowed. */
    @SerializedName("cancanposttomygroups")
    val cancanposttomygroups: kotlin.Boolean? = null,

    /* Whether the user has the capability mod/forum:cantogglefavourite allowed. */
    @SerializedName("cancantogglefavourite")
    val cancantogglefavourite: kotlin.Boolean? = null,

    /* Whether the user has the capability mod/forum:createattachment allowed. */
    @SerializedName("cancreateattachment")
    val cancreateattachment: kotlin.Boolean? = null,

    /* Whether the user has the capability mod/forum:deleteanypost allowed. */
    @SerializedName("candeleteanypost")
    val candeleteanypost: kotlin.Boolean? = null,

    /* Whether the user has the capability mod/forum:deleteownpost allowed. */
    @SerializedName("candeleteownpost")
    val candeleteownpost: kotlin.Boolean? = null,

    /* Whether the user has the capability mod/forum:editanypost allowed. */
    @SerializedName("caneditanypost")
    val caneditanypost: kotlin.Boolean? = null,

    /* Whether the user has the capability mod/forum:exportdiscussion allowed. */
    @SerializedName("canexportdiscussion")
    val canexportdiscussion: kotlin.Boolean? = null,

    /* Whether the user has the capability mod/forum:exportforum allowed. */
    @SerializedName("canexportforum")
    val canexportforum: kotlin.Boolean? = null,

    /* Whether the user has the capability mod/forum:exportownpost allowed. */
    @SerializedName("canexportownpost")
    val canexportownpost: kotlin.Boolean? = null,

    /* Whether the user has the capability mod/forum:exportpost allowed. */
    @SerializedName("canexportpost")
    val canexportpost: kotlin.Boolean? = null,

    /* Whether the user has the capability mod/forum:grade allowed. */
    @SerializedName("cangrade")
    val cangrade: kotlin.Boolean? = null,

    /* Whether the user has the capability mod/forum:managesubscriptions allowed. */
    @SerializedName("canmanagesubscriptions")
    val canmanagesubscriptions: kotlin.Boolean? = null,

    /* Whether the user has the capability mod/forum:movediscussions allowed. */
    @SerializedName("canmovediscussions")
    val canmovediscussions: kotlin.Boolean? = null,

    /* Whether the user has the capability mod/forum:pindiscussions allowed. */
    @SerializedName("canpindiscussions")
    val canpindiscussions: kotlin.Boolean? = null,

    /* Whether the user has the capability mod/forum:postprivatereply allowed. */
    @SerializedName("canpostprivatereply")
    val canpostprivatereply: kotlin.Boolean? = null,

    /* Whether the user has the capability mod/forum:postwithoutthrottling allowed. */
    @SerializedName("canpostwithoutthrottling")
    val canpostwithoutthrottling: kotlin.Boolean? = null,

    /* Whether the user has the capability mod/forum:rate allowed. */
    @SerializedName("canrate")
    val canrate: kotlin.Boolean? = null,

    /* Whether the user has the capability mod/forum:readprivatereplies allowed. */
    @SerializedName("canreadprivatereplies")
    val canreadprivatereplies: kotlin.Boolean? = null,

    /* Whether the user has the capability mod/forum:replynews allowed. */
    @SerializedName("canreplynews")
    val canreplynews: kotlin.Boolean? = null,

    /* Whether the user has the capability mod/forum:replypost allowed. */
    @SerializedName("canreplypost")
    val canreplypost: kotlin.Boolean? = null,

    /* Whether the user has the capability mod/forum:splitdiscussions allowed. */
    @SerializedName("cansplitdiscussions")
    val cansplitdiscussions: kotlin.Boolean? = null,

    /* Whether the user has the capability mod/forum:startdiscussion allowed. */
    @SerializedName("canstartdiscussion")
    val canstartdiscussion: kotlin.Boolean? = null,

    /* Whether the user has the capability mod/forum:viewallratings allowed. */
    @SerializedName("canviewallratings")
    val canviewallratings: kotlin.Boolean? = null,

    /* Whether the user has the capability mod/forum:viewanyrating allowed. */
    @SerializedName("canviewanyrating")
    val canviewanyrating: kotlin.Boolean? = null,

    /* Whether the user has the capability mod/forum:viewdiscussion allowed. */
    @SerializedName("canviewdiscussion")
    val canviewdiscussion: kotlin.Boolean? = null,

    /* Whether the user has the capability mod/forum:viewhiddentimedposts allowed. */
    @SerializedName("canviewhiddentimedposts")
    val canviewhiddentimedposts: kotlin.Boolean? = null,

    /* Whether the user has the capability mod/forum:viewqandawithoutposting allowed. */
    @SerializedName("canviewqandawithoutposting")
    val canviewqandawithoutposting: kotlin.Boolean? = null,

    /* Whether the user has the capability mod/forum:viewrating allowed. */
    @SerializedName("canviewrating")
    val canviewrating: kotlin.Boolean? = null,

    /* Whether the user has the capability mod/forum:viewsubscribers allowed. */
    @SerializedName("canviewsubscribers")
    val canviewsubscribers: kotlin.Boolean? = null,

    @SerializedName("warnings")
    val warnings: kotlin.collections.List<ElearningAuthEmailSignupUser200ResponseWarningsInner>? = null

) {


}

