/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningModH5pactivityGetResults200ResponseAttemptsInnerResultsInnerOptionsInner

import com.google.gson.annotations.SerializedName

/**
 * A single result statement tracking information
 *
 * @param answerlabel Label used for user answers
 * @param attemptid ID of the H5P attempt
 * @param completion Result completion
 * @param content Result extra content
 * @param correctlabel Label used for correct answers
 * @param description Result description
 * @param duration Result duration in seconds
 * @param id ID of the context
 * @param interactiontype Interaction type
 * @param maxscore Result max score
 * @param options 
 * @param optionslabel Label used for result options
 * @param rawscore Result score value
 * @param subcontent Subcontent identifier
 * @param success Result success
 * @param timecreated Result creation
 * @param track If the result has valid track information
 */


data class ElearningModH5pactivityGetResults200ResponseAttemptsInnerResultsInner (

    /* Label used for user answers */
    @SerializedName("answerlabel")
    val answerlabel: kotlin.String? = null,

    /* ID of the H5P attempt */
    @SerializedName("attemptid")
    val attemptid: kotlin.Int? = null,

    /* Result completion */
    @SerializedName("completion")
    val completion: kotlin.Int? = null,

    /* Result extra content */
    @SerializedName("content")
    val content: kotlin.String? = null,

    /* Label used for correct answers */
    @SerializedName("correctlabel")
    val correctlabel: kotlin.String? = null,

    /* Result description */
    @SerializedName("description")
    val description: kotlin.String? = null,

    /* Result duration in seconds */
    @SerializedName("duration")
    val duration: kotlin.Int? = 0,

    /* ID of the context */
    @SerializedName("id")
    val id: kotlin.Int? = null,

    /* Interaction type */
    @SerializedName("interactiontype")
    val interactiontype: kotlin.String? = null,

    /* Result max score */
    @SerializedName("maxscore")
    val maxscore: kotlin.Int? = null,

    @SerializedName("options")
    val options: kotlin.collections.List<ElearningModH5pactivityGetResults200ResponseAttemptsInnerResultsInnerOptionsInner>? = null,

    /* Label used for result options */
    @SerializedName("optionslabel")
    val optionslabel: kotlin.String? = null,

    /* Result score value */
    @SerializedName("rawscore")
    val rawscore: kotlin.Int? = null,

    /* Subcontent identifier */
    @SerializedName("subcontent")
    val subcontent: kotlin.String? = null,

    /* Result success */
    @SerializedName("success")
    val success: kotlin.Int? = null,

    /* Result creation */
    @SerializedName("timecreated")
    val timecreated: kotlin.Int? = null,

    /* If the result has valid track information */
    @SerializedName("track")
    val track: kotlin.Boolean? = null

) {


}

