/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param checked Selected flag
 * @param criterionid ID of the criterion this matches to
 * @param definition Definition of the level
 * @param id ID of level
 * @param score What this level is worth
 */


data class ElearningGradingformRubricGraderGradingpanelStore200ResponseGradeCriteriaInnerLevelsInner (

    /* Selected flag */
    @SerializedName("checked")
    val checked: kotlin.Boolean? = null,

    /* ID of the criterion this matches to */
    @SerializedName("criterionid")
    val criterionid: kotlin.Int? = null,

    /* Definition of the level */
    @SerializedName("definition")
    val definition: kotlin.String? = null,

    /* ID of level */
    @SerializedName("id")
    val id: kotlin.Int? = null,

    /* What this level is worth */
    @SerializedName("score")
    val score: kotlin.String? = null

) {


}

