/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param description description
 * @param descriptionformat description format (1 = HTML, 0 = MOODLE, 2 = PLAIN, or 4 = MARKDOWN)
 * @param descriptionmarkers markers description
 * @param descriptionmarkersformat descriptionmarkers format (1 = HTML, 0 = MOODLE, 2 = PLAIN, or 4 = MARKDOWN)
 * @param id criterion id
 * @param maxscore maximum score
 * @param shortname description
 * @param sortorder sortorder
 */


data class ElearningCoreGradingSaveDefinitionsRequestAreasInnerDefinitionsInnerGuideGuideCriteriaInner (

    /* description */
    @SerializedName("description")
    val description: kotlin.String? = null,

    /* description format (1 = HTML, 0 = MOODLE, 2 = PLAIN, or 4 = MARKDOWN) */
    @SerializedName("descriptionformat")
    val descriptionformat: kotlin.Int? = null,

    /* markers description */
    @SerializedName("descriptionmarkers")
    val descriptionmarkers: kotlin.String? = null,

    /* descriptionmarkers format (1 = HTML, 0 = MOODLE, 2 = PLAIN, or 4 = MARKDOWN) */
    @SerializedName("descriptionmarkersformat")
    val descriptionmarkersformat: kotlin.Int? = null,

    /* criterion id */
    @SerializedName("id")
    val id: kotlin.Int? = null,

    /* maximum score */
    @SerializedName("maxscore")
    val maxscore: java.math.BigDecimal? = null,

    /* description */
    @SerializedName("shortname")
    val shortname: kotlin.String? = null,

    /* sortorder */
    @SerializedName("sortorder")
    val sortorder: kotlin.Int? = null

) {


}

