/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningAuthEmailSignupUser200ResponseWarningsInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param version Latest version of the page.
 * @param content The contents of the page-section to be edited.
 * @param contentformat Format of the original content of the page.
 * @param warnings 
 */


data class ElearningModWikiGetPageForEditing200ResponsePagesection (

    /* Latest version of the page. */
    @SerializedName("version")
    val version: kotlin.Int,

    /* The contents of the page-section to be edited. */
    @SerializedName("content")
    val content: kotlin.String? = null,

    /* Format of the original content of the page. */
    @SerializedName("contentformat")
    val contentformat: kotlin.String? = null,

    @SerializedName("warnings")
    val warnings: kotlin.collections.List<ElearningAuthEmailSignupUser200ResponseWarningsInner>? = null

) {


}

