/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param courseid Course id
 * @param fullname User full name
 * @param started If the user has started the attempt
 * @param userid The user id
 */


data class ElearningModFeedbackGetNonRespondents200ResponseUsersInner (

    /* Course id */
    @SerializedName("courseid")
    val courseid: kotlin.Int? = null,

    /* User full name */
    @SerializedName("fullname")
    val fullname: kotlin.String? = null,

    /* If the user has started the attempt */
    @SerializedName("started")
    val started: kotlin.Boolean? = null,

    /* The user id */
    @SerializedName("userid")
    val userid: kotlin.Int? = null

) {


}

