/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param courseids 
 * @param pathid ID of Iomad Learning Path
 */


data class ElearningLocalIomadLearningpathRemovecoursesRequest (

    @SerializedName("courseids")
    val courseids: kotlin.collections.List<kotlin.Any>,

    /* ID of Iomad Learning Path */
    @SerializedName("pathid")
    val pathid: kotlin.Int

) {


}

