/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param assignmentid The assignment id to operate on
 * @param jsonformdata The data from the grading form, encoded as a json array
 * @param userid The user id the submission belongs to
 */


data class ElearningModAssignSubmitGradingFormRequest (

    /* The assignment id to operate on */
    @SerializedName("assignmentid")
    val assignmentid: kotlin.Int,

    /* The data from the grading form, encoded as a json array */
    @SerializedName("jsonformdata")
    val jsonformdata: kotlin.String,

    /* The user id the submission belongs to */
    @SerializedName("userid")
    val userid: kotlin.Int

) {


}

