/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param notificationid id of the notification
 * @param timeread timestamp for when the notification should be marked read
 */


data class ElearningCoreMessageMarkNotificationReadRequest (

    /* id of the notification */
    @SerializedName("notificationid")
    val notificationid: kotlin.Int,

    /* timestamp for when the notification should be marked read */
    @SerializedName("timeread")
    val timeread: kotlin.Int? = 0

) {


}

