/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningAuthEmailSignupUser200ResponseWarningsInner
import org.openapitools.client.models.ElearningToolDataprivacyCreatePurposeForm200ResponsePurpose

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param purpose 
 * @param validationerrors Were there validation errors
 * @param warnings 
 */


data class ElearningToolDataprivacyCreatePurposeForm200Response (

    @SerializedName("purpose")
    val purpose: ElearningToolDataprivacyCreatePurposeForm200ResponsePurpose,

    /* Were there validation errors */
    @SerializedName("validationerrors")
    val validationerrors: kotlin.Boolean,

    @SerializedName("warnings")
    val warnings: kotlin.collections.List<ElearningAuthEmailSignupUser200ResponseWarningsInner>? = null

) {


}

