/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param courseid id of the course
 * @param userid id of the user, 0 means current user
 */


data class ElearningGradereportOverviewViewGradeReportRequest (

    /* id of the course */
    @SerializedName("courseid")
    val courseid: kotlin.Int,

    /* id of the user, 0 means current user */
    @SerializedName("userid")
    val userid: kotlin.Int? = 0

) {


}

