/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningModAssignGetGrades200ResponseAssignmentsInner
import org.openapitools.client.models.ElearningModAssignGetGrades200ResponseWarningsInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param assignments 
 * @param warnings 
 */


data class ElearningModAssignGetGrades200Response (

    @SerializedName("assignments")
    val assignments: kotlin.collections.List<ElearningModAssignGetGrades200ResponseAssignmentsInner>,

    @SerializedName("warnings")
    val warnings: kotlin.collections.List<ElearningModAssignGetGrades200ResponseWarningsInner>? = null

) {


}

