/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param fullname User full name
 * @param id User ID
 * @param profileimageurl User picture URL
 */


data class ElearningCoreMessageGetBlockedUsers200ResponseUsersInner (

    /* User full name */
    @SerializedName("fullname")
    val fullname: kotlin.String? = null,

    /* User ID */
    @SerializedName("id")
    val id: kotlin.Int? = null,

    /* User picture URL */
    @SerializedName("profileimageurl")
    val profileimageurl: kotlin.String? = null

) {


}

