/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param code Certificate code
 * @param filename Time created
 * @param fileurl Time created
 * @param grade Certificate grade
 * @param id Issue id
 * @param iomadcertificateid Certificate id
 * @param mimetype mime type
 * @param timecreated Time created
 * @param userid User id
 */


data class ElearningModIomadcertificateGetIssuedIomadcertificates200ResponseIssuesInner (

    /* Certificate code */
    @SerializedName("code")
    val code: kotlin.String? = null,

    /* Time created */
    @SerializedName("filename")
    val filename: kotlin.String? = null,

    /* Time created */
    @SerializedName("fileurl")
    val fileurl: kotlin.String? = null,

    /* Certificate grade */
    @SerializedName("grade")
    val grade: kotlin.String? = null,

    /* Issue id */
    @SerializedName("id")
    val id: kotlin.Int? = null,

    /* Certificate id */
    @SerializedName("iomadcertificateid")
    val iomadcertificateid: kotlin.Int? = null,

    /* mime type */
    @SerializedName("mimetype")
    val mimetype: kotlin.String? = null,

    /* Time created */
    @SerializedName("timecreated")
    val timecreated: kotlin.Int? = null,

    /* User id */
    @SerializedName("userid")
    val userid: kotlin.Int? = null

) {


}

