/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningAuthEmailSignupUser200ResponseWarningsInner
import org.openapitools.client.models.ElearningModWorkshopGetSubmissions200ResponseSubmissionsInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param submissions 
 * @param totalcount Total count of submissions.
 * @param totalfilesize Total size (bytes) of the files attached to all the                     submissions (even the ones not returned due to pagination).
 * @param warnings 
 */


data class ElearningModWorkshopGetSubmissions200Response (

    @SerializedName("submissions")
    val submissions: kotlin.collections.List<ElearningModWorkshopGetSubmissions200ResponseSubmissionsInner>,

    /* Total count of submissions. */
    @SerializedName("totalcount")
    val totalcount: kotlin.Int,

    /* Total size (bytes) of the files attached to all the                     submissions (even the ones not returned due to pagination). */
    @SerializedName("totalfilesize")
    val totalfilesize: kotlin.Int,

    @SerializedName("warnings")
    val warnings: kotlin.collections.List<ElearningAuthEmailSignupUser200ResponseWarningsInner>? = null

) {


}

