/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningAuthEmailSignupUser200ResponseWarningsInner
import org.openapitools.client.models.ElearningCoreReportbuilderRetrieveReport200ResponseData
import org.openapitools.client.models.ElearningCoreReportbuilderRetrieveReport200ResponseDetails

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param `data` 
 * @param details 
 * @param warnings 
 */


data class ElearningCoreReportbuilderRetrieveReport200Response (

    @SerializedName("data")
    val `data`: ElearningCoreReportbuilderRetrieveReport200ResponseData,

    @SerializedName("details")
    val details: ElearningCoreReportbuilderRetrieveReport200ResponseDetails,

    @SerializedName("warnings")
    val warnings: kotlin.collections.List<ElearningAuthEmailSignupUser200ResponseWarningsInner>? = null

) {


}

