/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param h5pactivityid h5p activity instance id
 * @param attemptid The attempt id
 * @param userid The user id to log attempt (null means only current user)
 */


data class ElearningModH5pactivityLogReportViewedRequest (

    /* h5p activity instance id */
    @SerializedName("h5pactivityid")
    val h5pactivityid: kotlin.Int,

    /* The attempt id */
    @SerializedName("attemptid")
    val attemptid: kotlin.Int? = null,

    /* The user id to log attempt (null means only current user) */
    @SerializedName("userid")
    val userid: kotlin.Int? = null

) {


}

