/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param capabilities 
 * @param courseids 
 * @param includenotenrolledcourses whether to return courses that the user can see                                                                     even if is not enroled in. This requires the parameter courseids                                                                     to not be empty.
 */


data class ElearningModAssignGetAssignmentsRequest (

    @SerializedName("capabilities")
    val capabilities: kotlin.collections.List<kotlin.Any>? = null,

    @SerializedName("courseids")
    val courseids: kotlin.collections.List<kotlin.Any>? = null,

    /* whether to return courses that the user can see                                                                     even if is not enroled in. This requires the parameter courseids                                                                     to not be empty. */
    @SerializedName("includenotenrolledcourses")
    val includenotenrolledcourses: kotlin.Boolean? = false

) {


}

