/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param courseid Course id
 * @param grade Grade formatted
 * @param rank Your rank in the course
 * @param rawgrade Raw grade, not formatted
 */


data class ElearningGradereportOverviewGetCourseGrades200ResponseGradesInner (

    /* Course id */
    @SerializedName("courseid")
    val courseid: kotlin.Int? = null,

    /* Grade formatted */
    @SerializedName("grade")
    val grade: kotlin.String? = null,

    /* Your rank in the course */
    @SerializedName("rank")
    val rank: kotlin.Int? = null,

    /* Raw grade, not formatted */
    @SerializedName("rawgrade")
    val rawgrade: kotlin.String? = null

) {


}

