/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param status True if digital consent verification is enabled,                     false otherwise.
 */


data class ElearningCoreAuthIsAgeDigitalConsentVerificationEnabled200Response (

    /* True if digital consent verification is enabled,                     false otherwise. */
    @SerializedName("status")
    val status: kotlin.Boolean

) {


}

