/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param checked we already answered
 * @param countanswers number of answers
 * @param disabled option disabled
 * @param displaylayout true for orizontal, otherwise vertical
 * @param id option id
 * @param maxanswers maximum number of answers
 * @param text text of the choice
 */


data class ElearningModChoiceGetChoiceOptions200ResponseOptionsInner (

    /* we already answered */
    @SerializedName("checked")
    val checked: kotlin.Boolean? = null,

    /* number of answers */
    @SerializedName("countanswers")
    val countanswers: kotlin.Int? = null,

    /* option disabled */
    @SerializedName("disabled")
    val disabled: kotlin.Boolean? = null,

    /* true for orizontal, otherwise vertical */
    @SerializedName("displaylayout")
    val displaylayout: kotlin.Boolean? = null,

    /* option id */
    @SerializedName("id")
    val id: kotlin.Int? = null,

    /* maximum number of answers */
    @SerializedName("maxanswers")
    val maxanswers: kotlin.Int? = null,

    /* text of the choice */
    @SerializedName("text")
    val text: kotlin.String? = null

) {


}

