/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningCoreCompetencyGradeCompetency200ResponseActionuser
import org.openapitools.client.models.ElearningCoreCompetencyReadPlan200ResponseCommentarea
import org.openapitools.client.models.ElearningToolLpDataForCompetencySummary200Response
import org.openapitools.client.models.ElearningToolLpDataForCourseCompetenciesPage200ResponseCompetenciesInnerUsercompetencycourse
import org.openapitools.client.models.ElearningToolLpDataForUserCompetencySummary200ResponseEvidenceInner
import org.openapitools.client.models.ElearningToolLpDataForUserCompetencySummary200ResponseUsercompetency
import org.openapitools.client.models.ElearningToolLpDataForUserCompetencySummary200ResponseUsercompetencyplan

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param cangrade cangrade
 * @param competency 
 * @param evidence 
 * @param showrelatedcompetencies showrelatedcompetencies
 * @param user 
 * @param commentarea 
 * @param usercompetency 
 * @param usercompetencycourse 
 * @param usercompetencyplan 
 */


data class ElearningToolLpDataForUserCompetencySummaryInCourse200ResponseUsercompetencysummary (

    /* cangrade */
    @SerializedName("cangrade")
    val cangrade: kotlin.Boolean,

    @SerializedName("competency")
    val competency: ElearningToolLpDataForCompetencySummary200Response,

    @SerializedName("evidence")
    val evidence: kotlin.collections.List<ElearningToolLpDataForUserCompetencySummary200ResponseEvidenceInner>,

    /* showrelatedcompetencies */
    @SerializedName("showrelatedcompetencies")
    val showrelatedcompetencies: kotlin.Boolean,

    @SerializedName("user")
    val user: ElearningCoreCompetencyGradeCompetency200ResponseActionuser,

    @SerializedName("commentarea")
    val commentarea: ElearningCoreCompetencyReadPlan200ResponseCommentarea? = null,

    @SerializedName("usercompetency")
    val usercompetency: ElearningToolLpDataForUserCompetencySummary200ResponseUsercompetency? = null,

    @SerializedName("usercompetencycourse")
    val usercompetencycourse: ElearningToolLpDataForCourseCompetenciesPage200ResponseCompetenciesInnerUsercompetencycourse? = null,

    @SerializedName("usercompetencyplan")
    val usercompetencyplan: ElearningToolLpDataForUserCompetencySummary200ResponseUsercompetencyplan? = null

) {


}

