/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningModForumSetSubscriptionState200ResponseCapabilities
import org.openapitools.client.models.ElearningModForumSetSubscriptionState200ResponseGroup
import org.openapitools.client.models.ElearningModForumSetSubscriptionState200ResponseTimed
import org.openapitools.client.models.ElearningModForumSetSubscriptionState200ResponseTimes
import org.openapitools.client.models.ElearningModForumSetSubscriptionState200ResponseUrls
import org.openapitools.client.models.ElearningModForumSetSubscriptionState200ResponseUserstate

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param capabilities 
 * @param firstpostid firstpostid
 * @param forumid forumid
 * @param id id
 * @param istimelocked istimelocked
 * @param locked locked
 * @param name name
 * @param pinned pinned
 * @param timed 
 * @param times 
 * @param urls 
 * @param userstate 
 * @param group 
 */


data class ElearningModForumSetSubscriptionState200Response (

    @SerializedName("capabilities")
    val capabilities: ElearningModForumSetSubscriptionState200ResponseCapabilities,

    /* firstpostid */
    @SerializedName("firstpostid")
    val firstpostid: kotlin.Int,

    /* forumid */
    @SerializedName("forumid")
    val forumid: kotlin.Int,

    /* id */
    @SerializedName("id")
    val id: kotlin.Int,

    /* istimelocked */
    @SerializedName("istimelocked")
    val istimelocked: kotlin.Boolean,

    /* locked */
    @SerializedName("locked")
    val locked: kotlin.Boolean,

    /* name */
    @SerializedName("name")
    val name: kotlin.String,

    /* pinned */
    @SerializedName("pinned")
    val pinned: kotlin.Boolean,

    @SerializedName("timed")
    val timed: ElearningModForumSetSubscriptionState200ResponseTimed,

    @SerializedName("times")
    val times: ElearningModForumSetSubscriptionState200ResponseTimes,

    @SerializedName("urls")
    val urls: ElearningModForumSetSubscriptionState200ResponseUrls,

    @SerializedName("userstate")
    val userstate: ElearningModForumSetSubscriptionState200ResponseUserstate,

    @SerializedName("group")
    val group: ElearningModForumSetSubscriptionState200ResponseGroup? = null

) {


}

