/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param submissionid submission id.
 * @param feedbackformat The feedback format for text.
 * @param feedbacktext The feedback for the author.
 * @param gradeover The new submission grade.
 * @param published Publish the submission for others?.
 */


data class ElearningModWorkshopEvaluateSubmissionRequest (

    /* submission id. */
    @SerializedName("submissionid")
    val submissionid: kotlin.Int,

    /* The feedback format for text. */
    @SerializedName("feedbackformat")
    val feedbackformat: kotlin.Int? = 0,

    /* The feedback for the author. */
    @SerializedName("feedbacktext")
    val feedbacktext: kotlin.String? = "",

    /* The new submission grade. */
    @SerializedName("gradeover")
    val gradeover: kotlin.String? = "",

    /* Publish the submission for others?. */
    @SerializedName("published")
    val published: kotlin.Boolean? = false

) {


}

