/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningModAssignSaveSubmissionRequestPlugindataOnlinetextEditor

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param filesFilemanager The id of a draft area containing files for this submission.
 * @param onlinetextEditor 
 */


data class ElearningModAssignSaveSubmissionRequestPlugindata (

    /* The id of a draft area containing files for this submission. */
    @SerializedName("files_filemanager")
    val filesFilemanager: kotlin.Int? = null,

    @SerializedName("onlinetext_editor")
    val onlinetextEditor: ElearningModAssignSaveSubmissionRequestPlugindataOnlinetextEditor? = null

) {


}

