/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningCoreBlogGetEntries200ResponseEntriesInnerSummaryfilesInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param addtemplate addtemplate field
 * @param approval approval field
 * @param asearchtemplate asearchtemplate field
 * @param assessed assessed field
 * @param assesstimefinish assesstimefinish field
 * @param assesstimestart assesstimestart field
 * @param comments comments enabled
 * @param course Course id
 * @param coursemodule coursemodule
 * @param csstemplate csstemplate field
 * @param defaultsort defaultsort field
 * @param defaultsortdir defaultsortdir field
 * @param editany editany field (not used any more)
 * @param id Database id
 * @param intro The Database intro
 * @param introfiles 
 * @param introformat intro format (1 = HTML, 0 = MOODLE, 2 = PLAIN, or 4 = MARKDOWN)
 * @param jstemplate jstemplate field
 * @param lang Forced activity language
 * @param listtemplate listtemplate field
 * @param listtemplatefooter listtemplatefooter field
 * @param listtemplateheader listtemplateheader field
 * @param manageapproved manageapproved field
 * @param maxentries maxentries field
 * @param name Database name
 * @param notification notification field (not used any more)
 * @param requiredentries requiredentries field
 * @param requiredentriestoview requiredentriestoview field
 * @param rssarticles rssarticles field
 * @param rsstemplate rsstemplate field
 * @param rsstitletemplate rsstitletemplate field
 * @param scale scale field
 * @param singletemplate singletemplate field
 * @param timeavailablefrom timeavailablefrom field
 * @param timeavailableto timeavailableto field
 * @param timemodified Time modified
 * @param timeviewfrom timeviewfrom field
 * @param timeviewto timeviewto field
 */


data class ElearningModDataGetDatabasesByCourses200ResponseDatabasesInner (

    /* addtemplate field */
    @SerializedName("addtemplate")
    val addtemplate: kotlin.String? = null,

    /* approval field */
    @SerializedName("approval")
    val approval: kotlin.Boolean? = null,

    /* asearchtemplate field */
    @SerializedName("asearchtemplate")
    val asearchtemplate: kotlin.String? = null,

    /* assessed field */
    @SerializedName("assessed")
    val assessed: kotlin.Int? = null,

    /* assesstimefinish field */
    @SerializedName("assesstimefinish")
    val assesstimefinish: kotlin.Int? = null,

    /* assesstimestart field */
    @SerializedName("assesstimestart")
    val assesstimestart: kotlin.Int? = null,

    /* comments enabled */
    @SerializedName("comments")
    val comments: kotlin.Boolean? = null,

    /* Course id */
    @SerializedName("course")
    val course: kotlin.Int? = null,

    /* coursemodule */
    @SerializedName("coursemodule")
    val coursemodule: kotlin.Int? = null,

    /* csstemplate field */
    @SerializedName("csstemplate")
    val csstemplate: kotlin.String? = null,

    /* defaultsort field */
    @SerializedName("defaultsort")
    val defaultsort: kotlin.Int? = null,

    /* defaultsortdir field */
    @SerializedName("defaultsortdir")
    val defaultsortdir: kotlin.Int? = null,

    /* editany field (not used any more) */
    @SerializedName("editany")
    val editany: kotlin.Boolean? = null,

    /* Database id */
    @SerializedName("id")
    val id: kotlin.Int? = null,

    /* The Database intro */
    @SerializedName("intro")
    val intro: kotlin.String? = null,

    @SerializedName("introfiles")
    val introfiles: kotlin.collections.List<ElearningCoreBlogGetEntries200ResponseEntriesInnerSummaryfilesInner>? = null,

    /* intro format (1 = HTML, 0 = MOODLE, 2 = PLAIN, or 4 = MARKDOWN) */
    @SerializedName("introformat")
    val introformat: kotlin.Int? = 0,

    /* jstemplate field */
    @SerializedName("jstemplate")
    val jstemplate: kotlin.String? = null,

    /* Forced activity language */
    @SerializedName("lang")
    val lang: kotlin.String? = null,

    /* listtemplate field */
    @SerializedName("listtemplate")
    val listtemplate: kotlin.String? = null,

    /* listtemplatefooter field */
    @SerializedName("listtemplatefooter")
    val listtemplatefooter: kotlin.String? = null,

    /* listtemplateheader field */
    @SerializedName("listtemplateheader")
    val listtemplateheader: kotlin.String? = null,

    /* manageapproved field */
    @SerializedName("manageapproved")
    val manageapproved: kotlin.Boolean? = null,

    /* maxentries field */
    @SerializedName("maxentries")
    val maxentries: kotlin.Int? = null,

    /* Database name */
    @SerializedName("name")
    val name: kotlin.String? = null,

    /* notification field (not used any more) */
    @SerializedName("notification")
    val notification: kotlin.Int? = null,

    /* requiredentries field */
    @SerializedName("requiredentries")
    val requiredentries: kotlin.Int? = null,

    /* requiredentriestoview field */
    @SerializedName("requiredentriestoview")
    val requiredentriestoview: kotlin.Int? = null,

    /* rssarticles field */
    @SerializedName("rssarticles")
    val rssarticles: kotlin.Int? = null,

    /* rsstemplate field */
    @SerializedName("rsstemplate")
    val rsstemplate: kotlin.String? = null,

    /* rsstitletemplate field */
    @SerializedName("rsstitletemplate")
    val rsstitletemplate: kotlin.String? = null,

    /* scale field */
    @SerializedName("scale")
    val scale: kotlin.Int? = null,

    /* singletemplate field */
    @SerializedName("singletemplate")
    val singletemplate: kotlin.String? = null,

    /* timeavailablefrom field */
    @SerializedName("timeavailablefrom")
    val timeavailablefrom: kotlin.Int? = null,

    /* timeavailableto field */
    @SerializedName("timeavailableto")
    val timeavailableto: kotlin.Int? = null,

    /* Time modified */
    @SerializedName("timemodified")
    val timemodified: kotlin.Int? = null,

    /* timeviewfrom field */
    @SerializedName("timeviewfrom")
    val timeviewfrom: kotlin.Int? = null,

    /* timeviewto field */
    @SerializedName("timeviewto")
    val timeviewto: kotlin.Int? = null

) {


}

