/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningAuthEmailSignupUser200ResponseWarningsInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param completed If the user completed the feedback.
 * @param completionpagecontents The completion page contents.
 * @param jumpto The page to jump to.
 * @param siteaftersubmit The link (could be relative) to show after submit.
 * @param warnings 
 */


data class ElearningModFeedbackProcessPage200Response (

    /* If the user completed the feedback. */
    @SerializedName("completed")
    val completed: kotlin.Boolean,

    /* The completion page contents. */
    @SerializedName("completionpagecontents")
    val completionpagecontents: kotlin.String,

    /* The page to jump to. */
    @SerializedName("jumpto")
    val jumpto: kotlin.Int,

    /* The link (could be relative) to show after submit. */
    @SerializedName("siteaftersubmit")
    val siteaftersubmit: kotlin.String,

    @SerializedName("warnings")
    val warnings: kotlin.collections.List<ElearningAuthEmailSignupUser200ResponseWarningsInner>? = null

) {


}

