/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningModAssignSaveGradeRequestAdvancedgradingdataGuide
import org.openapitools.client.models.ElearningModAssignSaveGradeRequestAdvancedgradingdataRubric

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param guide 
 * @param rubric 
 */


data class ElearningModAssignSaveGradeRequestAdvancedgradingdata (

    @SerializedName("guide")
    val guide: ElearningModAssignSaveGradeRequestAdvancedgradingdataGuide? = null,

    @SerializedName("rubric")
    val rubric: ElearningModAssignSaveGradeRequestAdvancedgradingdataRubric? = null

) {


}

