/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param scaleid The scale id
 */


data class ElearningCoreCompetencyGetScaleValuesRequest (

    /* The scale id */
    @SerializedName("scaleid")
    val scaleid: kotlin.Int

) {


}

