/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param fullname contact user fullname
 * @param id contact user id
 */


data class ElearningCoreCourseGetCoursesByField200ResponseCoursesInnerContactsInner (

    /* contact user fullname */
    @SerializedName("fullname")
    val fullname: kotlin.String? = null,

    /* contact user id */
    @SerializedName("id")
    val id: kotlin.Int? = null

) {


}

