/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param participantcount Number of users who can submit.
 * @param submissiondraftscount Number of submissions in draft status.
 * @param submissionsenabled Whether submissions are enabled or not.
 * @param submissionsneedgradingcount Number of submissions that need grading.
 * @param submissionssubmittedcount Number of submissions in submitted status.
 * @param warnofungroupedusers Whether we need to warn people that there                                                                         are users without groups ('warningrequired'), warn                                                                         people there are users who will submit in the default                                                                         group ('warningoptional') or no warning ('').
 */


data class ElearningModAssignGetSubmissionStatus200ResponseGradingsummary (

    /* Number of users who can submit. */
    @SerializedName("participantcount")
    val participantcount: kotlin.Int,

    /* Number of submissions in draft status. */
    @SerializedName("submissiondraftscount")
    val submissiondraftscount: kotlin.Int,

    /* Whether submissions are enabled or not. */
    @SerializedName("submissionsenabled")
    val submissionsenabled: kotlin.Boolean,

    /* Number of submissions that need grading. */
    @SerializedName("submissionsneedgradingcount")
    val submissionsneedgradingcount: kotlin.Int,

    /* Number of submissions in submitted status. */
    @SerializedName("submissionssubmittedcount")
    val submissionssubmittedcount: kotlin.Int,

    /* Whether we need to warn people that there                                                                         are users without groups ('warningrequired'), warn                                                                         people there are users who will submit in the default                                                                         group ('warningoptional') or no warning (''). */
    @SerializedName("warnofungroupedusers")
    val warnofungroupedusers: kotlin.String

) {


}

