/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param companyid Company ID
 * @param departmentid Department ID
 * @param email User email address
 * @param firstname User firstname
 * @param id User ID
 * @param lastname User lastname
 */


data class ElearningBlockIomadCompanyAdminGetDepartmentUsers200ResponseUsersInner (

    /* Company ID */
    @SerializedName("companyid")
    val companyid: kotlin.Int? = null,

    /* Department ID */
    @SerializedName("departmentid")
    val departmentid: kotlin.Int? = null,

    /* User email address */
    @SerializedName("email")
    val email: kotlin.String? = null,

    /* User firstname */
    @SerializedName("firstname")
    val firstname: kotlin.String? = null,

    /* User ID */
    @SerializedName("id")
    val id: kotlin.Int? = null,

    /* User lastname */
    @SerializedName("lastname")
    val lastname: kotlin.String? = null

) {


}

