/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id The id of the contact request
 * @param requesteduserid The id of the user confirming the request
 * @param timecreated The timecreated timestamp for the contact request
 * @param userid The id of the user who created the contact request
 */


data class ElearningCoreMessageGetConversation200ResponseMembersInnerContactrequestsInner (

    /* The id of the contact request */
    @SerializedName("id")
    val id: kotlin.Int? = null,

    /* The id of the user confirming the request */
    @SerializedName("requesteduserid")
    val requesteduserid: kotlin.Int? = null,

    /* The timecreated timestamp for the contact request */
    @SerializedName("timecreated")
    val timecreated: kotlin.Int? = null,

    /* The id of the user who created the contact request */
    @SerializedName("userid")
    val userid: kotlin.Int? = null

) {


}

