/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningModForumAddDiscussionPost200ResponsePostAttachmentsInnerHtml
import org.openapitools.client.models.ElearningModForumAddDiscussionPost200ResponsePostAttachmentsInnerUrls

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param author author
 * @param component component
 * @param contextid contextid
 * @param filearea filearea
 * @param filename filename
 * @param filenameshort filenameshort
 * @param filepath filepath
 * @param filesize filesize
 * @param filesizeformatted filesizeformatted
 * @param html 
 * @param icon icon
 * @param isdir isdir
 * @param isimage isimage
 * @param itemid itemid
 * @param license license
 * @param timecreated timecreated
 * @param timecreatedformatted timecreatedformatted
 * @param timemodified timemodified
 * @param timemodifiedformatted timemodifiedformatted
 * @param url url
 * @param urls 
 */


data class ElearningModForumAddDiscussionPost200ResponsePostAttachmentsInner (

    /* author */
    @SerializedName("author")
    val author: kotlin.String? = null,

    /* component */
    @SerializedName("component")
    val component: kotlin.String? = null,

    /* contextid */
    @SerializedName("contextid")
    val contextid: kotlin.Int? = null,

    /* filearea */
    @SerializedName("filearea")
    val filearea: kotlin.String? = null,

    /* filename */
    @SerializedName("filename")
    val filename: kotlin.String? = null,

    /* filenameshort */
    @SerializedName("filenameshort")
    val filenameshort: kotlin.String? = null,

    /* filepath */
    @SerializedName("filepath")
    val filepath: kotlin.String? = null,

    /* filesize */
    @SerializedName("filesize")
    val filesize: kotlin.Int? = null,

    /* filesizeformatted */
    @SerializedName("filesizeformatted")
    val filesizeformatted: kotlin.String? = null,

    @SerializedName("html")
    val html: ElearningModForumAddDiscussionPost200ResponsePostAttachmentsInnerHtml? = null,

    /* icon */
    @SerializedName("icon")
    val icon: kotlin.String? = null,

    /* isdir */
    @SerializedName("isdir")
    val isdir: kotlin.Boolean? = null,

    /* isimage */
    @SerializedName("isimage")
    val isimage: kotlin.Boolean? = null,

    /* itemid */
    @SerializedName("itemid")
    val itemid: kotlin.Int? = null,

    /* license */
    @SerializedName("license")
    val license: kotlin.String? = null,

    /* timecreated */
    @SerializedName("timecreated")
    val timecreated: kotlin.Int? = null,

    /* timecreatedformatted */
    @SerializedName("timecreatedformatted")
    val timecreatedformatted: kotlin.String? = null,

    /* timemodified */
    @SerializedName("timemodified")
    val timemodified: kotlin.Int? = null,

    /* timemodifiedformatted */
    @SerializedName("timemodifiedformatted")
    val timemodifiedformatted: kotlin.String? = null,

    /* url */
    @SerializedName("url")
    val url: kotlin.String? = null,

    @SerializedName("urls")
    val urls: ElearningModForumAddDiscussionPost200ResponsePostAttachmentsInnerUrls? = null

) {


}

