/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningCoreCompetencyGradeCompetency200ResponseActionuser

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param canrequestreview canrequestreview
 * @param canreview canreview
 * @param competencyid competencyid
 * @param grade grade
 * @param gradename gradename
 * @param id id
 * @param iscancelreviewrequestallowed iscancelreviewrequestallowed
 * @param isrequestreviewallowed isrequestreviewallowed
 * @param isstartreviewallowed isstartreviewallowed
 * @param isstatusidle isstatusidle
 * @param isstatusinreview isstatusinreview
 * @param isstatuswaitingforreview isstatuswaitingforreview
 * @param isstopreviewallowed isstopreviewallowed
 * @param proficiency proficiency
 * @param proficiencyname proficiencyname
 * @param reviewerid reviewerid
 * @param status status
 * @param statusname statusname
 * @param timecreated timecreated
 * @param timemodified timemodified
 * @param url url
 * @param userid userid
 * @param usermodified usermodified
 * @param reviewer 
 */


data class ElearningToolLpDataForPlanPage200ResponseCompetenciesInnerUsercompetency (

    /* canrequestreview */
    @SerializedName("canrequestreview")
    val canrequestreview: kotlin.Boolean,

    /* canreview */
    @SerializedName("canreview")
    val canreview: kotlin.Boolean,

    /* competencyid */
    @SerializedName("competencyid")
    val competencyid: kotlin.Int,

    /* grade */
    @SerializedName("grade")
    val grade: kotlin.Int,

    /* gradename */
    @SerializedName("gradename")
    val gradename: kotlin.String,

    /* id */
    @SerializedName("id")
    val id: kotlin.Int = 0,

    /* iscancelreviewrequestallowed */
    @SerializedName("iscancelreviewrequestallowed")
    val iscancelreviewrequestallowed: kotlin.Boolean,

    /* isrequestreviewallowed */
    @SerializedName("isrequestreviewallowed")
    val isrequestreviewallowed: kotlin.Boolean,

    /* isstartreviewallowed */
    @SerializedName("isstartreviewallowed")
    val isstartreviewallowed: kotlin.Boolean,

    /* isstatusidle */
    @SerializedName("isstatusidle")
    val isstatusidle: kotlin.Boolean,

    /* isstatusinreview */
    @SerializedName("isstatusinreview")
    val isstatusinreview: kotlin.Boolean,

    /* isstatuswaitingforreview */
    @SerializedName("isstatuswaitingforreview")
    val isstatuswaitingforreview: kotlin.Boolean,

    /* isstopreviewallowed */
    @SerializedName("isstopreviewallowed")
    val isstopreviewallowed: kotlin.Boolean,

    /* proficiency */
    @SerializedName("proficiency")
    val proficiency: kotlin.Boolean,

    /* proficiencyname */
    @SerializedName("proficiencyname")
    val proficiencyname: kotlin.String,

    /* reviewerid */
    @SerializedName("reviewerid")
    val reviewerid: kotlin.Int,

    /* status */
    @SerializedName("status")
    val status: kotlin.Int = 0,

    /* statusname */
    @SerializedName("statusname")
    val statusname: kotlin.String,

    /* timecreated */
    @SerializedName("timecreated")
    val timecreated: kotlin.Int = 0,

    /* timemodified */
    @SerializedName("timemodified")
    val timemodified: kotlin.Int = 0,

    /* url */
    @SerializedName("url")
    val url: kotlin.String,

    /* userid */
    @SerializedName("userid")
    val userid: kotlin.Int,

    /* usermodified */
    @SerializedName("usermodified")
    val usermodified: kotlin.Int = 0,

    @SerializedName("reviewer")
    val reviewer: ElearningCoreCompetencyGradeCompetency200ResponseActionuser? = null

) {


}

