/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningBlockIomadCompanyAdminGetCompanies200ResponseCompaniesInner
import org.openapitools.client.models.ElearningBlockIomadCompanyAdminGetCompanies200ResponseWarningsInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param companies 
 * @param warnings 
 */


data class ElearningBlockIomadCompanyAdminGetCompanies200Response (

    @SerializedName("companies")
    val companies: kotlin.collections.List<ElearningBlockIomadCompanyAdminGetCompanies200ResponseCompaniesInner>,

    @SerializedName("warnings")
    val warnings: kotlin.collections.List<ElearningBlockIomadCompanyAdminGetCompanies200ResponseWarningsInner>? = null

) {


}

