/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * warning
 *
 * @param item item is always 'assignment'
 * @param itemid when errorcode is 3 then itemid is an assignment id. When errorcode is 1, itemid is a course module id
 * @param message untranslated english message to explain the warning
 * @param warningcode errorcode can be 3 (no grades found) or 1 (no permission to get grades)
 */


data class ElearningModAssignGetGrades200ResponseWarningsInner (

    /* item is always 'assignment' */
    @SerializedName("item")
    val item: kotlin.String? = null,

    /* when errorcode is 3 then itemid is an assignment id. When errorcode is 1, itemid is a course module id */
    @SerializedName("itemid")
    val itemid: kotlin.Int? = null,

    /* untranslated english message to explain the warning */
    @SerializedName("message")
    val message: kotlin.String? = null,

    /* errorcode can be 3 (no grades found) or 1 (no permission to get grades) */
    @SerializedName("warningcode")
    val warningcode: kotlin.String? = null

) {


}

