/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param url H5P file url.
 * @param copyright The copyright option
 * @param embed The embed allow to copy the code to your site
 * @param export The export allow to download the package
 * @param frame The frame allow to show the bar options below the content
 */


data class ElearningCoreH5pGetTrustedH5pFileRequest (

    /* H5P file url. */
    @SerializedName("url")
    val url: kotlin.String,

    /* The copyright option */
    @SerializedName("copyright")
    val copyright: kotlin.Int? = 0,

    /* The embed allow to copy the code to your site */
    @SerializedName("embed")
    val embed: kotlin.Int? = 0,

    /* The export allow to download the package */
    @SerializedName("export")
    val export: kotlin.Int? = 0,

    /* The frame allow to show the bar options below the content */
    @SerializedName("frame")
    val frame: kotlin.Int? = 0

) {


}

