/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param toolproxyid Tool proxy id
 */


data class ElearningModLtiGetToolTypesRequest (

    /* Tool proxy id */
    @SerializedName("toolproxyid")
    val toolproxyid: kotlin.Int? = 0

) {


}

