/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningAuthEmailSignupUser200ResponseWarningsInner
import org.openapitools.client.models.ElearningModForumGetDiscussionPost200ResponsePost

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param post 
 * @param warnings 
 */


data class ElearningModForumGetDiscussionPost200Response (

    @SerializedName("post")
    val post: ElearningModForumGetDiscussionPost200ResponsePost,

    @SerializedName("warnings")
    val warnings: kotlin.collections.List<ElearningAuthEmailSignupUser200ResponseWarningsInner>? = null

) {


}

