/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningAuthEmailSignupUser200ResponseWarningsInner
import org.openapitools.client.models.ElearningCoreCourseCheckUpdates200ResponseInstancesInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param instances 
 * @param warnings 
 */


data class ElearningCoreCourseCheckUpdates200Response (

    @SerializedName("instances")
    val instances: kotlin.collections.List<ElearningCoreCourseCheckUpdates200ResponseInstancesInner>,

    @SerializedName("warnings")
    val warnings: kotlin.collections.List<ElearningAuthEmailSignupUser200ResponseWarningsInner>? = null

) {


}

