/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningBlockIomadCompanyAdminGetCompanies200ResponseWarningsInner
import org.openapitools.client.models.ElearningBlockIomadCompanyAdminGetDepartmentUsers200ResponseUsersInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param users 
 * @param warnings 
 */


data class ElearningBlockIomadCompanyAdminGetDepartmentUsers200Response (

    @SerializedName("users")
    val users: kotlin.collections.List<ElearningBlockIomadCompanyAdminGetDepartmentUsers200ResponseUsersInner>,

    @SerializedName("warnings")
    val warnings: kotlin.collections.List<ElearningBlockIomadCompanyAdminGetCompanies200ResponseWarningsInner>? = null

) {


}

