/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param name data name
 * @param `value` data value
 */


data class ElearningModLessonProcessPageRequestDataInner (

    /* data name */
    @SerializedName("name")
    val name: kotlin.String? = null,

    /* data value */
    @SerializedName("value")
    val `value`: kotlin.String? = null

) {


}

