/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningAuthEmailSignupUser200ResponseWarningsInner
import org.openapitools.client.models.ElearningModFeedbackGetNonRespondents200ResponseUsersInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param total Total number of non respondents
 * @param users 
 * @param warnings 
 */


data class ElearningModFeedbackGetNonRespondents200Response (

    /* Total number of non respondents */
    @SerializedName("total")
    val total: kotlin.Int,

    @SerializedName("users")
    val users: kotlin.collections.List<ElearningModFeedbackGetNonRespondents200ResponseUsersInner>,

    @SerializedName("warnings")
    val warnings: kotlin.collections.List<ElearningAuthEmailSignupUser200ResponseWarningsInner>? = null

) {


}

