/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningAuthEmailSignupUser200ResponseWarningsInner
import org.openapitools.client.models.ElearningModLabelGetLabelsByCourses200ResponseLabelsInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param labels 
 * @param warnings 
 */


data class ElearningModLabelGetLabelsByCourses200Response (

    @SerializedName("labels")
    val labels: kotlin.collections.List<ElearningModLabelGetLabelsByCourses200ResponseLabelsInner>,

    @SerializedName("warnings")
    val warnings: kotlin.collections.List<ElearningAuthEmailSignupUser200ResponseWarningsInner>? = null

) {


}

