/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningModForumGetDiscussionPosts200ResponsePostsInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param parentposts 
 * @param userposts 
 */


data class ElearningModForumGetDiscussionPostsByUserid200ResponseDiscussionsInnerPosts (

    @SerializedName("parentposts")
    val parentposts: kotlin.collections.List<ElearningModForumGetDiscussionPosts200ResponsePostsInner>,

    @SerializedName("userposts")
    val userposts: kotlin.collections.List<ElearningModForumGetDiscussionPosts200ResponsePostsInner>

) {


}

