/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param courseid id of course
 * @param groupid id of group
 */


data class ElearningLocalIomadLearningpathOrdercoursesRequestCoursesInner (

    /* id of course */
    @SerializedName("courseid")
    val courseid: kotlin.Int? = null,

    /* id of group */
    @SerializedName("groupid")
    val groupid: kotlin.Int? = null

) {


}

