/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param name Field name.
 * @param `value` Field value.
 */


data class ElearningToolMobileGetContent200ResponseOtherdataInner (

    /* Field name. */
    @SerializedName("name")
    val name: kotlin.String? = null,

    /* Field value. */
    @SerializedName("value")
    val `value`: kotlin.String? = null

) {


}

