/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningAuthEmailSignupUser200ResponseWarningsInner
import org.openapitools.client.models.ElearningCoreBadgesGetUserBadgeByHash200ResponseBadgeInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param badge 
 * @param warnings 
 */


data class ElearningCoreBadgesGetUserBadgeByHash200Response (

    @SerializedName("badge")
    val badge: kotlin.collections.List<ElearningCoreBadgesGetUserBadgeByHash200ResponseBadgeInner>,

    @SerializedName("warnings")
    val warnings: kotlin.collections.List<ElearningAuthEmailSignupUser200ResponseWarningsInner>? = null

) {


}

