/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param submitted If form was submitted and validated
 * @param `data` JSON-encoded return data from form processing method
 * @param html HTML fragment of the form
 * @param javascript JavaScript fragment of the form
 */


data class ElearningCoreFormDynamicForm200Response (

    /* If form was submitted and validated */
    @SerializedName("submitted")
    val submitted: kotlin.Boolean,

    /* JSON-encoded return data from form processing method */
    @SerializedName("data")
    val `data`: kotlin.String? = null,

    /* HTML fragment of the form */
    @SerializedName("html")
    val html: kotlin.String? = null,

    /* JavaScript fragment of the form */
    @SerializedName("javascript")
    val javascript: kotlin.String? = null

) {


}

