/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param companyid User company ID
 * @param departmentid User company department ID
 * @param educator User educator 0 => No, 1 => Yes
 * @param managertype User manager type 0 => User, 1 => company manager 2 => department manager, 3 => report only
 * @param userid User ID
 */


data class ElearningBlockIomadCompanyAdminAssignUsersRequestUsersInner (

    /* User company ID */
    @SerializedName("companyid")
    val companyid: kotlin.Int? = 0,

    /* User company department ID */
    @SerializedName("departmentid")
    val departmentid: kotlin.Int? = 0,

    /* User educator 0 => No, 1 => Yes */
    @SerializedName("educator")
    val educator: kotlin.Int? = 0,

    /* User manager type 0 => User, 1 => company manager 2 => department manager, 3 => report only */
    @SerializedName("managertype")
    val managertype: kotlin.Int? = 0,

    /* User ID */
    @SerializedName("userid")
    val userid: kotlin.Int? = 0

) {


}

