/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningBlockIomadCompanyAdminCreateLicensesRequestLicensesInnerCoursesInner

import com.google.gson.annotations.SerializedName

/**
 * one or many licenses
 *
 * @param allocation Number of license slots
 * @param clearonexpire Clear license assignments on expire - 0 = no, 1 = yes
 * @param companyid Company id
 * @param courses 
 * @param cutoffdate License cut off date (int = timestamp)
 * @param expirydate License expiry date (int = timestamp)
 * @param instant Instant access - 0 = no, 1 = yes
 * @param name License name
 * @param parentid Parent license id
 * @param program Program pf courses 0 = no, 1 = yes
 * @param reference License reference
 * @param startdate Date from which the liucense is available (int = timestamp) 
 * @param type License type - 0 = standard, 1 = reusable, 2 = standard educator, 3 = reusable educator
 * @param used Number how often the lic can be allocated
 * @param validlength Course access length (days)
 */


data class ElearningBlockIomadCompanyAdminCreateLicensesRequestLicensesInner (

    /* Number of license slots */
    @SerializedName("allocation")
    val allocation: kotlin.Int? = null,

    /* Clear license assignments on expire - 0 = no, 1 = yes */
    @SerializedName("clearonexpire")
    val clearonexpire: kotlin.Int? = null,

    /* Company id */
    @SerializedName("companyid")
    val companyid: kotlin.Int? = null,

    @SerializedName("courses")
    val courses: kotlin.collections.List<ElearningBlockIomadCompanyAdminCreateLicensesRequestLicensesInnerCoursesInner>? = null,

    /* License cut off date (int = timestamp) */
    @SerializedName("cutoffdate")
    val cutoffdate: kotlin.Int? = null,

    /* License expiry date (int = timestamp) */
    @SerializedName("expirydate")
    val expirydate: kotlin.Int? = null,

    /* Instant access - 0 = no, 1 = yes */
    @SerializedName("instant")
    val instant: kotlin.Int? = null,

    /* License name */
    @SerializedName("name")
    val name: kotlin.String? = null,

    /* Parent license id */
    @SerializedName("parentid")
    val parentid: kotlin.Int? = null,

    /* Program pf courses 0 = no, 1 = yes */
    @SerializedName("program")
    val program: kotlin.Int? = null,

    /* License reference */
    @SerializedName("reference")
    val reference: kotlin.String? = null,

    /* Date from which the liucense is available (int = timestamp)  */
    @SerializedName("startdate")
    val startdate: kotlin.Int? = null,

    /* License type - 0 = standard, 1 = reusable, 2 = standard educator, 3 = reusable educator */
    @SerializedName("type")
    val type: kotlin.Int? = null,

    /* Number how often the lic can be allocated */
    @SerializedName("used")
    val used: kotlin.Int? = null,

    /* Course access length (days) */
    @SerializedName("validlength")
    val validlength: kotlin.Int? = null

) {


}

