/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningCoreEnrolGetEnrolledUsersRequestOptionsInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param courseid course id
 * @param options 
 */


data class ElearningCoreEnrolGetEnrolledUsersRequest (

    /* course id */
    @SerializedName("courseid")
    val courseid: kotlin.Int,

    @SerializedName("options")
    val options: kotlin.collections.List<ElearningCoreEnrolGetEnrolledUsersRequestOptionsInner>? = null

) {


}

