/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningGradereportUserGetGradesTable200ResponseTablesInnerTabledataInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param courseid course id
 * @param maxdepth table max depth (needed for printing it)
 * @param tabledata 
 * @param userfullname user fullname
 * @param userid user id
 */


data class ElearningGradereportUserGetGradesTable200ResponseTablesInner (

    /* course id */
    @SerializedName("courseid")
    val courseid: kotlin.Int? = null,

    /* table max depth (needed for printing it) */
    @SerializedName("maxdepth")
    val maxdepth: kotlin.Int? = null,

    @SerializedName("tabledata")
    val tabledata: kotlin.collections.List<ElearningGradereportUserGetGradesTable200ResponseTablesInnerTabledataInner>? = null,

    /* user fullname */
    @SerializedName("userfullname")
    val userfullname: kotlin.String? = null,

    /* user id */
    @SerializedName("userid")
    val userid: kotlin.Int? = null

) {


}

