/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param context Page context id
 * @param setmode Set edit mode to
 */


data class ElearningCoreChangeEditmodeRequest (

    /* Page context id */
    @SerializedName("context")
    val context: kotlin.Int,

    /* Set edit mode to */
    @SerializedName("setmode")
    val setmode: kotlin.Boolean

) {


}

