/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param cartridgeurl URL to cardridge to load tool information
 * @param key Consumer key
 * @param secret Shared secret
 */


data class ElearningModLtiCreateToolTypeRequest (

    /* URL to cardridge to load tool information */
    @SerializedName("cartridgeurl")
    val cartridgeurl: kotlin.String? = "",

    /* Consumer key */
    @SerializedName("key")
    val key: kotlin.String? = "",

    /* Shared secret */
    @SerializedName("secret")
    val secret: kotlin.String? = ""

) {


}

