/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param daytimestamp Timestamp for the new start day
 * @param eventid Id of event to be updated
 */


data class ElearningCoreCalendarUpdateEventStartDayRequest (

    /* Timestamp for the new start day */
    @SerializedName("daytimestamp")
    val daytimestamp: kotlin.Int,

    /* Id of event to be updated */
    @SerializedName("eventid")
    val eventid: kotlin.Int

) {


}

