/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningAuthEmailSignupUser200ResponseWarningsInner
import org.openapitools.client.models.ElearningModLessonGetLesson200ResponseLesson

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param lesson 
 * @param warnings 
 */


data class ElearningModLessonGetLesson200Response (

    @SerializedName("lesson")
    val lesson: ElearningModLessonGetLesson200ResponseLesson,

    @SerializedName("warnings")
    val warnings: kotlin.collections.List<ElearningAuthEmailSignupUser200ResponseWarningsInner>? = null

) {


}

