/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param fieldname The field name.
 * @param notification The notification for the field.
 */


data class ElearningModDataUpdateEntry200ResponseFieldnotificationsInner (

    /* The field name. */
    @SerializedName("fieldname")
    val fieldname: kotlin.String? = null,

    /* The notification for the field. */
    @SerializedName("notification")
    val notification: kotlin.String? = null

) {


}

