/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningCoreCompetencyCreatePlanRequestPlan

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param plan 
 */


data class ElearningCoreCompetencyCreatePlanRequest (

    @SerializedName("plan")
    val plan: ElearningCoreCompetencyCreatePlanRequestPlan

) {


}

