/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningCoreGradingGetDefinitions200ResponseAreasInnerDefinitionsInnerRubricRubricCriteriaInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param rubricCriteria 
 */


data class ElearningCoreGradingGetDefinitions200ResponseAreasInnerDefinitionsInnerRubric (

    @SerializedName("rubric_criteria")
    val rubricCriteria: kotlin.collections.List<ElearningCoreGradingGetDefinitions200ResponseAreasInnerDefinitionsInnerRubricRubricCriteriaInner>? = null

) {


}

