/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param courseid course id
 * @param page Page number
 * @param perpage Number per page
 * @param search query
 * @param searchanywhere find a match anywhere, or only at the beginning
 * @param contextid Context ID
 */


data class ElearningCoreEnrolSearchUsersRequest (

    /* course id */
    @SerializedName("courseid")
    val courseid: kotlin.Int,

    /* Page number */
    @SerializedName("page")
    val page: kotlin.Int,

    /* Number per page */
    @SerializedName("perpage")
    val perpage: kotlin.Int,

    /* query */
    @SerializedName("search")
    val search: kotlin.String,

    /* find a match anywhere, or only at the beginning */
    @SerializedName("searchanywhere")
    val searchanywhere: kotlin.Boolean,

    /* Context ID */
    @SerializedName("contextid")
    val contextid: kotlin.Int? = null

) {


}

