/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningModFeedbackGetResponsesAnalysis200ResponseAttemptsInnerResponsesInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param courseid Course id
 * @param fullname User full name
 * @param id Completed id
 * @param responses 
 * @param timemodified Time modified for the response
 * @param userid User who responded
 */


data class ElearningModFeedbackGetResponsesAnalysis200ResponseAttemptsInner (

    /* Course id */
    @SerializedName("courseid")
    val courseid: kotlin.Int? = null,

    /* User full name */
    @SerializedName("fullname")
    val fullname: kotlin.String? = null,

    /* Completed id */
    @SerializedName("id")
    val id: kotlin.Int? = null,

    @SerializedName("responses")
    val responses: kotlin.collections.List<ElearningModFeedbackGetResponsesAnalysis200ResponseAttemptsInnerResponsesInner>? = null,

    /* Time modified for the response */
    @SerializedName("timemodified")
    val timemodified: kotlin.Int? = null,

    /* User who responded */
    @SerializedName("userid")
    val userid: kotlin.Int? = null

) {


}

