/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param forumid forum instance id
 * @param groupid group id
 * @param page current page
 * @param perpage items per page
 * @param sortorder sort by this element: numreplies, , created or timemodified
 */


data class ElearningModForumGetForumDiscussionsRequest (

    /* forum instance id */
    @SerializedName("forumid")
    val forumid: kotlin.Int,

    /* group id */
    @SerializedName("groupid")
    val groupid: kotlin.Int? = 0,

    /* current page */
    @SerializedName("page")
    val page: kotlin.Int? = -1,

    /* items per page */
    @SerializedName("perpage")
    val perpage: kotlin.Int? = 0,

    /* sort by this element: numreplies, , created or timemodified */
    @SerializedName("sortorder")
    val sortorder: kotlin.Int? = -1

) {


}

