/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningModH5pactivityGetAttempts200ResponseUsersattemptsInnerScoredAttemptsInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param attempts 
 * @param grademethod Grading method
 * @param title Scored attempts title
 */


data class ElearningModH5pactivityGetUserAttempts200ResponseUsersattemptsInnerScored (

    @SerializedName("attempts")
    val attempts: kotlin.collections.List<ElearningModH5pactivityGetAttempts200ResponseUsersattemptsInnerScoredAttemptsInner>,

    /* Grading method */
    @SerializedName("grademethod")
    val grademethod: kotlin.String,

    /* Scored attempts title */
    @SerializedName("title")
    val title: kotlin.String

) {


}

