/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id category id to delete
 * @param newparent the parent category to move the contents to, if specified
 * @param recursive 1: recursively delete all contents inside this                                 category, 0 (default): move contents to newparent or current parent category (except if parent is root)
 */


data class ElearningCoreCourseDeleteCategoriesRequestCategoriesInner (

    /* category id to delete */
    @SerializedName("id")
    val id: kotlin.Int? = null,

    /* the parent category to move the contents to, if specified */
    @SerializedName("newparent")
    val newparent: kotlin.Int? = null,

    /* 1: recursively delete all contents inside this                                 category, 0 (default): move contents to newparent or current parent category (except if parent is root) */
    @SerializedName("recursive")
    val recursive: kotlin.Boolean? = 0

) {


}

