/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param instanceid instance id of guest enrolment plugin
 * @param password the course password
 */


data class ElearningEnrolGuestValidatePasswordRequest (

    /* instance id of guest enrolment plugin */
    @SerializedName("instanceid")
    val instanceid: kotlin.Int,

    /* the course password */
    @SerializedName("password")
    val password: kotlin.String

) {


}

