/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningAuthEmailSignupUser200ResponseWarningsInner
import org.openapitools.client.models.ElearningModLessonGetAttemptsOverview200ResponseData

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param `data` 
 * @param warnings 
 */


data class ElearningModLessonGetAttemptsOverview200Response (

    @SerializedName("data")
    val `data`: ElearningModLessonGetAttemptsOverview200ResponseData? = null,

    @SerializedName("warnings")
    val warnings: kotlin.collections.List<ElearningAuthEmailSignupUser200ResponseWarningsInner>? = null

) {


}

