/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * The lesson generated messages
 *
 * @param message Message.
 * @param type Message type: usually a CSS identifier like:                                 success, info, warning, error, notifyproblem, notifyerror, notifytiny, notifysuccess
 */


data class ElearningModLessonGetPageData200ResponseMessagesInner (

    /* Message. */
    @SerializedName("message")
    val message: kotlin.String? = null,

    /* Message type: usually a CSS identifier like:                                 success, info, warning, error, notifyproblem, notifyerror, notifytiny, notifysuccess */
    @SerializedName("type")
    val type: kotlin.String? = null

) {


}

