/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param entitytype Entity type that can be created by a generator.
 */


data class ElearningToolBehatGetEntityGeneratorRequest (

    /* Entity type that can be created by a generator. */
    @SerializedName("entitytype")
    val entitytype: kotlin.String

) {


}

