/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningModDataUpdateEntryRequestDataInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param `data` 
 * @param entryid The entry record id.
 */


data class ElearningModDataUpdateEntryRequest (

    @SerializedName("data")
    val `data`: kotlin.collections.List<ElearningModDataUpdateEntryRequestDataInner>,

    /* The entry record id. */
    @SerializedName("entryid")
    val entryid: kotlin.Int

) {


}

