/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param coursecategory Category name
 * @param courseimage course image
 * @param fullname course full name
 * @param hidden is the course visible
 * @param id course id
 * @param viewurl Next step of import
 */


data class ElearningToolMoodlenetSearchCourses200ResponseCoursesInner (

    /* Category name */
    @SerializedName("coursecategory")
    val coursecategory: kotlin.String? = null,

    /* course image */
    @SerializedName("courseimage")
    val courseimage: kotlin.String? = null,

    /* course full name */
    @SerializedName("fullname")
    val fullname: kotlin.String? = null,

    /* is the course visible */
    @SerializedName("hidden")
    val hidden: kotlin.Int? = null,

    /* course id */
    @SerializedName("id")
    val id: kotlin.Int? = null,

    /* Next step of import */
    @SerializedName("viewurl")
    val viewurl: kotlin.String? = null

) {


}

