/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param criteria Criteria description
 * @param requirement Requirement description
 * @param status Status description, can be anything
 * @param type Type description
 */


data class ElearningCoreCompletionGetCourseCompletionStatus200ResponseCompletionstatusCompletionsInnerDetails (

    /* Criteria description */
    @SerializedName("criteria")
    val criteria: kotlin.String,

    /* Requirement description */
    @SerializedName("requirement")
    val requirement: kotlin.String,

    /* Status description, can be anything */
    @SerializedName("status")
    val status: kotlin.String,

    /* Type description */
    @SerializedName("type")
    val type: kotlin.String

) {


}

