/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param result True if the user's enrolment was successfully updated
 * @param validationerror Indicates invalid form data
 */


data class ElearningCoreEnrolSubmitUserEnrolmentForm200Response (

    /* True if the user's enrolment was successfully updated */
    @SerializedName("result")
    val result: kotlin.Boolean,

    /* Indicates invalid form data */
    @SerializedName("validationerror")
    val validationerror: kotlin.Boolean? = false

) {


}

