/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param cmid course module id
 * @param completed activity completed or not
 */


data class ElearningCoreCompletionUpdateActivityCompletionStatusManuallyRequest (

    /* course module id */
    @SerializedName("cmid")
    val cmid: kotlin.Int,

    /* activity completed or not */
    @SerializedName("completed")
    val completed: kotlin.Boolean

) {


}

