/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningCoreFilesDeleteDraftFilesRequestFilesInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param draftitemid Item id of the draft file area
 * @param files 
 */


data class ElearningCoreFilesDeleteDraftFilesRequest (

    /* Item id of the draft file area */
    @SerializedName("draftitemid")
    val draftitemid: kotlin.Int,

    @SerializedName("files")
    val files: kotlin.collections.List<ElearningCoreFilesDeleteDraftFilesRequestFilesInner>

) {


}

