/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param columns 
 * @param global Set global config setting, rather than user preference
 */


data class ElearningQbankColumnsortorderSetColumnbankOrderRequest (

    @SerializedName("columns")
    val columns: kotlin.collections.List<kotlin.Any>? = null,

    /* Set global config setting, rather than user preference */
    @SerializedName("global")
    val global: kotlin.Boolean? = false

) {


}

