/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningBlockIomadCompanyAdminGetCompanies200ResponseWarningsInner
import org.openapitools.client.models.ElearningBlockIomadCompanyAdminGetLicenseInfo200ResponseLicensesInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param licenses 
 * @param warnings 
 */


data class ElearningBlockIomadCompanyAdminGetLicenseInfo200Response (

    @SerializedName("licenses")
    val licenses: kotlin.collections.List<ElearningBlockIomadCompanyAdminGetLicenseInfo200ResponseLicensesInner>,

    @SerializedName("warnings")
    val warnings: kotlin.collections.List<ElearningBlockIomadCompanyAdminGetCompanies200ResponseWarningsInner>? = null

) {


}

