/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningModH5pactivityGetResults200ResponseAttemptsInnerResultsInner

import com.google.gson.annotations.SerializedName

/**
 * The attempt general information
 *
 * @param attempt Attempt number
 * @param completion Attempt completion
 * @param duration Attempt duration in seconds
 * @param h5pactivityid ID of the H5P activity
 * @param id ID of the context
 * @param maxscore Attempt max score
 * @param rawscore Attempt score value
 * @param results 
 * @param scaled Attempt scaled
 * @param success Attempt success
 * @param timecreated Attempt creation
 * @param timemodified Attempt modified
 * @param userid ID of the user
 */


data class ElearningModH5pactivityGetResults200ResponseAttemptsInner (

    /* Attempt number */
    @SerializedName("attempt")
    val attempt: kotlin.Int? = null,

    /* Attempt completion */
    @SerializedName("completion")
    val completion: kotlin.Int? = null,

    /* Attempt duration in seconds */
    @SerializedName("duration")
    val duration: kotlin.Int? = null,

    /* ID of the H5P activity */
    @SerializedName("h5pactivityid")
    val h5pactivityid: kotlin.Int? = null,

    /* ID of the context */
    @SerializedName("id")
    val id: kotlin.Int? = null,

    /* Attempt max score */
    @SerializedName("maxscore")
    val maxscore: kotlin.Int? = null,

    /* Attempt score value */
    @SerializedName("rawscore")
    val rawscore: kotlin.Int? = null,

    @SerializedName("results")
    val results: kotlin.collections.List<ElearningModH5pactivityGetResults200ResponseAttemptsInnerResultsInner>? = null,

    /* Attempt scaled */
    @SerializedName("scaled")
    val scaled: java.math.BigDecimal? = null,

    /* Attempt success */
    @SerializedName("success")
    val success: kotlin.Int? = null,

    /* Attempt creation */
    @SerializedName("timecreated")
    val timecreated: kotlin.Int? = null,

    /* Attempt modified */
    @SerializedName("timemodified")
    val timemodified: kotlin.Int? = null,

    /* ID of the user */
    @SerializedName("userid")
    val userid: kotlin.Int? = null

) {


}

