/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * List of events to delete
 *
 * @param eventid Event ID
 * @param repeat Delete comeplete series if repeated event
 */


data class ElearningCoreCalendarDeleteCalendarEventsRequestEventsInner (

    /* Event ID */
    @SerializedName("eventid")
    val eventid: kotlin.Int? = ,

    /* Delete comeplete series if repeated event */
    @SerializedName("repeat")
    val repeat: kotlin.Boolean? = null

) {


}

