/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param courseid Filter badges by course id, empty all the courses
 * @param onlypublic Whether to return only public badges
 * @param page The page of records to return.
 * @param perpage The number of records to return per page
 * @param search A simple string to search for
 * @param userid Badges only for this user id, empty for current user
 */


data class ElearningCoreBadgesGetUserBadgesRequest (

    /* Filter badges by course id, empty all the courses */
    @SerializedName("courseid")
    val courseid: kotlin.Int? = 0,

    /* Whether to return only public badges */
    @SerializedName("onlypublic")
    val onlypublic: kotlin.Boolean? = false,

    /* The page of records to return. */
    @SerializedName("page")
    val page: kotlin.Int? = 0,

    /* The number of records to return per page */
    @SerializedName("perpage")
    val perpage: kotlin.Int? = 0,

    /* A simple string to search for */
    @SerializedName("search")
    val search: kotlin.String? = "",

    /* Badges only for this user id, empty for current user */
    @SerializedName("userid")
    val userid: kotlin.Int? = 0

) {


}

