/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningAuthEmailSignupUser200ResponseWarningsInner
import org.openapitools.client.models.ElearningModDataGetDatabasesByCourses200ResponseDatabasesInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param databases 
 * @param warnings 
 */


data class ElearningModDataGetDatabasesByCourses200Response (

    @SerializedName("databases")
    val databases: kotlin.collections.List<ElearningModDataGetDatabasesByCourses200ResponseDatabasesInner>,

    @SerializedName("warnings")
    val warnings: kotlin.collections.List<ElearningAuthEmailSignupUser200ResponseWarningsInner>? = null

) {


}

