/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param additionalfield Additional field for the user (email or ID number, for example)
 * @param feedbacktext The full feedback text
 * @param fullname Students name
 * @param picture Students picture
 * @param title Title of the grade item that the feedback is for
 */


data class ElearningCoreGradesGetFeedback200Response (

    /* Additional field for the user (email or ID number, for example) */
    @SerializedName("additionalfield")
    val additionalfield: kotlin.String,

    /* The full feedback text */
    @SerializedName("feedbacktext")
    val feedbacktext: kotlin.String,

    /* Students name */
    @SerializedName("fullname")
    val fullname: kotlin.String,

    /* Students picture */
    @SerializedName("picture")
    val picture: kotlin.String,

    /* Title of the grade item that the feedback is for */
    @SerializedName("title")
    val title: kotlin.String

) {


}

