/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param forumid forum instance id
 * @param page current page
 * @param perpage items per page
 * @param sortby sort by this element: id, timemodified, timestart or timeend
 * @param sortdirection sort direction: ASC or DESC
 */


data class ElearningModForumGetForumDiscussionsPaginatedRequest (

    /* forum instance id */
    @SerializedName("forumid")
    val forumid: kotlin.Int,

    /* current page */
    @SerializedName("page")
    val page: kotlin.Int? = -1,

    /* items per page */
    @SerializedName("perpage")
    val perpage: kotlin.Int? = 0,

    /* sort by this element: id, timemodified, timestart or timeend */
    @SerializedName("sortby")
    val sortby: kotlin.String? = "timemodified",

    /* sort direction: ASC or DESC */
    @SerializedName("sortdirection")
    val sortdirection: kotlin.String? = "DESC"

) {


}

