/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningAuthEmailSignupUser200ResponseWarningsInner
import org.openapitools.client.models.ElearningCoreFiltersGetAvailableInContext200ResponseFiltersInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param filters 
 * @param warnings 
 */


data class ElearningCoreFiltersGetAvailableInContext200Response (

    @SerializedName("filters")
    val filters: kotlin.collections.List<ElearningCoreFiltersGetAvailableInContext200ResponseFiltersInner>,

    @SerializedName("warnings")
    val warnings: kotlin.collections.List<ElearningAuthEmailSignupUser200ResponseWarningsInner>? = null

) {


}

