/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param assignid assignment instance id
 * @param groupid filter by users in group (used for generating the grading summary).                     0 for all groups information, any other empty value will calculate currrent group.
 * @param userid user id (empty for current user)
 */


data class ElearningModAssignGetSubmissionStatusRequest (

    /* assignment instance id */
    @SerializedName("assignid")
    val assignid: kotlin.Int,

    /* filter by users in group (used for generating the grading summary).                     0 for all groups information, any other empty value will calculate currrent group. */
    @SerializedName("groupid")
    val groupid: kotlin.Int? = 0,

    /* user id (empty for current user) */
    @SerializedName("userid")
    val userid: kotlin.Int? = 0

) {


}

