/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id message id
 * @param message message text
 * @param system true if is a system message (like user joined)
 * @param timestamp timestamp for the message
 * @param userid user id
 */


data class ElearningModChatGetChatLatestMessages200ResponseMessagesInner (

    /* message id */
    @SerializedName("id")
    val id: kotlin.Int? = null,

    /* message text */
    @SerializedName("message")
    val message: kotlin.String? = null,

    /* true if is a system message (like user joined) */
    @SerializedName("system")
    val system: kotlin.Boolean? = null,

    /* timestamp for the message */
    @SerializedName("timestamp")
    val timestamp: kotlin.Int? = null,

    /* user id */
    @SerializedName("userid")
    val userid: kotlin.Int? = null

) {


}

