/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningCoreGradesGraderGradingpanelScaleFetch200ResponseGradeOptionsInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param gradedby The assumed grader of this grading instance
 * @param maxgrade Max possible grade
 * @param options 
 * @param timecreated The time that the grade was created
 * @param timemodified The time that the grade was last updated
 * @param usergrade Current user grade
 */


data class ElearningCoreGradesGraderGradingpanelScaleFetch200ResponseGrade (

    /* The assumed grader of this grading instance */
    @SerializedName("gradedby")
    val gradedby: kotlin.String,

    /* Max possible grade */
    @SerializedName("maxgrade")
    val maxgrade: kotlin.String,

    @SerializedName("options")
    val options: kotlin.collections.List<ElearningCoreGradesGraderGradingpanelScaleFetch200ResponseGradeOptionsInner>,

    /* The time that the grade was created */
    @SerializedName("timecreated")
    val timecreated: kotlin.Int,

    /* The time that the grade was last updated */
    @SerializedName("timemodified")
    val timemodified: kotlin.Int,

    /* Current user grade */
    @SerializedName("usergrade")
    val usergrade: kotlin.String

) {


}

