/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningCoreReportbuilderRetrieveSystemReport200ResponseDataRowsInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param headers 
 * @param rows 
 * @param totalrowcount totalrowcount
 */


data class ElearningCoreReportbuilderRetrieveSystemReport200ResponseData (

    @SerializedName("headers")
    val headers: kotlin.collections.List<kotlin.Any>,

    @SerializedName("rows")
    val rows: kotlin.collections.List<ElearningCoreReportbuilderRetrieveSystemReport200ResponseDataRowsInner>,

    /* totalrowcount */
    @SerializedName("totalrowcount")
    val totalrowcount: kotlin.Int

) {


}

