/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningAuthEmailSignupUser200ResponseWarningsInner
import org.openapitools.client.models.ElearningModWorkshopGetWorkshopsByCourses200ResponseWorkshopsInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param workshops 
 * @param warnings 
 */


data class ElearningModWorkshopGetWorkshopsByCourses200Response (

    @SerializedName("workshops")
    val workshops: kotlin.collections.List<ElearningModWorkshopGetWorkshopsByCourses200ResponseWorkshopsInner>,

    @SerializedName("warnings")
    val warnings: kotlin.collections.List<ElearningAuthEmailSignupUser200ResponseWarningsInner>? = null

) {


}

