/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningCoreCompetencyDuplicateCompetencyFramework200Response

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param canmanage True if this user has permission to manage competency frameworks
 * @param framework 
 * @param pagecontextid Context id for the framework
 * @param pluginbaseurl Plugin base url
 * @param rulesmodules JSON encoded data for rules
 * @param search Current search string
 */


data class ElearningToolLpDataForCompetenciesManagePage200Response (

    /* True if this user has permission to manage competency frameworks */
    @SerializedName("canmanage")
    val canmanage: kotlin.Boolean,

    @SerializedName("framework")
    val framework: ElearningCoreCompetencyDuplicateCompetencyFramework200Response,

    /* Context id for the framework */
    @SerializedName("pagecontextid")
    val pagecontextid: kotlin.Int,

    /* Plugin base url */
    @SerializedName("pluginbaseurl")
    val pluginbaseurl: kotlin.String,

    /* JSON encoded data for rules */
    @SerializedName("rulesmodules")
    val rulesmodules: kotlin.String,

    /* Current search string */
    @SerializedName("search")
    val search: kotlin.String

) {


}

