/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param favourite favourite
 * @param manage manage
 * @param move move
 * @param pin pin
 * @param post post
 * @param subscribe subscribe
 */


data class ElearningModForumSetPinState200ResponseCapabilities (

    /* favourite */
    @SerializedName("favourite")
    val favourite: kotlin.Boolean,

    /* manage */
    @SerializedName("manage")
    val manage: kotlin.Boolean,

    /* move */
    @SerializedName("move")
    val move: kotlin.Boolean,

    /* pin */
    @SerializedName("pin")
    val pin: kotlin.Boolean,

    /* post */
    @SerializedName("post")
    val post: kotlin.Boolean,

    /* subscribe */
    @SerializedName("subscribe")
    val subscribe: kotlin.Boolean

) {


}

