/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningCoreBlockGetDashboardBlocks200ResponseBlocksInnerContentsFilesInner
import org.openapitools.client.models.ElearningModDataGetEntries200ResponseEntriesInnerTagsInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param approved Whether the entry was approved
 * @param attachment Whether or not the entry has attachments
 * @param attachments 
 * @param casesensitive When true, the matching is case sensitive
 * @param concept The concept
 * @param definition The definition
 * @param definitionformat definition format (1 = HTML, 0 = MOODLE, 2 = PLAIN, or 4 = MARKDOWN)
 * @param definitioninlinefiles 
 * @param definitiontrust The definition trust flag
 * @param fullmatch When true, the matching is done on full words only
 * @param glossaryid The glossary ID
 * @param id The entry ID
 * @param sourceglossaryid The source glossary ID
 * @param tags 
 * @param teacherentry The entry was created by a teacher, or equivalent.
 * @param timecreated Time created
 * @param timemodified Time modified
 * @param usedynalink Whether the concept should be automatically linked
 * @param userfullname Author full name
 * @param userid Author ID
 * @param userpictureurl Author picture
 */


data class ElearningModGlossaryGetEntriesByAuthorId200ResponseEntriesInner (

    /* Whether the entry was approved */
    @SerializedName("approved")
    val approved: kotlin.Boolean? = null,

    /* Whether or not the entry has attachments */
    @SerializedName("attachment")
    val attachment: kotlin.Boolean? = null,

    @SerializedName("attachments")
    val attachments: kotlin.collections.List<ElearningCoreBlockGetDashboardBlocks200ResponseBlocksInnerContentsFilesInner>? = null,

    /* When true, the matching is case sensitive */
    @SerializedName("casesensitive")
    val casesensitive: kotlin.Boolean? = null,

    /* The concept */
    @SerializedName("concept")
    val concept: kotlin.String? = null,

    /* The definition */
    @SerializedName("definition")
    val definition: kotlin.String? = null,

    /* definition format (1 = HTML, 0 = MOODLE, 2 = PLAIN, or 4 = MARKDOWN) */
    @SerializedName("definitionformat")
    val definitionformat: kotlin.Int? = null,

    @SerializedName("definitioninlinefiles")
    val definitioninlinefiles: kotlin.collections.List<ElearningCoreBlockGetDashboardBlocks200ResponseBlocksInnerContentsFilesInner>? = null,

    /* The definition trust flag */
    @SerializedName("definitiontrust")
    val definitiontrust: kotlin.Boolean? = null,

    /* When true, the matching is done on full words only */
    @SerializedName("fullmatch")
    val fullmatch: kotlin.Boolean? = null,

    /* The glossary ID */
    @SerializedName("glossaryid")
    val glossaryid: kotlin.Int? = null,

    /* The entry ID */
    @SerializedName("id")
    val id: kotlin.Int? = null,

    /* The source glossary ID */
    @SerializedName("sourceglossaryid")
    val sourceglossaryid: kotlin.Int? = null,

    @SerializedName("tags")
    val tags: kotlin.collections.List<ElearningModDataGetEntries200ResponseEntriesInnerTagsInner>? = null,

    /* The entry was created by a teacher, or equivalent. */
    @SerializedName("teacherentry")
    val teacherentry: kotlin.Boolean? = null,

    /* Time created */
    @SerializedName("timecreated")
    val timecreated: kotlin.Int? = null,

    /* Time modified */
    @SerializedName("timemodified")
    val timemodified: kotlin.Int? = null,

    /* Whether the concept should be automatically linked */
    @SerializedName("usedynalink")
    val usedynalink: kotlin.Boolean? = null,

    /* Author full name */
    @SerializedName("userfullname")
    val userfullname: kotlin.String? = null,

    /* Author ID */
    @SerializedName("userid")
    val userid: kotlin.Int? = null,

    /* Author picture */
    @SerializedName("userpictureurl")
    val userpictureurl: kotlin.String? = null

) {


}

