/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param component component
 * @param contextlevel context level: course, module, user, etc...
 * @param instanceid the instance id of item associated with the context level
 * @param itemid associated id
 * @param ratingarea rating area
 * @param scaleid scale id
 * @param sort sort order (firstname, rating or timemodified)
 */


data class ElearningCoreRatingGetItemRatingsRequest (

    /* component */
    @SerializedName("component")
    val component: kotlin.String,

    /* context level: course, module, user, etc... */
    @SerializedName("contextlevel")
    val contextlevel: kotlin.String,

    /* the instance id of item associated with the context level */
    @SerializedName("instanceid")
    val instanceid: kotlin.Int,

    /* associated id */
    @SerializedName("itemid")
    val itemid: kotlin.Int,

    /* rating area */
    @SerializedName("ratingarea")
    val ratingarea: kotlin.String,

    /* scale id */
    @SerializedName("scaleid")
    val scaleid: kotlin.Int,

    /* sort order (firstname, rating or timemodified) */
    @SerializedName("sort")
    val sort: kotlin.String

) {


}

