/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningAuthEmailSignupUser200ResponseWarningsInner
import org.openapitools.client.models.ElearningModChoiceGetChoiceResults200ResponseOptionsInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param options 
 * @param warnings 
 */


data class ElearningModChoiceGetChoiceResults200Response (

    @SerializedName("options")
    val options: kotlin.collections.List<ElearningModChoiceGetChoiceResults200ResponseOptionsInner>,

    @SerializedName("warnings")
    val warnings: kotlin.collections.List<ElearningAuthEmailSignupUser200ResponseWarningsInner>? = null

) {


}

