/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningModDataGetEntries200ResponseEntriesInnerTagsInner

import com.google.gson.annotations.SerializedName

/**
 * Pages
 *
 * @param cachedcontent Page contents.
 * @param caneditpage True if user can edit the page.
 * @param contentformat cachedcontent format (1 = HTML, 0 = MOODLE, 2 = PLAIN, or 4 = MARKDOWN)
 * @param contentsize Size of page contents in bytes (doesn't include size of attached files).
 * @param firstpage True if it's the first page.
 * @param id Page ID.
 * @param pageviews Number of times the page has been viewed.
 * @param readonly 1 if readonly, 0 otherwise.
 * @param subwikiid Page's subwiki ID.
 * @param tags 
 * @param timecreated Time of creation.
 * @param timemodified Time of last modification.
 * @param timerendered Time of last renderization.
 * @param title Page title.
 * @param userid ID of the user that last modified the page.
 */


data class ElearningModWikiGetSubwikiPages200ResponsePagesInner (

    /* Page contents. */
    @SerializedName("cachedcontent")
    val cachedcontent: kotlin.String? = null,

    /* True if user can edit the page. */
    @SerializedName("caneditpage")
    val caneditpage: kotlin.Boolean? = null,

    /* cachedcontent format (1 = HTML, 0 = MOODLE, 2 = PLAIN, or 4 = MARKDOWN) */
    @SerializedName("contentformat")
    val contentformat: kotlin.Int? = null,

    /* Size of page contents in bytes (doesn't include size of attached files). */
    @SerializedName("contentsize")
    val contentsize: kotlin.Int? = null,

    /* True if it's the first page. */
    @SerializedName("firstpage")
    val firstpage: kotlin.Boolean? = null,

    /* Page ID. */
    @SerializedName("id")
    val id: kotlin.Int? = null,

    /* Number of times the page has been viewed. */
    @SerializedName("pageviews")
    val pageviews: kotlin.Int? = null,

    /* 1 if readonly, 0 otherwise. */
    @SerializedName("readonly")
    val readonly: kotlin.Int? = null,

    /* Page's subwiki ID. */
    @SerializedName("subwikiid")
    val subwikiid: kotlin.Int? = null,

    @SerializedName("tags")
    val tags: kotlin.collections.List<ElearningModDataGetEntries200ResponseEntriesInnerTagsInner>? = null,

    /* Time of creation. */
    @SerializedName("timecreated")
    val timecreated: kotlin.Int? = null,

    /* Time of last modification. */
    @SerializedName("timemodified")
    val timemodified: kotlin.Int? = null,

    /* Time of last renderization. */
    @SerializedName("timerendered")
    val timerendered: kotlin.Int? = null,

    /* Page title. */
    @SerializedName("title")
    val title: kotlin.String? = null,

    /* ID of the user that last modified the page. */
    @SerializedName("userid")
    val userid: kotlin.Int? = null

) {


}

