/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param restoreurl Restore url
 */


data class ElearningCoreBackupGetAsyncBackupLinksRestore200Response (

    /* Restore url */
    @SerializedName("restoreurl")
    val restoreurl: kotlin.String

) {


}

