/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param coursecount coursecount
 * @param depth depth
 * @param id id
 * @param idnumber idnumber
 * @param name name
 * @param nestedname nestedname
 * @param parent parent
 * @param timemodified timemodified
 * @param url url
 * @param visible visible
 * @param description description
 */


data class ElearningCoreCalendarGetActionEventsByCourse200ResponseEventsInnerCategory (

    /* coursecount */
    @SerializedName("coursecount")
    val coursecount: kotlin.Int = 0,

    /* depth */
    @SerializedName("depth")
    val depth: kotlin.Int = 0,

    /* id */
    @SerializedName("id")
    val id: kotlin.Int,

    /* idnumber */
    @SerializedName("idnumber")
    val idnumber: kotlin.String,

    /* name */
    @SerializedName("name")
    val name: kotlin.String = "",

    /* nestedname */
    @SerializedName("nestedname")
    val nestedname: kotlin.String,

    /* parent */
    @SerializedName("parent")
    val parent: kotlin.Int,

    /* timemodified */
    @SerializedName("timemodified")
    val timemodified: kotlin.Int = 0,

    /* url */
    @SerializedName("url")
    val url: kotlin.String,

    /* visible */
    @SerializedName("visible")
    val visible: kotlin.Int = 1,

    /* description */
    @SerializedName("description")
    val description: kotlin.String? = null

) {


}

