/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param dayno dayno
 * @param fullname fullname
 * @param shortname shortname
 */


data class ElearningCoreCalendarGetCalendarMonthlyView200ResponseDaynamesInner (

    /* dayno */
    @SerializedName("dayno")
    val dayno: kotlin.Int? = null,

    /* fullname */
    @SerializedName("fullname")
    val fullname: kotlin.String? = null,

    /* shortname */
    @SerializedName("shortname")
    val shortname: kotlin.String? = null

) {


}

