/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningCoreBlogGetEntries200ResponseEntriesInnerSummaryfilesInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param content Contents.
 * @param content1 Contents.
 * @param content2 Contents.
 * @param content3 Contents.
 * @param content4 Contents.
 * @param fieldid The field type of the content.
 * @param files 
 * @param id Content id.
 * @param recordid The record this content belongs to.
 */


data class ElearningModDataGetEntry200ResponseEntryContentsInner (

    /* Contents. */
    @SerializedName("content")
    val content: kotlin.String? = null,

    /* Contents. */
    @SerializedName("content1")
    val content1: kotlin.String? = null,

    /* Contents. */
    @SerializedName("content2")
    val content2: kotlin.String? = null,

    /* Contents. */
    @SerializedName("content3")
    val content3: kotlin.String? = null,

    /* Contents. */
    @SerializedName("content4")
    val content4: kotlin.String? = null,

    /* The field type of the content. */
    @SerializedName("fieldid")
    val fieldid: kotlin.Int? = 0,

    @SerializedName("files")
    val files: kotlin.collections.List<ElearningCoreBlogGetEntries200ResponseEntriesInnerSummaryfilesInner>? = null,

    /* Content id. */
    @SerializedName("id")
    val id: kotlin.Int? = null,

    /* The record this content belongs to. */
    @SerializedName("recordid")
    val recordid: kotlin.Int? = 0

) {


}

