/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param componentname frankenstyle name of the component to which the content item belongs
 * @param contentitemid id of the content item
 */


data class ElearningCoreCourseRemoveContentItemFromUserFavouritesRequest (

    /* frankenstyle name of the component to which the content item belongs */
    @SerializedName("componentname")
    val componentname: kotlin.String,

    /* id of the content item */
    @SerializedName("contentitemid")
    val contentitemid: kotlin.Int = 

) {


}

