/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ElearningAuthEmailSignupUser200ResponseWarningsInner
import org.openapitools.client.models.ElearningModGlossaryGetGlossariesByCourses200ResponseGlossariesInner

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param glossaries 
 * @param warnings 
 */


data class ElearningModGlossaryGetGlossariesByCourses200Response (

    @SerializedName("glossaries")
    val glossaries: kotlin.collections.List<ElearningModGlossaryGetGlossariesByCourses200ResponseGlossariesInner>,

    @SerializedName("warnings")
    val warnings: kotlin.collections.List<ElearningAuthEmailSignupUser200ResponseWarningsInner>? = null

) {


}

