package it.attendance100.mybicocca.ui.theme

import androidx.compose.ui.graphics.Color

val BicoccaWordmarkAccent = Color(0xFFD81648)

// Light scheme
internal val PrimaryLight = Color(0xFFD81648)
internal val OnPrimaryLight = Color(0xFFFFFFFF)
internal val PrimaryContainerLight = Color(0xFFFFD9DF)
internal val OnPrimaryContainerLight = Color(0xFF400014)
internal val SecondaryLight = Color(0xFF7A4F56)
internal val OnSecondaryLight = Color(0xFFFFFFFF)
internal val TertiaryLight = Color(0xFF7B5A2E)
internal val OnTertiaryLight = Color(0xFFFFFFFF)
internal val SurfaceLight = Color(0xFFFFFFFF)
internal val OnSurfaceLight = Color(0xFF1A0A10)
internal val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
internal val SurfaceContainerLowLight = Color(0xFFFFF8F9)
internal val SurfaceContainerLight = Color(0xFFFFF0F2)
internal val SurfaceContainerHighLight = Color(0xFFFFE1E6)
internal val SurfaceContainerHighestLight = Color(0xFFF8D5DA)
internal val OnSurfaceVariantLight = Color(0xFF6B4B53)
internal val OutlineLight = Color(0xFF9B7C82)
internal val OutlineVariantLight = Color(0xFFE8C8CE)

// Dark scheme
internal val PrimaryDark = Color(0xFFFFB1BE)
internal val OnPrimaryDark = Color(0xFF5B0017)
internal val PrimaryContainerDark = Color(0xFF7A1530)
internal val OnPrimaryContainerDark = Color(0xFFFFD9DF)
internal val SecondaryDark = Color(0xFFE5BCC2)
internal val OnSecondaryDark = Color(0xFF432229)
internal val TertiaryDark = Color(0xFFE9C28C)
internal val OnTertiaryDark = Color(0xFF412C04)
internal val SurfaceDark = Color(0xFF0B0808)
internal val OnSurfaceDark = Color(0xFFF3E7E9)
internal val SurfaceContainerLowestDark = Color(0xFF0F0606)
internal val SurfaceContainerLowDark = Color(0xFF140A0C)
internal val SurfaceContainerDark = Color(0xFF1A0D10)
internal val SurfaceContainerHighDark = Color(0xFF261317)
internal val SurfaceContainerHighestDark = Color(0xFF322028)
internal val OnSurfaceVariantDark = Color(0xFFB89398)
internal val OutlineDark = Color(0xFF7C5A60)
internal val OutlineVariantDark = Color(0xFF3A1B22)
