package it.attendance100.mybicocca.domain.model.account

/**
 * Identifier of a saved account: a random UUID generated by the app when a student first signs
 * in on this device, not a university identifier. A student signing in again is matched by the
 * Esse3 user id and keeps the existing value. Keys the stored credentials, the cached session
 * tokens, and every account-scoped Room row.
 */
@JvmInline
value class AccountId(val value: String)
